### ISSUE TITLE
duplicate categories on all-categories page

### ISSUE THREAD

**Issue by RomanBogachev** [LouisBarranqueiro/hexo-theme-tranquilpeak#149]
Hi! 

In all-categories & all-tags are the same names.
There are no errors, because at last theme - 'Hueman' was ok.
This is sub-category for category.
How i can combine them?
https://www.dropbox.com/s/90sf67lhufq5a28/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-11-21%2000.30.06.png?dl=0

**Comment by LouisBarranqueiro** [comment]
Hi man. Why are you talking about categories and sub-categories? Did you try to run `hexo clean`?

**Comment by RomanBogachev** [comment]
Yes, I tried. 
I have several categories: `CentOS`, `Gentoo`, `FreeBSD` and in each category have sub-category named `Tips & Tricks`, but they doesn't combined. 

If I had not tried it, I would not have turned to you for help ;)

**Comment by LouisBarranqueiro** [comment]
Then why talk about tags? :D sorry, I don't understand. I understood that you have duplicate items but are they tags or categories?

**Comment by RomanBogachev** [comment]
Sorry :)
My thoughts ahead of the fingers.
The problem with categories only. 

With tags the problem solved - it is my carelessness.

**Comment by LouisBarranqueiro** [comment]
can you show me one of your post that generated his duplicate please?

**Comment by RomanBogachev** [comment]
yes, of course.
http://bogachev.biz/categories/Unix-like/Tips-&-tricks

Also, I just noticed that when I open this category - it doesn`t show the articles. Perhaps, Is the problem in ampersand?

**Comment by LouisBarranqueiro** [comment]
Sorry man, i was talking about the source code of the post :D. Add front-matter of your post that generate a duplicace entry please

**Comment by RomanBogachev** [comment]
Sure.

```md
title: Добавление переменных окружения PATH CentOS
date: 2015-02-27 14:49:41
categories:
- CentOS
- Tips & tricks
tags:
- centos
clearReading: true
thumbnailImage: centos.png
thumbnailImagePosition: right
autoThumbnailImage: yes
metaAlignment: center
---
```

**Comment by LouisBarranqueiro** [comment]
In fact, there is no problem. But the view where Tranquilpeak show all categories and sub-categories is not appropriate in your case because if a i understand , you have this :  
- CentOS
    - Tips & tricks
- OS X
    - Tips & tricks
- Windows
    - Tips & tricks

And that why, it generate 3 **Tips & tricks** sub-categories. If you organize your posts like this :  

- Tips & tricks
    - CentOS
    - Windows
    - OS X

It should be good. I'm not asking you do to that but I can't do anything to solve this problem because its Hexo that generate this categories and sub-categories. Maybe, you should re-organize your categories and use tags too. In my opinion, you should declare **Tips & tricks** as the root category

**Comment by RomanBogachev** [comment]
But in another theme there are no problems. 
Thanks for your help. I will try to solve the problem yourself.

**Comment by LouisBarranqueiro** [comment]
There is no problems man, the theme just displayed all categories. and `CentOS/Tips & tricks` isn't the same categories that `Windows/Tips & tricks` Could you show me how the older theme was displaying all categories and subcategories

**Comment by RomanBogachev** [comment]
Of course.

#### Windows category
![](https://habrastorage.org/files/c96/ac2/9da/c96ac29da77e42c29511dd7ed78abc37.png)
#### CentOS category
![](https://habrastorage.org/files/c57/2ee/e4b/c572eee4b2e24fe08854f3589fdf367e.png)
#### Unix category
![](https://habrastorage.org/files/4bb/dee/850/4bbdee8509354c48a83015a22b0be6b4.png)
#### List of all categories
![](https://habrastorage.org/files/979/e1f/905/979e1f905c8c42abb6720c3e50f74f60.png)

**Comment by LouisBarranqueiro** [comment]
then, there is no bug, the views is just not adapted to display categories and subcategories. I'm gonna think about a new way to display them. Thank you.

**Comment by RomanBogachev** [comment]
I'm not saying that this is a bug) I wanted to find a solution.
Well, I will wait. Thank you too.

**Comment by LouisBarranqueiro** [comment]
Here is the new look: Do you want something else?
![capture d ecran 2015-12-11 a 18 37 29](https://cloud.githubusercontent.com/assets/4705626/11752018/6cb4edf4-a03d-11e5-843a-8a27202d2308.png)

**Comment by RomanBogachev** [comment]
Hi,

Yes, it is excellent. Thank You!

**Comment by LouisBarranqueiro** [comment]
Your welcome.
Do you want that the theme allow you to choose the character that prepend subcategories? (**E.g** : `/`, `-`) And by default, for you, what's the best : `/` or `-`?

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.5.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.5.0) is released and fix this issue :)

**Comment by RomanBogachev** [comment]
By default I use `-`. 

Thank you!
