### ISSUE TITLE
. in tags on all tags page 

### ISSUE THREAD

**Issue by tparnell8** [LouisBarranqueiro/hexo-theme-tranquilpeak#154]
links generated for the all tags page when a tag has a `.` character in the tag will create a bad link

for example if I had a tag of node.js right now it tries to go to /tags/node.js but hexo actually makes the url /tags/node-js

**Comment by LouisBarranqueiro** [comment]
Got it! I will fix this.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.5.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.5.0) is released and fix this issue :)
