### ISSUE TITLE
bump font-weight?

### ISSUE THREAD

**Issue by tparnell8** [LouisBarranqueiro/hexo-theme-tranquilpeak#155]
So this is just a general observation. I feel like regular text in posts get washed out a little with the background. I altered some of my css files where I bumped the font-weight to 400 and I set the default font size to 1.7rem, and the typography stood out sooo much better. 

Would you consider making these changes? I have heard from other people that they feel the font is a little muted as well.

**Comment by LouisBarranqueiro** [comment]
I'll try that. I come back to you

**Comment by tparnell8** [comment]
Thanks, its just a suggestion. Feel free to tell me I'm dumb. I'm not a designer. I don't know what really makes good design, but I do feel the font needs to be either bigger, or bolder, or some zazz that I am not aware of.

One of the things that I think makes the [ghostium theme](http://ghostium.oswaldoacauan.com/welcome-to-ghost/) stand out is how vivid the typography is.

Side note I do love your theme, so I really thank you for making it!

**Comment by LouisBarranqueiro** [comment]
Could you add a screen please? to see what it gives. Also which browser do you use?

**Comment by tparnell8** [comment]
Chrome

Steps to repro: 

set `.post` to `font-weight: 400`
set `body`  to `font-size: 1.7rem` 

![beforeafterblog](https://cloud.githubusercontent.com/assets/3459800/11672306/61ea9098-9ddd-11e5-91dd-093a50df1b3d.png)

**Comment by futurefeeling** [comment]
I also prefer to selecting a bolder font

**Comment by LouisBarranqueiro** [comment]
**Left** : After
**Right** : Before

Safari :  
![safari](https://cloud.githubusercontent.com/assets/4705626/11768772/7eaf907c-a1d7-11e5-9a45-fdf3e2a149e3.png)
Chrome :  
![chrome](https://cloud.githubusercontent.com/assets/4705626/11768775/85eaa228-a1d7-11e5-9315-99de36ae4373.png)
Firefox :  
![firefox](https://cloud.githubusercontent.com/assets/4705626/11768777/8940c9f2-a1d7-11e5-84f3-3c4ad52be056.png)

**Comment by tparnell8** [comment]
:+1:

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.5.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.5.0) is released and fix this issue :)

**Comment by futurefeeling** [comment]
good
