### ISSUE TITLE
No image galery

### ISSUE THREAD

**Issue by fega** [LouisBarranqueiro/hexo-theme-tranquilpeak#158]
hello, im triying to use tranquilpeak to create an image gallery, but the images appear one below of the other.

what can I do?

**Comment by LouisBarranqueiro** [comment]
Hi man. add the related code please

**Comment by fega** [comment]
Hello man, Im going to move to another closely related topic :
when I do click in a image the image disappears on the main text, look:

http://fega.github.io/blog/2015/12/03/Videojuegos-sangrilulentos/

the code is:

{% image fancybox  http://archive.globalgamejam.org/sites/default/files/uploads/2011/13965/ss1.jpg?1296360575 300px  "Game Blood 48:14 1" %}

and something similar for all of the small images.
how Can I solve this?

**Comment by LouisBarranqueiro** [comment]
Image gallery is working? 

Please open a new issue for this one. i'm on it.
