### ISSUE TITLE
Add supports for Kudos

### ISSUE THREAD

**Issue by xerosanyam** [LouisBarranqueiro/hexo-theme-tranquilpeak#164]
Kudos can be added to each blog http://kudosplease.com/

**Comment by LouisBarranqueiro** [comment]
Could you explain what is this? What's a Kudos?

**Comment by xerosanyam** [comment]
Basically it is used to thank the writer. When you read a blog and you like it, you give writer a kudo.  
It's important because it shows popularity or a blog or the writer.  
Presently, blogs based on jekyll fail to showcase the traffic on the website. 
If you know a lot of people has visited and liked that blog, you become satisfied that the thing you will read will be worth the time.

**Comment by LouisBarranqueiro** [comment]
Could you propose an implementation to see the result and create a pull request?

**Comment by xerosanyam** [comment]
Sure. :+1:
