### ISSUE TITLE
Why I clicked post table, it let me to the top of post

### ISSUE THREAD

**Issue by xiejiachen** [LouisBarranqueiro/hexo-theme-tranquilpeak#173]
<img width="456" alt="2015-12-10 22 27 00" src="https://cloud.githubusercontent.com/assets/16185716/11730451/2b4e9dc0-9f8d-11e5-8691-555a1c59e109.png">

**Comment by LouisBarranqueiro** [comment]
If there is no table of content in the post, then it go to the top. if there is one, it go to the top of the table of content

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.5.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.5.0) is released and fix this issue :)
