### ISSUE TITLE
how can i get this list style

### ISSUE THREAD

**Issue by gilnuy** [LouisBarranqueiro/hexo-theme-tranquilpeak#180]
how can i get the list style like this:
[http://kaedea.com/](http://kaedea.com/)
and,now my is like this:
[http://gilnuy.github.io/](http://gilnuy.github.io/)

please help,thank you~

**Comment by LouisBarranqueiro** [comment]
You have to use `<!-- more -->` or `<!-- excerpt -->` comment in your post content. Read [user documentation - Writing post](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#define-post-excerpt)

**Comment by gilnuy** [comment]
it works , thx

**Comment by LouisBarranqueiro** [comment]
you're welcome :)
