### ISSUE TITLE
the post does not have <meta name="keywords" element

### ISSUE THREAD

**Issue by yirankiller** [LouisBarranqueiro/hexo-theme-tranquilpeak#182]
I configured :
layout: post
description: Mysql 
title: install mysql
keywords: Mysql
in the post.md ,but the post page does not generate the 
<meta name="keywords" content="Mysql" > element.does we support keywords ?

**Comment by LouisBarranqueiro** [comment]
No, the theme hasn't this feature. Are you able to implement it and create a pull request?

**Comment by yirankiller** [comment]
Of course, no problem

**Comment by LouisBarranqueiro** [comment]
Your implementation is a bit too complicated (#186) . I implemented something more simple.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.0) is released and solve this issue
