### ISSUE TITLE
all tags page, tag url does not respect the tag_dir setting in _config.yml

### ISSUE THREAD

**Issue by tparnell8** [LouisBarranqueiro/hexo-theme-tranquilpeak#184]
In the all-tags page, the tag url does not respect the tag_dir setting.

For example I converted from ghost, and the tags directory in ghost is /tag but in hexo default its /tags

I altered the setting in [my _config.yml](https://github.com/tparnell8/blog.tparnell.io/blob/master/_config.yml#L23) (the one for hexo) to change  the tag directory from /tags to /tag

However you have [hard coded](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/385ba9ac150b39d786f991dd06abae9cc5c5f8c1/layout/all-tags.ejs#L17) the url to be /tags 

This results in a 404 since my tags directory is `/tag` and not `/tags`

**Comment by LouisBarranqueiro** [comment]
I will fix that. got it!

**Comment by tparnell8** [comment]
Thanks for both being fast in responses and making an awesome theme!!!!

**Comment by LouisBarranqueiro** [comment]
I also fix the same bug for archives

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.0) is released and solve this issue
