### ISSUE TITLE
Example Post

### ISSUE THREAD

**Issue by bryanj4** [LouisBarranqueiro/hexo-theme-tranquilpeak#185]
Can you post a sample post with all of your working bells and whistles for verrsion 1.2? I enter a thumbnailImage but it automatically looks for example.com/YYYY/MM/DD/example.jpg instead of going to example.com/assets/images/example.jpg

**Comment by theRiddler91** [comment]
I also cannont get the caption to work properly for the photo gallery. I have to remove the caption for the image to load. All of my site code will be up at [here](https://github.com/udaciouspeople/site)

**Comment by LouisBarranqueiro** [comment]
Did you enable post asset folder in you Hexo configuration file? Because, assets folder URL will be : `example.com/YYY/MM/DD/post-slug/example.jpg`.

I don't have anymore source of blog posts (v1.2). I recommend you to update the theme with the last version. Did you try to do that?
