### ISSUE TITLE
Custom results notifications

### ISSUE THREAD

**Issue by veshinak** [LouisBarranqueiro/hexo-theme-tranquilpeak#187]
Hello, Louis! Will you make phrases "... posts found", "... tags found" and "... categories found" customizable with language file, please?

**Comment by LouisBarranqueiro** [comment]
There are hard coded in javascript. I'm gonna do something to change this. What kind of sentences would you like to have?

**Comment by veshinak** [comment]
In Russian it would be better `words {num} words`, in English `{num} words`... Afraid, there is no universal answer. Besides, there is one more problem in Russian: we have 3 different plural strings for 0, 5-9 posts (comments or tags), 1 post (comment or tag) and 2-4 posts (comments or tags). [Here is](https://hexo.io/docs/internationalization.html#Templates) what I mean. Is it possible to make them work in right way?

**Comment by LouisBarranqueiro** [comment]
yeah, but It complicate a lot the code and take a lot of time for something very small. i'm gonna think about it.

What do you mean with same problem with ... ?

**Comment by veshinak** [comment]
I mean common difficulties, not problem with theme. Thanks.

**Comment by LouisBarranqueiro** [comment]
Hey @veshinak, I need your help to complete russian traduction. Pull request on **i18n-all-pages** if you can :)
