### ISSUE TITLE
How to change the blockquote p margin-top ?

### ISSUE THREAD

**Issue by YingshanDeng** [LouisBarranqueiro/hexo-theme-tranquilpeak#189]
![image](https://cloud.githubusercontent.com/assets/7246595/11931118/6c4b1c50-a824-11e5-9310-bb3c0d8dc3d5.png)

I don't like the blockquote p has 2em margin-top. How to reset it to 0? thank you!

**Comment by LouisBarranqueiro** [comment]
HI man! it's a bug, already fixed [#179](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/179). I'm gonna release new version tonight :)

**Comment by YingshanDeng** [comment]
@LouisBarranqueiro  I am so surprised for your quickly reply! Thank you! And I am looking forward to your new version! Come on :)

**Comment by LouisBarranqueiro** [comment]
Got it :) great new features and new style :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.0) is released and solve this issue
