### ISSUE TITLE
Cannot read property 'icon' of null

### ISSUE THREAD

**Issue by jahbini** [LouisBarranqueiro/hexo-theme-tranquilpeak#190]
I have been having trouble with the image tags described in your theme's docs.  I finally realized these extended tags were not in the version I first downloaded (v1.2.0), and downloaded both the `hexo-theme-tranquilpeak-built-for-production-1.5.0` and `hexo-theme-tranquilpeak-built-for-production-1.6.0`

Then (after adding my info to _config.yml in the tranquilpeak directory), I find that 1.5.0 throws an error when it tries to process an {% alert ... %} tag.  Version 1.6.0 throws a completely different error:

```
INFO  Generated: assets/css/jquery.fancybox.css
INFO  Generated: assets/css/jquery.fancybox-thumbs.css
INFO  Generated: assets/css/font-awesome.css
Unhandled rejection TypeError: /Users/jim/Documents/bamboo-snow/themes/tranquilpeak/layout/layout.ejs:18
    16|     <body>
    17|         <div id="blog">
 >> 18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>
    19|             <%- partial('_partial/sidebar', {sidebarBehavior: sidebarBehavior}) %>
    20|             <%- partial('_partial/post/header-cover', {post: page, sidebarBehavior: sidebarBehavior}) %>
    21|             <div id="main" data-behavior="<%= sidebarBehavior %>"

/Users/jim/Documents/bamboo-snow/themes/tranquilpeak/layout/_partial/header.ejs:3
    1| <!-- Define author's picture -->
    2| <% var authorPicture = null; %>
 >> 3| <% if (!theme.header.right_link.icon) { %>
    4|     <% if (theme.gravatar_email && theme.gravatar_email.length) { %>
    5|         <% authorPicture = gravatar(theme.gravatar_email, 90); %>
    6|     <% } else if (theme.author.picture && theme.author.picture.length) { %>

Cannot read property 'icon' of null
    at eval (eval at <anonymous> (/Users/jim/Documents/bamboo-snow/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:157)
    at eval (eval at <anonymous> (/Users/jim/Documents/bamboo-snow/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:3248)
```

Any suggestions are greatly appreciated.

**Comment by LouisBarranqueiro** [comment]
Alert tag is a new feature added in version 1.6.0.

**Comment by jahbini** [comment]
Here is the config file I am currently using
[_config.yml](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/70065/_config.yml.txt)

I also tried this one which worked with tranquil peak V1.2:
[config.yml](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/70085/config1.2.yml.txt)

Both die at the same place during hexo generate

**Comment by LouisBarranqueiro** [comment]
yeah, that's a bug, i'm gonna fix this. It not allowed to comment `header.right_link.icon` var. i'm gonna fix this. Give me 20 minutes, to release a patch :)

**Comment by LouisBarranqueiro** [comment]
In fact, what do you wanna to do? why did you comment these lines instead of remove value?

**Comment by jahbini** [comment]
I am not sure I commented out any lines.  The last couple of days have ben a flurry of bug finding and syntax blinding opportunities.

**Comment by LouisBarranqueiro** [comment]
It doesn't work because, you comment some line
``` 
header:
    right_link:
        # url:
        # icon:
        # class:
```
Default config :
``` 
header:
    right_link:
        url:
        icon:
        class:
```

**Comment by jahbini** [comment]
I started with V 1.2.0 which had those items commented out.  I did not change them when I moved them from 1.2.0 to 1.5.0 and 1.6.0.  (and if you have suggestions for what I should put here, I am your student)

-- this is the original text from that download:
```
# Header configuration
# The link at the right of the header is customizable
# You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
# DON'T edit `header`, `right_link`, `url`, `icon` and `class` variable name
header:
    right_link:
        # url: /#search
        # icon: search
        # class: st-search-show-outputs
```

**Comment by LouisBarranqueiro** [comment]
Use the last configuration file from tranquilpeak 1.6.0, and re-set your property, that's all :)

**Comment by jahbini** [comment]
Yes, I can proceed now.  Unfortunate that I started out with 1.2 (I have no idea where that download link came from -- it certainly was not my intention to use an early version -- I just found about tranquipeak 4 or 5 days ago)

Maybe a major version bump if many interface semantics have changed. Yes?

(And yes, this is a fabulous theme you have created: Bravissimo.  Ciao for now. )

**Comment by LouisBarranqueiro** [comment]
hum, I know where does the problem came from. Some days ago, i renamed the repository and the demo website was displayed with version 1.2 with link to download 1.2 version, that's why, you downloaded version 1.2. I contacted GitHub 3 days ago to remove the old site. It has been deleted yesterday.

Thank you man :)
