### ISSUE TITLE
image width and height attributes for {% image stuff %}

### ISSUE THREAD

**Issue by jahbini** [LouisBarranqueiro/hexo-theme-tranquilpeak#193]
I have looked at the code in `tranquilpeak/scripts/tag/image.js` -- specifically the behavior of the rSize Regex.  It seems to accept some odd looking sizes and rejects seemingly normal specs.

I ran hexo under the node debugger and this is what happens for some sample size specs:
```
> rSize.test('30.0')
true
> rSize.test('30px')
false
> rSize.test('30:')
true
> rSize.test('30.0px')
true
> rSize.test('25%')
false
> rSize.test('25:%')
true
```

I suspect that this behavior is not what you intend.

**Comment by LouisBarranqueiro** [comment]
Yeah, you are right. There is a space in the regex, that's why it broke.
`/^\d+( ?:|\.\d+)(?:px|%)?$/;`
instead of 
`/^\d+(?:|\.\d+)(?:px|%)?$/;`

I will fix that. Thank you man

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.1) is released and solve this issue
