### ISSUE TITLE
incompatibility note

### ISSUE THREAD

**Issue by jahbini** [LouisBarranqueiro/hexo-theme-tranquilpeak#195]
During integration of Hexo and tranquilpeak into my bamboo snow site, I have had difficulty because
`<!-- more -->` and `<!-- excerpt -->` tags did not work.

I traced this to an incompatibility with `hexo-renderer-marked` and `hexo-renderer-markdown-it`

I may have incorrectly configured `hexo-renderer-markdown-it`, but it did not work with these tags, hexo's default `hexo-renderer-marked`  does.

Just thought you'd like to know

**Comment by LouisBarranqueiro** [comment]
it's `<!-- excerpt --> and ``. these tags are use by tranquilpeak to define post excerpt and post content. generators is something different, it is not bound

**Comment by jahbini** [comment]
yes, it's  of course, my mistake in syntax.  I have corrected the original issue posting.  (This is why I hate HTML's sucky escape sequences.  And {% tags %} are NOT my friend either. )

**Comment by LouisBarranqueiro** [comment]
then what does not work? is there an error message?

**Comment by jahbini** [comment]
no error message -- markdown-it escapes the chars and passes them through to the html output

**Comment by jahbini** [comment]
And now I'm back to getting my image tags right.  Whew!

**Comment by LouisBarranqueiro** [comment]
because your plugin should sanitize HTML, read documentation https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Advanced-Configuration#available-settings-explained and post an issue on their repository if you have a question

**Comment by jahbini** [comment]
Ahhh, a configuration param for markdown-it.  Can't just RTFM, you gotta ExperienceTFM.  No pain, no gain. (and I'm still getting my brain warped by image paths)

**Comment by LouisBarranqueiro** [comment]
:santa: is it working?

**Comment by jahbini** [comment]
With your help I believe I have mastered the "is it a bug or is it configuration" question for now.  Although I reserve the right to make many mistakes in the future.

_Yes._
Joyeux Noel
