### ISSUE TITLE
Landing page posts ordering

### ISSUE THREAD

**Issue by jahbini** [LouisBarranqueiro/hexo-theme-tranquilpeak#196]
Is there an alternate to using the front-matter `date` tag for posts ordering on the home page?

Is this a hexo question or a tranquilpeak question?

**Comment by LouisBarranqueiro** [comment]
tranquilpeak question :)

Yeah, currently posts are ordered by date. What do you want?

**Comment by jahbini** [comment]
Is this a possibility?

In the _config.yml `sort_by: priority`

in the post's front matter: `priority: alpha-numeric-value`

That way posts could by prioritized by sequence or alphabetic as needed -- no need to require unique priorities.

BTW -- see my latest tranquilpeak efforts at http://jahbini.github.io/bamboo-snow/ -- things are coming along nicely, thank you.

**Comment by LouisBarranqueiro** [comment]
I'm gonna think about it. :) Why do you need something like that?

**Comment by jahbini** [comment]
Currently I'm hacking this with "funny dates" -- which get an ordering of posts that I can live with.  No action needed on your part (unless you really want to...)

I am documenting many attributes of a newly cataloged substance: the powder from the natural deay of bamboo.  It seems that while there are dozens (or hundreds) of products and uses that this substance can be used for, it has never been examined closely by anyone.  Ever.

The ordering of this information for quick understanding and access is important. check out http://bamboosnow.com/

**Comment by LouisBarranqueiro** [comment]
Since you wanna present products and not articles, create a custom page to present them, will be better :)
