### ISSUE TITLE
About inserting multiple images of the same height

### ISSUE THREAD

**Issue by eaglesky** [LouisBarranqueiro/hexo-theme-tranquilpeak#197]
Hi Louis,

I was wondering how to insert multiple images of the same height. According to `tranquilpeak/scripts/tag/image.js` if I only specify the height it will always be read as width. A workaround might be checking whether the thumbnail width is zero or not before generating the width attribute:
```
        // Build the image HTML structure
        var image = '<img class="fig-img" src="' + (thumbnail || original) + '" ';
        // add image size
        if (thumbnailWidth || thumbnailHeight) {
            image += 'style="';
            // add width
            if (thumbnailWidth && (thumbnailWidth != '0')) {
                image += 'width:' + thumbnailWidth + ';';
            }
            // add height
            if (thumbnailHeight && (thumbnailHeight != '0')) {
                image += 'height:' + thumbnailHeight + ';';
            }
            image += '"';
        }
```
In this way if I write something like this :
 `{% image fancybox right /images/projects/push.png 0 270 "Real Time Recognition" %}`
 the thumbnail should have the height of 270 and the width is ignored. 

Thanks!

**Comment by LouisBarranqueiro** [comment]
you have to precise the unit. Put `0px` and `270px` in your case. Check [image](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#image) documentation for more information

**Comment by LouisBarranqueiro** [comment]
I just release a patch [Tranquilpeak v1.6.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.1), regex for size was broken.
