### ISSUE TITLE
CoverImage and thumbnailImage generation error on local images folder

### ISSUE THREAD

**Issue by nerdomancer** [LouisBarranqueiro/hexo-theme-tranquilpeak#198]
Hello!

First of all, I really like your theme. Thank you for your effort!

I might have noticed a bug. 

head-cover.ejs

```javascript
<%
    // Generate cover image url
    var coverImageUrl;

    if (post.coverImage) {
        if (post.coverImage.indexOf('://') >= 0) {
            coverImageUrl = post.coverImage;
        }
        else {
            coverImageUrl = url_for(post.path.replace('.html', '/') + post.coverImage);
        }
%>
```
When I place my cover image in my assets/images folder of the theme, cover image html tag is generated as "http://localhost:4000/permalink-setting/post-name/cover.jpg" but it should be a relative address like "/assets/images/cover.jpg"

I also saw the same issue in index.ejs.
When I update them as follows, everyhing is generated correctly and it works:

```javascript
<%
    // Generate cover image url
    var coverImageUrl;

    if (post.coverImage) {
        if (post.coverImage.indexOf('://') >= 0) {
            coverImageUrl = post.coverImage;
        }
        else {
            coverImageUrl = url_for(theme.image_dir + '/' + post.coverImage);
        }
%>
```

I can create a pull request for these two files if you agree.

**Comment by LouisBarranqueiro** [comment]
cover image must be put in post asset folder, not in main asset folder. otherwise use an absolute url

**Comment by nerdomancer** [comment]
But if that's the case, it is not automatically placed in there during generation. (hexo generate) Is there any more setting that I should update there?

**Comment by LouisBarranqueiro** [comment]
Did you enable post asset folder? [enable post asset folder](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-post-assets-folder)

**Comment by nerdomancer** [comment]
Yes, it is enabled in config.yml

**Comment by LouisBarranqueiro** [comment]
then, when you create your post with `hexo new post "post name"` a folder (`post-name`) has been created next your `post-name.md` file. Put your cover image into. read [user](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#front-matter-settings) documentation, everything is explained.

**Comment by nerdomancer** [comment]
Oh, I was migrating from a different theme, that's why my old posts were not getting that asset folder. When I create a new post, asset folder is getting generated.

Thanks!

**Comment by LouisBarranqueiro** [comment]
you're welcome :)
