### ISSUE TITLE
comment button is unavailable when i use duoshuo

### ISSUE THREAD

**Issue by zhengfuwang** [LouisBarranqueiro/hexo-theme-tranquilpeak#200]
In the 1.6.1 version, actions.ejs  `post.comments ` :

    <% if (post.comments) { %>
        <li class="post-action">
            <a class="post-action-btn btn btn--default" href="#disqus_thread">
                <i class="fa fa-comment-o"></i>
            </a>
        </li>
    <% } %>

when i use duoshuo-comment, click on the article comments button, the page can not be switched to comment view. 

this my settings

    <% if (post.comments) { %>
        <li class="post-action">
            <% if (theme.disqus_shortname) { %>
                <a class="post-action-btn btn btn--default" href="#disqus_thread">
                    <i class="fa fa-comment-o"></i>
                </a>
            <% } else if (theme.duoshuo_shortname) { %>
                <a class="post-action-btn btn btn--default" href="#ds-thread">
                    <i class="fa fa-comment-o"></i>
                </a>
            <% } %>
        </li>
    <% } %>

**Comment by LouisBarranqueiro** [comment]
I'm gonna fix this. Give me 30 minutes to release a new version :) Happy new year :D

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.6.2](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.6.2) is released and solve this issue

**Comment by zhengfuwang** [comment]
Happy new year :+1:
