### ISSUE TITLE
Add my blog to showcase

### ISSUE THREAD

**Issue by eaglesky** [LouisBarranqueiro/hexo-theme-tranquilpeak#201]
Hi Louis,

I finally completed migrating my old blog to Hexo using your theme!

URL: http://eaglesky.github.io/
Changes: 
1. Background picture.
2. Font size and color. (I personally think the fonts in the pure black color look much clearer than the original gray color)
3. Text width
4. "Go to top" icon
5.  Removed Disqus identifier to solve problems when migrating the comments

Please add my blog to the showcase.

Thank you!

**Comment by LouisBarranqueiro** [comment]
Hey Yalun. Thank you for using this theme :)
