### ISSUE TITLE
this theme does not work well with me

### ISSUE THREAD

**Issue by Medusar** [LouisBarranqueiro/hexo-theme-tranquilpeak#203]
i like your theme very much, but when i clone your theme to my workspace, and i change the "theme" variable in my _config file, it does not work when i start the server,   can you help me with that?

**Comment by Medusar** [comment]
when i generated the website and visit by localhost:4000, all the stylesheets and some js files are not avaliable, here is the picture:http://7xo4v8.com1.z0.glb.clouddn.com/aaaa.jpg ， and the css file's path is like： http://localhost:4000/assets/css/jquery.fancybox.css  ，it seems that the css files does not exist in the generated public folder

**Comment by LouisBarranqueiro** [comment]
Hi man. You downloaded the source and not the built-for-production version, then all dependencies are not included. So build the theme [dev doc - build](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#build) or download the built for production version : [hexo-theme-tranquilpeak-built-for-production-1.6.2.zip](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/download/v1.6.2/hexo-theme-tranquilpeak-built-for-production-1.6.2.zip).

I wrote a README, a user doc and dev doc then read them, everything is explained :D

**Comment by Medusar** [comment]
i can not connect to the 'github-cloud.s3.amazonaws.com',would you please send me an email or upload the zip file to somewhere else?  thank you so much, and my email address is '939958749@qq.com'.
