### ISSUE TITLE
Some imperfections of code blocks

### ISSUE THREAD

**Issue by tufu9441** [LouisBarranqueiro/hexo-theme-tranquilpeak#204]
When scroll bars of code blocks appear, the line numbers cannot align with the content, such as the case of [SQL](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/03/23/highlighted-code-showcase/#SQL) and [Swift](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/03/23/highlighted-code-showcase/#Swift) in your demo site.
![6888593F-86D2-4635-8CF2-446DB85D3351.png](https://ooo.0o0.ooo/2016/01/10/56931b5a1bb2d.png)

Besides, for all [Markdown](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/03/23/highlighted-code-showcase/#Markdown) codes, there is always a scroll bar along the vertical direction, and the line numbers cannot align with the content too.

The above mentioned problems did not exist before the release v1.6.0, I thinks it is because the position of  scroll bar was changed in new style highlight code blocks.

**Comment by LouisBarranqueiro** [comment]
Could you add your configuration? the only bug that is noticed is with Markdown when the screen width is < 393px

**Comment by tufu9441** [comment]
What do you mean by my configuration? I am not using this theme, but I tested it with the default configuration, which means I did not change anything in _config.yml. Besides, I migrate your highlight css to another theme, and the bug is the same.

**Comment by LouisBarranqueiro** [comment]
I mean OS and browser used

**Comment by tufu9441** [comment]
OSX, Safari and Chrome.

**Comment by LouisBarranqueiro** [comment]
with version please man :D

**Comment by tufu9441** [comment]
OS X El Captain 10.11.2
Safari 9.0.2(11601.3.9)
Chrome 47.0.2526.106 (64-bit)

**Comment by LouisBarranqueiro** [comment]
I got the same setup and didn't got that bug

**Comment by LouisBarranqueiro** [comment]
I'm gonna fix the bug with the Markdown code, but for the others, can't do anything if I can't reproduce the bug

**Comment by tufu9441** [comment]
That is so strange, if I use a PC of windows 8.1 with Chrome to visit your demo site, the bug does not appear. Can you reproduce the bug if you write a code block within some very long lines so that the horizontal scroll bar will appear?

**Comment by tufu9441** [comment]
I found the position of the scroll bar is the only difference in current version in comparison with the older version (before v1.6.0), whose scroll bar has nothing to do with the line numbers.

**Comment by LouisBarranqueiro** [comment]
huuuuuum, ok, I understand. Because, in   -> System preferences -> General : **Always** is checked. that's why. I checked the second option (show during scroll). I'm on it to fix that.

**Comment by tufu9441** [comment]
Yes, I see, I checked the second option and the bug disappeared. But I am still wondering why this bug never appeared in older versions, is it  also related to the highlight css?

**Comment by LouisBarranqueiro** [comment]
no, because in the new version, the gutter is fixed (to always have the line number) even if you scroll :)

**Comment by tufu9441** [comment]
OK I see, then hope to fix it soon. :)
