### ISSUE TITLE
 i18n missing

### ISSUE THREAD

**Issue by ghost** [LouisBarranqueiro/hexo-theme-tranquilpeak#205]
Filter scripts and reading time i18n are missing.
The former one seems hard to deal with... :(

**Comment by LouisBarranqueiro** [comment]
Hi man, I'm on it. About filter scripts, you mean "No categories found" and "categories found"?

**Comment by Imyssed** [comment]
Yep :)

**Comment by nyaatyan** [comment]
I have no ideas about the filter scripts too :(

**Comment by nyaatyan** [comment]
My commit disappeared!
Anyway you can referenced it >_<
