### ISSUE TITLE
Add my site to showcase

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-theme-tranquilpeak#208]
Hi Louis, will you add this: http://www.aerostatica.ru ?

Changes:
- background image
- fontsize & fonts
- sidebar width 
- GOOGLE+ share button changed to VK.COM share button
- custom meta added
- custom behavior of about page (it is opening by clicking on copyright)
- changed the view of "/all-categories" because of some strange site categories' specific :)

Thanks!

**Comment by nyaatyan** [comment]
About the last change,I think Louis just forgot to add styles to them :joy:

**Comment by aerohub** [comment]
Louis, he is on to our little game!

**Comment by LouisBarranqueiro** [comment]
@aerohub 
> because of some strange site categories' specific :)
@ghost
> About the last point,I think Louis just forgot to add styles to them
what are you talking about? :D
