### ISSUE TITLE
About don't display 'bio' neither 'job'

### ISSUE THREAD

**Issue by falosempre** [LouisBarranqueiro/hexo-theme-tranquilpeak#209]
In about is display the variables 'bio' and 'job' than the values.

**Comment by LouisBarranqueiro** [comment]
Hi man. Did you read the user documentation [language configuration](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#language-configuration) and [author configuration](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#author)?
