### ISSUE TITLE
How to change value of .main-content-wrap

### ISSUE THREAD

**Issue by mgerzabek** [LouisBarranqueiro/hexo-theme-tranquilpeak#210]
Hi Louis,

First of all thanks for this great theme! I hope, I will be able to customize it to my own ideas.

I want to change the width of the main body, which should be easliy achieved by setting
``` 
$main-content 'max-width' in themes/tranquilpeak/source/_css/utils/-variables.scss
```
But somehow the width of .main-content-wrap stays the same. I did try hexo clean, restarted node, checked the .scss files here and there but none worked for me. Currently I have no clue what else could I do. Any help appreciated.

Regards,
Michael

**Comment by LouisBarranqueiro** [comment]
Hi man. Thank you, I really appreciate. You just have to build the theme, to generate the new css file with your changes. Read developer documentation to learn how to do that : [developer doc - build theme](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#build)

**Comment by mgerzabek** [comment]
Thank You Louis for the quick response!

Okay, I have problems installing the dependencies. My system Windows 7 64bit, installed the latest Node with .msi Installer, Path is up to date, npm installed with Node Installer, hexo and the other tools installed with the cmds outlined in your developer page. But then section Build something goes wrong.
At the project directory ...
```
> npm install
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
> bower install
bower ENOENT        No bower.json present
```
I have to admit I'm a complete novice to all this fancy js stuff, but I like it  lot. So where should I look for further hints on what didn't go well.
Thanks for any hints!
Regards,
Michael

**Comment by mgerzabek** [comment]
Okay, that did it. Thanks a lot man!
I was unsure about where to call npm and bower dependencies. 
For the records, it's the theme folder
```
HEXO_PROJECT_HOME/themes/tranquilpeak> npm install
HEXO_PROJECT_HOME/themes/tranquilpeak> bower install
```

**Comment by LouisBarranqueiro** [comment]
yeah :)

**Comment by hilen** [comment]
I change the `tranquilpeak/source/_css/utils/_variables.scss` file. Then run `npm install`, `bower install`. But it not works, why?

**Comment by LouisBarranqueiro** [comment]
As I said, you have to built the theme. So run `grunt build` or `grunt buildProd` (before deployment), and that's it. :)

**Comment by maireh** [comment]
Is there a way to change max-width at the site level? 

I also love your theme - and I also want to change max-width. I don't really want to fork the theme since you still seem to be in active development. I will fork the theme if it is the only way.
