### ISSUE TITLE
Thumbnail Image not working correctly

### ISSUE THREAD

**Issue by joelrdz** [LouisBarranqueiro/hexo-theme-tranquilpeak#213]
I am following the exact steps that you wrote in the user documentation and I'm using the 'hexo-theme-tranquilpeak-prod-1.6.2' version of tranquilpeak. I choose the thumbnail image to appear on the left in the config.yml but the thumbnail image appears always on the bottom.

I also tried to overwrite it in the frontmatter of the post as an option, but it still puts the image in the bottom.

Please help me :(

**Comment by LouisBarranqueiro** [comment]
Hey man. Could you add useful information from theme `_config.yml` and front-matter of your post, please

**Comment by yuanchenhao** [comment]
The other problem related to **Thumbnail Image** and **Post Image**:what the format of image link for adding the external link?(I want to use external CDN service)

#### I tried three kind of external format
1.**The way add image to the post**`![image](https://cdn-images-1.medium.com/max/1600/1*r1aF7Ypb1rAvYLCfdh2Yag.png "Image2")
My setting in the post .md file is like this`

this format works ok in the page content but do not work in the Setting Part,it will show error info like this:`YAMLException:tag suffix cannot contain flow indicator characters at line 10, column 60`when I try to debug locally.

2.**like adding to the gallery** `https://cdn-images-1.medium.com/max/1600/1*r1aF7Ypb1rAvYLCfdh2Yag.png "Image2"`

3.**Directly Copy the link** like this
`title: xxxxxxxx`
`date: 2016-02-22 00:40:50`
`clearReading: true`
`thumbnailImage: http://7xr4z2.com1.z0.glb.clouddn.com/gitlab.png`
`thumbnailImagePosition: bottom`
`autoThumbnailImage: yes`
`metaAlignment: center`
`coverImage: https://cdn-images-1.medium.com/max/1600/1*r1aF7Ypb1rAvYLCfdh2Yag.png "Image2")`
`coverCaption: "A beautiful sunrise"`
`coverMeta: out`

all of these ways of inserting image did not work for me.So I am coming to seek your help.Thx a lot

**Comment by yuanchenhao** [comment]
<img width="797" alt="2016-02-22 19 46 50" src="https://cloud.githubusercontent.com/assets/5696660/13217420/38fc0774-d99d-11e5-8562-d20f7a97e8b9.png">
The effect is like this now

**Comment by joelrdz** [comment]
Here's my config yml:

# Tranquilpeak
# Version : 1.6.2
# Author : Louis Barranqueiro

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/_images` folder and
# use grunt task `build` to synchronize assets


# Image directory (default: images)
image_dir: assets/images


# Sidebar Configuration
#    You can add groups of links and links much as you want
#    You just have to respect the indentation : `groups of links` -> `link` -> `title, link, icon`
#    E.g:
#    -------------
#    sidebar:                   # DON'T modify this variable name
#         menu:                 # Name of your groups of links (changeable)
#             home:             # Name of your link (changeable)
#                title: Home    # Title of your link displayed
#                url: /         # URL of the link. If the URL is internal, domain name is not necessary
#                icon: home     # Name of the font awesome icon class without the `fa-`
#                               # Go to http://fontawesome.io/icons/ to find class name of icon
sidebar:
    menu:
        home:
            title: global.home
            url: /
            icon: home
        categories:
            title: global.categories
            url: /all-categories
            icon: bookmark
        tags:
            title: global.tags
            url: /all-tags
            icon: tags
        archives:
            title: global.archives
            url: /all-archives
            icon: archive
        search:
            title: global.search
            url: /#search
            icon: search
            # `st-search-show-outputs` classes are used to open swiftype search window
            class: st-search-show-outputs
        about:
            title: global.about
            url: /#about
            icon: question
    author_links:
        # github:
        #     title: global.github
        #     url: https://github.com/
        #     icon: github
        # stack_overflow:
        #     title: global.stack_overflow
        #     url: http://stackoverflow.com/users
        #     icon: stack-overflow
        # twitter:
        #     title: global.twitter
        #     url: https://twitter.com/
        #     icon: twitter
        # facebook:
        #     title: global.facebook
        #     url: https://facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: global.google_plus
        #     url: https://plus.google.com/
        #     icon: google-plus
        # linked_in:
        #     title: global.linkedin
        #     url: https://www.linkedin.com/profile/
        #     icon: linkedin
        # mail:
        #     title: global.mail
        #     url: mailto:
        #     icon: envelope-o
    rss:
        rss:
            title: global.rss
            url: /atom.xml
            icon: rss


# Header configuration
# The link at the right of the header is customizable
# You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
# By default, author's gravatar or author's picture is displayed if `icon` is empty
# DON'T edit `header`, `right_link`, `url`, `icon` and `class` variable name
# E.g to display a shortcut to open swiftype search window :
#     url: /#search
#     icon: search
#     class: st-search-show-outputs
header:
    right_link:
        url: /#about
        icon:
        class:


# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
    email:
    location:
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production)
    # or you can use an external url
    # Overwritten by your gravatar image if `gravatar_email` is filled
    picture:
    # Your Twitter username without the @. E.g : `tranquilpeak`
    twitter:
    # Your google plus profile id. E.g : `+Tranquilpeak` or `123812884128439`
    google_plus:


# Customization
# Define the behavior of the sidebar
# 1: Display large sidebar on large screen, medium sidebar on medium screen and header bar on small screen
# and large sidebar is swiped
# 2: Display medium sidebar on large and medium screen and header bar on small screen and medium sidebar is swiped (default)
# 3: Display header bar on all screens and large sidebar is swiped
# 4: Display header bar on all screens and medium sidebar is swiped
sidebar_behavior: 1
# Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
clear_reading: true
# Head title displayed at the top of the table of contents.
toc_title: Table of contents
# Display thumbnail image of each post on index pages (false: disabled, true: enabled)
thumbnail_image: true
# Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
# Set this value to `right` if you have old posts to keep the old style on them
# and define `thumbnailImagePosition` on a post to overwrite this setting
thumbnail_image_position: right
# Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
# Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
# and set `autoThumbnailImage` to `false` on a post to overwrite this setting
auto_thumbnail_image: true
# Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.
# Current image is on AWS S3 and delivered by AWS CloudFront.
# Otherwise put your image in folder `source/_images/` (development)  or in `source/assets/images/` if you can't or don't want to build the theme,
# and use relative url : `your-image.png`
cover_image: cover.jpg
# Your favicon located in folder `source/_images/` (development) or in `source/assets/images/` (production)
favicon:
# Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
image_gallery: true
# Pagination behavior of archive, category and tag pages (false: pagination disabled, true: pagination enabled)
archive_pagination: true
category_pagination: true
tag_pagination: true


# Integrated services
# You can't use Disqus and Duoshuo together
# then fill the right shortname
# Your Disqus shortname
disqus_shortname:
# Your Duoshuo shortname
duoshuo_shortname:
# Your Google analystics web property ID : UA-XXXXX-X
google_analytics_id:
# Your Baidu analystics web property ID : 9505a5af654a2478f93fd6c0ae4f687d
baidu_analytics_id:
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatar_email:
# Your swiftype install key
swiftype_install_key:
# Your Facebook user ids used to connect your blog with your facebook user accounts (Facebook Insights). Separate ids with comma. e.g : 9830047,1003342
fb_admin_ids:
# Your Facebook app id used to connect your blog with your facebook app account (Facebook Insights). E.g : 9841307
fb_app_id:

**Comment by joelrdz** [comment]
There are both files, I've deleted all and started clean with hexo and tranquilpeak several times, but the thumbnail image keeps appearing in the bottom. 

![captura de pantalla 2016-02-25 a las 1 15 56 p m](https://cloud.githubusercontent.com/assets/5441531/13331182/f4a7331a-dbc1-11e5-8d53-37d33f9dee9a.png)

**Comment by LouisBarranqueiro** [comment]
Could you try to download the latest version and replace your current version to make sure all layouts are correct, please?

**Comment by joelrdz** [comment]
I am using 

tranquilpeak: 1.6.2
Hexo: 3.1.1
hexo-cli: 1.0.1

I am using these versions, I've already deleted everything and started again, but the problem persists.

**Comment by LouisBarranqueiro** [comment]
add your node version and OS version please :)

**Comment by joelrdz** [comment]
node v5.4.1
npm 3.5.3

**Comment by LouisBarranqueiro** [comment]
Got the same configuration and everything is working fine. Get the [1.7.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.7.0) version just released and try again man.

**Comment by LouisBarranqueiro** [comment]
Is it fixed?

**Comment by LouisBarranqueiro** [comment]
I just fixed a bug on the thumbnail image position #240. New version available in some days. sorry, I just detect the bug now by doing other stuff.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released and fix this issue :)
