### ISSUE TITLE
image auto prefix with / ??

### ISSUE THREAD

**Issue by XGHeaven** [LouisBarranqueiro/hexo-theme-tranquilpeak#216]
I upgrade from 1.3.0 to 1.6.2

In follow Markdown
```markdown
![image](image.jpg)
```
will generate `...href="image.jpg"...` in before version, and `...href="/image.jpg"...` in 1.6.2 version

how to prevent that??

**Comment by LouisBarranqueiro** [comment]
Hey man. It doesn't come from the theme, I did some tests and `![image](image.jpg)` -> `<img src="image.jpg" alt="test">` without `/`. Did you update some packages responsible of rendering like `hexo-renderer-marked`, or directly Hexo?

**Comment by XGHeaven** [comment]
my `hexo-renderer-marked` version is `0.2.8`, how about you?
And my deps is:

![image](https://cloud.githubusercontent.com/assets/9291212/12866841/76b67c4e-cd17-11e5-96af-05825d1bccd2.png)

**Comment by LouisBarranqueiro** [comment]
`0.2.4`, try with this version. Try to comeback with the old theme to check if it solve the issue

**Comment by XGHeaven** [comment]
I try `0.2.5` and `0.2.4`, the issue also occur.
And this issue only appear in `index` page. In single post page, everything is ok.

**Comment by XGHeaven** [comment]
I think that is hexo issue.
Best to use asset_img tag to infer a img asset.
