### ISSUE TITLE
Can not open disqus comment in individual page.

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/hexo-theme-tranquilpeak#217]
For example, if I create an "about me" folder fo individual page in Hexo, I can not open the disqus comment even if I have set "comments: true" in index.md of "about me".

Could you please consider to add this feature and give some support to add this?

**Comment by kaedea** [comment]
And here posts the content of `source/about/index.md`
```markdown
title: Teatime
date: 2016-2-7
comments: true
---
<!-- write something -->
```

**Comment by LouisBarranqueiro** [comment]
It should works, which version of tranquilpeak do you have?

**Comment by kaedea** [comment]
Yes, it works in the latest version, could you post the commit message where you fix it?

**Comment by LouisBarranqueiro** [comment]
every changes is linked in the release :) 
commit : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/af0375ecdc2fc7fee2daa7499dd528fe225f8b01

**Comment by kaedea** [comment]
thank u, the helps.
