### ISSUE TITLE
How can I change the syntax highlighting theme?

### ISSUE THREAD

**Issue by hanmomhanda** [LouisBarranqueiro/hexo-theme-tranquilpeak#220]
Thanks for the gorgeous theme!

I want dark theme such as Zenburn for the syntax highlighting.

I found that _highlight-text.scss is responsible for the syntax highlighting from the documents, 
but I could not find how to apply other theme file nicely instead of editing _highlight-text.css file line by lines.

Could you tell me how to change the syntax highlighting?

**Comment by LouisBarranqueiro** [comment]
Thank you man. Happy to heard that :)

Currently you can't do that. First of all, your theme must be compatible with css class that highlight.js plugin use. The theme is strongly integrated in Tranquilpeak, so you can't switch to an another highlight.js theme. But you gave me the idea to ease the switch by simply add theme css file.

**Comment by LaureKamalandua** [comment]
+1, I'd vouch for this since the standard  highlight.js is not that appealing.

**Comment by LouisBarranqueiro** [comment]
this is not the default theme of highlight.js, it's a custom theme that I created, inspired by github syntax coloration :D

**Comment by LouisBarranqueiro** [comment]
you can change font size easily in `_css/utils/_variable.scss` file. 
About the dark theme, I don't have enough time for the moment to do that, but why not you? :)

**Comment by LaureKamalandua** [comment]
If I wouldn't have the problem of the hexo server taking 20 seconds to startup, I would have already made some tweaks. It really prevents me from doing anything creative with this theme.

**Comment by LouisBarranqueiro** [comment]
I'm very disappointed about what happens to you. come on gitter, I wanna test something to help you :)
