### ISSUE TITLE
Can not show the layout

### ISSUE THREAD

**Issue by yuanchenhao** [LouisBarranqueiro/hexo-theme-tranquilpeak#221]
> I placed the theme folder into theme and modify the config file then enter debug mode but the webpage just shows plain words like this no layout at all but when I switched to other theme they all works.How to fix it?

Steven YUAN's blog

首頁
分類
標籤
所有文章
搜尋
關於
Atom
Hello World

Feb 21, 2016
Welcome to Hexo! This is your very first post. Check documentation for more info. If you get any problems when using Hexo, you can find the answer in troubleshooting or you can ask me on GitHub.

Quick Start

Create a new post

1
$ hexo new "My New Post"
More info: Writing

Run server

1
$ hexo server

**Comment by LouisBarranqueiro** [comment]
Hi man. Please read documentation, I write it for that :D You downloaded the source so you have to build the theme to use it. Read developer documentation to know how to do that. Or download the production version already built : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/download/v1.6.2/hexo-theme-tranquilpeak-built-for-production-1.6.2.zip

**Comment by yuanchenhao** [comment]
Thx.I did use the production version yesterday but the problem was actually due to the network LOL.Thanks for your great work!!

**Comment by LouisBarranqueiro** [comment]
Good news. Thank you man :)
