### ISSUE TITLE
The cover border is not fully filled by the image

### ISSUE THREAD

**Issue by sshuair** [LouisBarranqueiro/hexo-theme-tranquilpeak#222]
it looks not very well. I hope you could spare some time to fix it

![qq 20160222212313](https://cloud.githubusercontent.com/assets/5787131/13219495/592fa312-d9ab-11e5-9d1d-d77cb53a3d86.jpg)

**Comment by LouisBarranqueiro** [comment]
Hey man! got it :)

**Comment by LouisBarranqueiro** [comment]
I also recommend you to hide these bars if you can do it on Windows. :)
