### ISSUE TITLE
grunt tasks messes up hexo server performance 

### ISSUE THREAD

**Issue by LaureKamalandua** [LouisBarranqueiro/hexo-theme-tranquilpeak#223]
When running the grunt watch task as follows:
`..\tranquilpeak> grunt watch`
The changed files are properly labeled as modified and compiled 
```
Running "watch" task
Waiting...
>> File "source\_css\layout\_about.scss" changed.
Running "sass:dev" (sass) task
Running "concat:devJs" (concat) task
File source/assets/js/tranquilpeak.js created.
Running "sync:dev" (sync) task
Done, without errors.
Completed in 2.286s at Tue Feb 23 2016 10:44:21 GMT+0100 (Romance Standard Time) - Waiting...
```
Which can also be confirmed in my IDE that the compilation was successful: 

![revision](https://cloud.githubusercontent.com/assets/12623827/13247923/314e6330-da1c-11e5-91ec-34ec2b9d413b.png)

After terminating the batch job in the console using CTRL + C and restarting the hexo server the hexo server becomes unresponsive (takes 20 seconds to start instead of 2) and the same occurs when terminating the job of the server:

```
INFO  Farewell
INFO  Bye!
INFO  Bye!
```

Changes in styling are not visible either. When running the hexo clean command to clear the database, this does not resolve the problem. I would appreciate some more insight.

**Comment by LouisBarranqueiro** [comment]
Hey :) Why do you restart the server after changes? It's not necessary.

**Comment by LaureKamalandua** [comment]
Because I don't keep the server open 24/7 when the process runs in the shell, since certain files aren't updated either way without a restart. You advise to run the hexo server and grunt task along? I'll have a look into that then.

**Comment by LouisBarranqueiro** [comment]
yeah, run `hexo s` and `grunt default`

**Comment by LaureKamalandua** [comment]
I'll set up a test and let you know. Thanks.

**Comment by LouisBarranqueiro** [comment]
about the 2 minutes waiting when you are launching your server with `hexo s`, it is because you deleted the database `db.json` and the site just before with `hexo clean` and hexo have to generate it again

**Comment by LaureKamalandua** [comment]
Nothing changes the performance.

**Comment by LouisBarranqueiro** [comment]
What do you means by performances? Is it working? Does CSS is updated?

**Comment by LaureKamalandua** [comment]
Node version 4.2.6. Created a clean express project and installed the theme. Dependencies, bower and grunt installed according to procedure. This is the first error I run into: 
![2016-02-24 16_54_32-start](https://cloud.githubusercontent.com/assets/12623827/13291526/633132f4-db18-11e5-821a-3c00899e26ed.png)
I'll check about compatibility node-sass and node 4.2.6.

**Comment by LouisBarranqueiro** [comment]
There is a lot of errors: node-sass not found, sass:dev task not found. This is clearly not normal. Which hexo version do you use? Add your `package.json` please. When you say "clean express project", express means fast, not `express` npm module?

**Comment by LaureKamalandua** [comment]
../blog/

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1"
  },
  "dependencies": {
    "hexo": "^3.1.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-renderer-marked": "^0.2.9",
    "hexo-server": "^0.1.3"
  }
}

/test/

**Comment by LouisBarranqueiro** [comment]
why do you use `express since` `hexo-server` serve static files?

**Comment by LaureKamalandua** [comment]
because the blog is a separate app and I'm hosting another at root, which is unrelated to the blog.

**Comment by LouisBarranqueiro** [comment]
yeha, but when you dev, if you wanna reload feature to update pages, only `hexo-server` do this job.

**Comment by LouisBarranqueiro** [comment]
Did you follow each step of developer docs to starting coding? It hard to debug your problem because i don't know your environment. Could you try to start form scratch with `hexo new blog`, run `npm install`, pick the tranquilpeak theme and follow the developer docs to install all dependencies and launch grunt tasks?

**Comment by LaureKamalandua** [comment]
Update issues were due to the bower dependency, so that is solved.
The following are still question marks:

1. styling updates do not happen dynamically, although the hexo server is running in dynamic mode. Manual restarts are needed.
2. starting up the server still takes 20 seconds opposed to the normal 2 seconds before the theme is build and grunt default has been ran. Even after building, not making a change and starting up the server this timing remains equal.

**Comment by LouisBarranqueiro** [comment]
It's hard to know what can cause that, it can be so many things. If it works before the `watch` task so it seems to come from this task, but it only watchs 4 folders (40 files). About the Hexo server, it is very guzzler and the new version may be more efficient. I think your computer is enough powerful to handle that. What's your computer configuration?

**Comment by LaureKamalandua** [comment]
Not due to my computer. An MSI GS70 can handle these types of calculations :) I'll keep an eye out on the hexo updates. Thanks.
