### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined on Mac

### ISSUE THREAD

**Issue by Mombuyish** [LouisBarranqueiro/hexo-theme-tranquilpeak#224]
I am updating my mac early and I get this errors.
When I use windows compile it does not have any errors. 
```
ERROR Process failed: source/_css/layout/_about.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/view.js:104:22)
....
```

**Comment by LouisBarranqueiro** [comment]
hey man. when does this happen?

**Comment by Mombuyish** [comment]
When I use `hexo generate`, it will get this errors.
I try use 'next' or others theme does not have any errors, but it get errors on tranquilpeak.

**Comment by LouisBarranqueiro** [comment]
did you try to remove theme dependencies and blog dependencies and try again?

**Comment by Mombuyish** [comment]
yes, I remove hexo node modules and reinstall it, same as.
And I create new project and put  tranquilpeak into the project, but I get same errors.

**Comment by LouisBarranqueiro** [comment]
add hexo version OS version, tranquilpeak version, node version, npm version, i'm gonna try with your setup

**Comment by Mombuyish** [comment]
OS: OS X EI Capitan 10.11.3 (latest)
npm: 3.8.0 
hexo: 3.2.0
hexo-cli: 1.0.1
node: 5.7.0
tranquilpeak: 1.6.2

**Comment by Mombuyish** [comment]
And I found many same errors on thus files.
ERROR Process failed: source/_css/layout/_about.scss
ERROR Process failed: source/_css/layout/_blog.scss
ERROR Process failed: source/_css/layout/_bottom-bar.scss
ERROR Process failed: source/_css/layout/_cover.scss
ERROR Process failed: source/_css/layout/_footer.scss
ERROR Process failed: source/_css/layout/_header.scss
ERROR Process failed: source/_css/layout/_main.scss
ERROR Process failed: source/_css/layout/_sidebar.scss

```
TypeError: Cannot read property 'compile' of undefined
    at View._precompile (/Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/view.js:104:22)
    at View (/Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/index.js:71:20)
    at /Applications/MAMP/htdocs/my.github.io/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:424:57)
    at Promise._settlePromiseFromHandler (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (/Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/promise.js:629:18)
    at /Applications/MAMP/htdocs/my.github.io/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Applications/MAMP/htdocs/my.github.io/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

**Comment by shiaue** [comment]
I have the same problem

"
ERROR Process failed: source/_css/layout/_blog.scss
ERROR Process failed: source/_css/layout/_bottom-bar.scss
ERROR Process failed: source/_css/layout/_about.scss
ERROR Process failed: source/_css/layout/_cover.scss
ERROR Process failed: source/_css/layout/_footer.scss
ERROR Process failed: source/_css/layout/_header.scss
ERROR Process failed: source/_css/layout/_main.scss
"
Running on OS X Yosemite 10.10.3
and Hexo -version:

hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 14.3.0 darwin x64
http_parser: 2.6.0
node: 5.4.1
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e

**Comment by LouisBarranqueiro** [comment]
ok, you got the new hexo version. This one is trying to process scss files as view (layout) that's why there are errors. There is an variable to skip folder, i'm on it. It also a good new because, previous versions processed all files, `node_modules` included and Tranquilpeak got a lot of modules and this process take a lot of time, now it's gonna be faster and more efficient

**Comment by Mombuyish** [comment]
ok, thank you.
btw, how to downgrade hexo? I try to edit version to 3.1.1 on package.json  and update it, but it will be 3.2.0.
I think I wanna see Tranquilpeak for new version ;-)

**Comment by joelrdz** [comment]
@Mombuyish , make sure that you are updating the dependency.
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.1.1" <<<<<<<<<NOT THIS ONE, THIS IS IRRELEVANT
  },
  "dependencies": {
    "hexo": "3.1.1",      <<<<<<<< BUT THIS ONE
.....

**Comment by Mombuyish** [comment]
@joelrdz thank you. I try it.

**Comment by joelrdz** [comment]
@Mombuyish Don't forget to npm install

**Comment by LouisBarranqueiro** [comment]
I opened an issue on Hexo repository : https://github.com/hexojs/hexo/issues/1793

**Comment by wykydtronik** [comment]
I'm getting the same error.

`hexo: 3.2.0
hexo-cli: 1.0.1
os: Windows_NT 10.0.10240 win32 x64
http_parser: 2.6.2
node: 5.8.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2g`

`{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.1.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-renderer-marked": "^0.2.9",
    "hexo-server": "^0.1.3"
  }
}`

**Comment by wykydtronik** [comment]
I think I figured it out, remove the carrot

"dependencies": {
"hexo": "3.1.1",

**Comment by tparnell8** [comment]
@wykydtronik removing the carrot just pins you to 3.1.1 and does not fix the actual issue that occurs in 3.2.0

**Comment by LouisBarranqueiro** [comment]
As I said below : 
> If you wanna fix this temporarily, downgrade to version 3.1.1

The problem come from the new Hexo version that doesn't ignore this folder, an issue is already opened here : https://github.com/hexojs/hexo/issues/1793

**Comment by harmon25** [comment]
Just starting a hexo blog using tranquilpeak.
Getting the same error on a debian system with the latest version of Hexo.

Would rather not use 3.1.1 in case there are other breaking changes I am unaware of...

Everything seems to be working despite the errors, can I just ignore them for now and hope the next Hexo release patches this issue?

**Comment by LouisBarranqueiro** [comment]
If the blog is correctly generated, yes, you can ignore them, otherwise downgrade to 3.1.1.

**Comment by kaedea** [comment]
Exactly, as for me, I have to uninstall hexo and install it again by the following.

- npm uninstall hexo
- npm install hexo@3.1.1 --save
- And then, rebuild the folder by hexo init and npm install

**Comment by zyzyz** [comment]
I seem to have found a workaround without downgrading hexo.

According to [this comment](https://github.com/hexojs/hexo/issues/1855#issuecomment-208012712),  change ```source/_css/layout``` into ```source/_css/layouts``` and modify related lines in ```source/_css/tranquilpeak.scss```

```
@import
    'layouts/about',
    'layouts/blog',
    'layouts/bottom-bar',
    'layouts/cover',
    'layouts/footer',
    'layouts/header',
    'layouts/main',
    'layouts/sidebar';
```
and the errors gone.

**Comment by flexgrip** [comment]
Confirmed that it fixed it for me. Thanks zyzyz!

Are you going to rename this folder in the repo Louis? Otherwise I can't track your changes.

**Comment by leesei** [comment]
@zyzyz Thanks for spreading the words for the workaround.

**Comment by LouisBarranqueiro** [comment]
@flexgrip yeha, I renamed the folder. I'm gonna release a new version in some days. I'm waiting the last PRs :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released :) `.layout`file error must be solved by Hexo repo
