### ISSUE TITLE
bottom bar and post footer both visible in 1.6.2

### ISSUE THREAD

**Issue by darkshell** [LouisBarranqueiro/hexo-theme-tranquilpeak#228]
when scrolling up from the bottom of  a post and with the post footer still visible, the post bottom bar is also visible, i.e. there will be two bars existing.

**Comment by LouisBarranqueiro** [comment]
Hey man.I think Did you customize the theme or is it an original version? Could you add a screen, please?

**Comment by darkshell** [comment]
![screenshot from 2016-03-03 00-15-45](https://cloud.githubusercontent.com/assets/1749175/13466559/646bf4d4-e0d5-11e5-9fcf-38cfef377549.png)

No. I'm using the original version, with _config.yml modified.

**Comment by LouisBarranqueiro** [comment]
it bug on all post page or only one in particular? Can I see it live?

**Comment by darkshell** [comment]
yeah, it bugs on all posts longer than the screen. and my site is https://amito.me,  which  is  using your theme now.

**Comment by LouisBarranqueiro** [comment]
didn't notice this behavior before that . Got it. fix on the way :)
