### ISSUE TITLE
How to set jsfiddle size ?

### ISSUE THREAD

**Issue by iPonyo** [LouisBarranqueiro/hexo-theme-tranquilpeak#229]
HI ! I want to set jsfiddle size, but it did't work. Please help me ! Thanks !
{% jsfiddle ccWP7 100 600 %}

**Comment by LouisBarranqueiro** [comment]
Which version of Hexo do you have?

**Comment by iPonyo** [comment]
hexo: 3.1.1

**Comment by LouisBarranqueiro** [comment]
This feature is available in Hexo 3.2.0. You should post this issue on Hexo repo since jsfiddle tag is handled by Hexo. And I think you have to define a unit like `px`, `%`.

**Comment by iPonyo** [comment]
OK ! Thanks !

**Comment by LouisBarranqueiro** [comment]
Is it working? :)

**Comment by iPonyo** [comment]
Not yet ! I'm going to search. Thanks !

**Comment by iPonyo** [comment]
Done ! The syntax should be: 
{% jsfiddle nr4jk7Lh html,css,result dark 100 200 %}

Thanks !
