### ISSUE TITLE
buttons of post footer not in one line under little screen like iphone 5s

### ISSUE THREAD

**Issue by darkshell** [LouisBarranqueiro/hexo-theme-tranquilpeak#236]
### Configuration

 - **Operating system with version** :  iPhone 5s, iOS 9.2
 - **Node version** :  4.3.2
 - **Hexo version** :   3.1.1
 - **Hexo-cli version** :  0.1.9
 - **Tranquilpeak version** :  1.7.0
 

### Actual behavior
![img_2018](https://cloud.githubusercontent.com/assets/1749175/13735525/af518108-e9e5-11e5-8410-d67cdaffb63f.PNG)
![screenshot from 2016-03-14 12-57-12](https://cloud.githubusercontent.com/assets/1749175/13735548/f95f0a04-e9e5-11e5-9122-8700eb2d457b.png)
![screenshot from 2016-03-14 12-54-47](https://cloud.githubusercontent.com/assets/1749175/13735550/fa334ecc-e9e5-11e5-8972-266def637e8e.png)

### Expected behavior
All buttons should be in one line.

### Steps to reproduce the behavior
Just Open a page supported by hexo and tranquilpeak on a iPhone 5s

**Comment by LouisBarranqueiro** [comment]
Hey man, yeah, I checked that. It doesn't bug with Safari dev tools (Iphone 5) but on a real Iphone, it does. I'm on :)

**Comment by darkshell** [comment]
It will bug too when resizing  a desktop version chrome to a small size..

**Comment by h404bi** [comment]
chrome dev tool cannot reproduce this issue on the demo site, but on op's site.

**Comment by darkshell** [comment]
@h404bi You need to resize chrome little by little. Only at some size the bug would show up.

**Comment by h404bi** [comment]
nope, I just use chrome's device mode.

|Demo | Op's|
|--------- | ---------|
|![a](https://cloud.githubusercontent.com/assets/5764917/13744881/d3e66908-ea25-11e5-9e1b-aa8c6d1d92ab.PNG) | ![b](https://cloud.githubusercontent.com/assets/5764917/13744886/da300706-ea25-11e5-9b0d-54686aac568a.PNG)|

strange.

**Comment by darkshell** [comment]
@h404bi  Yeah. I just forgot I changed the width. I changed the max-width from 750px to 80%.

**Comment by h404bi** [comment]
I tested it on my 4 inch' mobile phone, no problem on the demo. Maybe you made something changed on your instance. I remember this issue has been resolved previously.

**Comment by LouisBarranqueiro** [comment]
Yeah, I remember this issue : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/62  but I just checked and this issue appears on an iPhone 5s.

**Comment by LouisBarranqueiro** [comment]
it bug because you reduce max-width value.

**Comment by darkshell** [comment]
yeah， I've noticed it…
