### ISSUE TITLE
[Feature Request] Clickable Thumbnail

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#237]
Hey! I think it would be cool if when you click the thumbnail image on the main page, it would bring you to the actual blog post.

Let me know if you need more info.

**Comment by LouisBarranqueiro** [comment]
Hey man, yeah good idea.

**Comment by LouisBarranqueiro** [comment]
Sorry @fletchto99, I was really busy. It's done. New version available in some days :)

**Comment by fletchto99** [comment]
Great no worries @LouisBarranqueiro! I've been really busy too otherwise I would have looked into this. Thanks!

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released :)
