### ISSUE TITLE
[question] Showing all post instead have continue to read

### ISSUE THREAD

**Issue by masterviana** [LouisBarranqueiro/hexo-theme-tranquilpeak#239]
hey, first thanks for your theme, i've try to configurate as you have on your sample, my post all showing full content on the main screen i want to show a bit of post and have the countinue to read label. 

I've setup on _config.yml this properties 

```javascript
read_more_message: true
go_to_message : true
```

Thant i found on documentation but yet I saw full post on the post list. 

Thanks for your support

**Comment by LouisBarranqueiro** [comment]
Hey man, thanks you, I appreciate :) You have to put `<!-- more -->` or `<!-- excerpt -->` tag in your post to cut the post on index page and define the excerpt. Read [define post excerpt](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#define-post-excerpt) for more information

**Comment by masterviana** [comment]
Hey man, thanks for your help this working for me.

**Comment by LouisBarranqueiro** [comment]
You're welcome.  :)
