### ISSUE TITLE
[question] Showing top post image on bottom 

### ISSUE THREAD

**Issue by masterviana** [LouisBarranqueiro/hexo-theme-tranquilpeak#240]
I've try to configure my template as you have on the sample.

That means have the top post the image filled center and all other posts showing thumbnail on left.

I'm using this on top post 
```javascript
thumbnailImagePosition  : bottom
```

and using thumbnail_image_position: left on _config.yml that is what I need to show top post as you've on sample.

**Comment by LouisBarranqueiro** [comment]
Hey man, yeah. It doesn't work like this?

**Comment by LouisBarranqueiro** [comment]
Is it fixed?

**Comment by LouisBarranqueiro** [comment]
sorry @masterviana , I just remarked this bug by doing other stuff. I'm gonna fix it.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released and fix this issue :)

**Comment by showzeng** [comment]
Hey bro, this bug show in production-1.9.1 again!

**Comment by sunilpatro1985** [comment]
@LouisBarranqueiro bro, I am having same issue with 1.10 version as well, 

My Theme _config.yml setting

```
sidebar_behavior: 2
thumbnail_image_position: right
auto_thumbnail_image: true
```
Still thumbnail shows bottom of post title - [sunilpatro1985.github.io](url)

Any suggestions/workaround on how to display thumbnail right or left? 
Thanks in advance.
