### ISSUE TITLE
Front-matter settings problems

### ISSUE THREAD

**Issue by princessyv** [LouisBarranqueiro/hexo-theme-tranquilpeak#241]
### Configuration

 - **Operating system with version** :  Ubuntu 14.04
 - **Node version** : 4.4.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** : 1.7
 

### Actual behavior
The thumbnailImagePosition, metaAlignment and autoThumbnailImage didn't work.

Thank you for your guide.

**Comment by princessyv** [comment]
because there is no excerpt in the post

**Comment by LouisBarranqueiro** [comment]
Hey man, is that ok?
