### ISSUE TITLE
How can i let code block word wrap?

### ISSUE THREAD

**Issue by CairoLee** [LouisBarranqueiro/hexo-theme-tranquilpeak#246]
Hi @laurentkempe 

How can i let code block word wrap? i don't like the horizontal scroll...

![qq20160422-0](https://cloud.githubusercontent.com/assets/4458917/14735070/5d6e41f2-08a1-11e6-9775-f5686b157703.png)

### Configuration

 - **Operating system with version** : OS X EI Capitan 10.11.4
 - **Node version** : v4.3.1
 - **Hexo version** : 3.1.1
 - **Hexo-cli version** : 0.1.9
 - **Tranquilpeak version** : 1.7.0

**Comment by LouisBarranqueiro** [comment]
Hey man, you can't do that.

If you don't wanna see the scroll bar :  -> System Preferences -> Général -> Display scroll bar : when scrolling

**Comment by LouisBarranqueiro** [comment]
Is that ok ?
