### ISSUE TITLE
How to tell the gallery that the images are portrait?

### ISSUE THREAD

**Issue by davidascher** [LouisBarranqueiro/hexo-theme-tranquilpeak#249]
### Configuration

 - **Operating system with version** : 
 - **Node version** : 4.4.1
 - **Hexo version** : 3.1.1
 - **Hexo-cli version** : (dunno)
 - **Tranquilpeak version** : 1.7.1
 

### Actual behavior

When using the gallery feature, the first image is stretched to fit the width of the img tag. This is done horizontally only, so it distorts the image.

### Expected behavior

Scaling is in both directions.

### Steps to reproduce the behavior

Add a post with a gallery with an image that is < 400 px wide.

**Comment by LouisBarranqueiro** [comment]
Could you add a screen? please

**Comment by davidascher** [comment]
Sure thing.

Here's the gallery view:

<img width="846" alt="screenshot 2016-04-30 18 08 32" src="https://cloud.githubusercontent.com/assets/51278/14939504/a695784c-0efe-11e6-82a9-4eb91f5a5e08.png">


Here's the correctly sized detail view:

<img width="813" alt="screenshot 2016-04-30 18 08 44" src="https://cloud.githubusercontent.com/assets/51278/14939505/aa1b4762-0efe-11e6-90a7-bf7de90c4a9f.png">

Note that the image being inserted is 500px wide.

**Comment by LouisBarranqueiro** [comment]
oh, it's the default behavior, to fill all space. Otherwise, there is a blank on side... Of course, you can update this part of code, that resize images (`source/_js/image-gallery.js`) :
```js
this.$images.each(function() {
        $image = $(this);
        photoBoxWidth = $image.parent().parent().width();
        photoBoxHeight = $image.parent().parent().innerHeight();
        imageWidth = $image.width();
        imageHeight = $image.height();

        // Checks if image height is smaller than his box
        if (imageHeight < photoBoxHeight) {
          imageRatio = (imageWidth / imageHeight);
          // Resize image with the box height
          $image.css({
            height: photoBoxHeight,
            width: (photoBoxHeight * imageRatio)
          });
          // Center image in his box
          $image.parent().css({
            left: '-' + (((photoBoxHeight * imageRatio) / 2) - (photoBoxWidth / 2)) + 'px'
          });
        }

        // Update new values of height and width
        imageWidth = $image.width();
        imageHeight = $image.height();

        // Checks if image width is smaller than his box
        if (imageWidth < photoBoxWidth) {
          imageRatio = (imageHeight / photoBoxWidth);

          $image.css({
            width: photoBoxWidth,
            height: (photoBoxWidth * imageRatio)
          });
          // Center image in his box
          $image.parent().css({
            top: '-' + (((imageHeight) / 2) - (photoBoxHeight / 2)) + 'px'
          });
        }

        // Checks if image height is larger than his box
        if (imageHeight > photoBoxHeight) {
          // Center image in his box
          $image.parent().css({
            top: '-' + (((imageHeight) / 2) - (photoBoxHeight / 2)) + 'px'
          });
        }
      });
```

**Comment by davidascher** [comment]
Thanks @LouisBarranqueiro for the pointer.  I'll look at that code, because even though it has lots of mentions of aspect ratio, something is not right (the aspect ratio should mean the images aren't squished, only zoomed in).

**Comment by LouisBarranqueiro** [comment]
you are right @davidascher . PR on **dev** branch please :)
