### ISSUE TITLE
all-tags, archive and search links in sidebar are broken

### ISSUE THREAD

**Issue by davidascher** [LouisBarranqueiro/hexo-theme-tranquilpeak#250]
### Configuration

 - **Operating system with version** : osx 10.11.4
 - **Node version** : 4.4.1
 - **Hexo version** : 3.1.1
 - **Hexo-cli version** : dunno
 - **Tranquilpeak version** : 1.7.1
 

### Actual behavior

Links in sidebar to `/all-tags` and `#search` lead to a 404 and a non-searching page respectively.

### Expected behavior

Some tag navigation, archive navigation and search capability.

### Steps to reproduce the behavior

I get that search requires swiftype, but the others should work (but I can't find references to those routes in the code).  Is it possible you forgot to `git add all-tags.ejs`, `archives` and `all-categories.ejs`?

**Comment by LouisBarranqueiro** [comment]
Hey man, Did you [enable these pages](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-pages)?

**Comment by davidascher** [comment]
😳 

oops. thanks!
