### ISSUE TITLE
disabling thumbnails in fancybox gallery on a landscape mobile phone display

### ISSUE THREAD

**Issue by davidascher** [LouisBarranqueiro/hexo-theme-tranquilpeak#251]
This is a lovely theme, I'm very grateful for it.

The only thing I'm finding a bit frustrating is that in landscape mode on a phone, the images are way too small.  My ideal would be to, in a landcape phone config, not have the thumbnails and make the photos full screen (with swiping would be lovely).

here's an example:

![image](https://cloud.githubusercontent.com/assets/51278/14939458/c61e3188-0efc-11e6-812b-e794e0bf1563.png)

**Comment by LouisBarranqueiro** [comment]
Hey man, that a good idea. Remove the thumbnail images on phone is quick and easy. about the swipe movement, it requires more time. Add button on the right and left of the picture should be good for the moment. but PR are welcome :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released :) thumbs are hidden on small screens and navigations arrows displayed.

**Comment by jrbenito** [comment]
Nice work man!

**Comment by LouisBarranqueiro** [comment]
:)

**Comment by LouisBarranqueiro** [comment]
Can we close it  @davidascher ?
