### ISSUE TITLE
[Question] CSS and Javascript are note being generated nor served

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#252]
Hexo is not generating styles and js scripts necessary for this theme. Landscape theme works. My setup is presented below.

What am I missing?

### Configuration

 hexo: 3.1.1
os: Linux 3.17.0-rc4-eudyptula-00204-g8381e57-dirty linux x64
http_parser: 2.5.2
node: 4.4.3
v8: 4.5.103.35
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2g
node: v4.4.3
tranquilpeak: v1.7.1
 
### Actual behavior
$ hexo generate
INFO  Files loaded in 11 s
INFO  Generated: 2016/05/hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2016/index.html
INFO  Generated: archives/2016/05/index.html
INFO  Generated: atom.xml
INFO  Generated: index.html
INFO  6 files generated in 133 ms

### Expected behavior
Hexo shall generate any css and js necessary to the site
Site is displayed with no style
If switch theme to landscape, site is ok.

**Comment by LouisBarranqueiro** [comment]
Hey man, I bet you downloaded the source so you have to build the theme to use it. Otherwise, download the built for production version. Read README and docs, everything is explained :)

**Comment by jrbenito** [comment]
Hi Louis

Thanks for your help. You are right , somwthibg went wrong whike building the theme and I missed. Tries with pre built package and it works. I will repeat experiente with source and look for what i did wrong.

Thanks agaain and sorry for this dumb question.

**Comment by LouisBarranqueiro** [comment]
no problem man, check [developer documentation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#requirements) to know how to install requirements and build the theme. :)

**Comment by LouisBarranqueiro** [comment]
no problem man, check [developer documentation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#requirements) to know how to install requirements and build the theme. Thank you for using this theme :)
