### ISSUE TITLE
Link text was set to French "Continuer" after doing "hexo generate"

### ISSUE THREAD

**Issue by sktoozaki** [LouisBarranqueiro/hexo-theme-tranquilpeak#254]
Hi Louis,

I have a little problem after doing "hero generate" command with the configuration below:

 - **Operating system with version** : OS X EI Capitan 10.11.1
 - **Node version** : 5.8.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** : 1.7.0
 
the link with text "Continue Reading" turns into French "Continuer" like this:

<img width="794" alt="2016-05-10 10 27 38" src="https://cloud.githubusercontent.com/assets/10172088/15150832/6d37880a-1701-11e6-8d2c-fdca99d0008b.png">

There is a workaround: do "hero clean" before generate. I just want to know is there any better way to solve this.

Thank you

**Comment by LouisBarranqueiro** [comment]
Did you set the right language code in your main `_config.yml` file? Each time your run `hexo generate`, it generate the blog in french?

**Comment by LouisBarranqueiro** [comment]
Hey man, 

Did you set the right language code in your main `_config.yml` file? Each time your run `hexo generate`, it generate the blog in french?

**Comment by sktoozaki** [comment]
Thanks.That's exactly the cause.

In Hexo default theme Landscape Chinese language setting file is zh-CN.yml, and that in Tranquilpeak is zh-cn.yml,different in capitalisation.
