### ISSUE TITLE
*Free* search feature

### ISSUE THREAD

**Issue by kousha-icracked** [LouisBarranqueiro/hexo-theme-tranquilpeak#256]
I know that we can use `SwiftType` for search feature. But it costs $250/month! Is there a free alternative?

**Comment by LouisBarranqueiro** [comment]
Heyn man, 

AHAHAH, 250$ :D  Didn't notice that they have updated their pricing plans. :D When I integrated Swiftype to the project, there was a free plan. [Algolia](https://www.algolia.com/pricing) seems to do the same thing, i'm gonna work on it to check if I can integrate it. Thank you :)

**Comment by kakawait** [comment]
When I search an alternative to implement inside the theme fork I found Algolia promising. But you must generate your index by yourself.

There are also _easy way_: [Google CSE](https://cse.google.com/cse/), [DuckDuckGo search box](https://duckduckgo.com/search_box) or [Yandex search](https://site.yandex.ru/?lang=en) but hard to customize/style.

Or homemade by using [lunrjs](http://lunrjs.com/) and creating index during build phase (using `Grunt`?)

**Comment by LouisBarranqueiro** [comment]
Hey man, thank you for this alternative. I checked them and I agree with your remarks. Algolia seems to be the best alternative : simple and fast to implement. Algolia is working with many open source projects to increase their visibility so yeah I think that they will always give a free plan.

**Comment by prajaybasu** [comment]
Any progress/update on this ?

**Comment by LouisBarranqueiro** [comment]
@prajaybasu  I'm gonna work on it today, maybe a release tomorrow or in some days

**Comment by LouisBarranqueiro** [comment]
I implemented the NPM module to index post on Algolia : [hexo-algoliasearch](https://github.com/LouisBarranqueiro/hexo-algoliasearch). For the moment, the plugin only clear the idnex and re-import all posts. Later, I will be better to only sync modified posts. I also implement the necessary on the theme to search and display results, it need some css yet and it will be good :)

**Comment by LouisBarranqueiro** [comment]
- Open search modal by clicking on button or pressing `s` button (shortcut)
- Close it by clicking on overlay or pressing `ESC` button (shortcut)

check it live on **add-search-box** branch

![dicaswlzre](https://cloud.githubusercontent.com/assets/4705626/16591401/0b48481c-42dc-11e6-9edc-81af2fe0eece.gif)

**Comment by brenotx** [comment]
Hi, nice to know we are going to get this new release soon. I tried to implement a search on my page following this tutorial: http://jeffworkshop.com/2016/01/01/hexo-Local-Search/
but for some reason it doesn't work.

**Comment by LouisBarranqueiro** [comment]
[v1.9.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.0) is here - with a new search module working with Algolia Search API **[Read Tips before update](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.0)** :)
