### ISSUE TITLE
[Question] How to change the size of avatar in sidebar?

### ISSUE THREAD

**Issue by sktoozaki** [LouisBarranqueiro/hexo-theme-tranquilpeak#258]
Hi Louis,

 The size of avatar  in sidebar is a bit small, and I wonder if it could be changed in `source/_css/utils/mixins/_sidebar.scss`

I tried to modify the values of `width` and `height` here:
```
 .sidebar-profile {
	        .sidebar-profile-picture {
	            width:          30px;
	            height:         30px;
```

but it doesn't work.

### Configuration

 - **Operating system with version** : OS X EI Capitan 10.11.1
 - **Node version** : 5.8.0
 - **Hexo version** :  3.2.0
 - **Hexo-cli version** : 1.0.1
 - **Tranquilpeak version** : 1.7.0

**Comment by LouisBarranqueiro** [comment]
hey @sktoozaki , after that, you have to build the theme to see changes. read [dev doc](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#requirements) to install al the requirements and run `grunt build` or `grunt buildProd`

**Comment by sktoozaki** [comment]
Oops......Thank you!
