### ISSUE TITLE
HTML5 validation error: Attribute charset not allowed on element meta at this point

### ISSUE THREAD

**Issue by kyrylkov** [LouisBarranqueiro/hexo-theme-tranquilpeak#261]
### Configuration

 - **Operating system with version** : Windows 10.0.10586
 - **Node version** :  6.2.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** :  1.0.1
 - **Tranquilpeak version** :  1.7.1
 

### Actual behavior
HTML5 validator error

### Expected behavior
No error

### Steps to reproduce the behavior
Run https://html5.validator.nu/ on Hexo blog with `tranquilpeak` theme.

To fix, replace:

    <meta http-equiv="Content-Type" content="text/html" charset="UTF-8" >

with:

    <meta charset="utf-8">

**Comment by LouisBarranqueiro** [comment]
Hey @kyrylkov, yeah, you're right. Could you PR on dev branch, please?

**Comment by kyrylkov** [comment]
@LouisBarranqueiro  done
