### ISSUE TITLE
Url for the image is not correct

### ISSUE THREAD

**Issue by oliviafu** [LouisBarranqueiro/hexo-theme-tranquilpeak#264]
### Configuration

 - **Operating system with version** :  OSX EI Capitan
 - **Node version** : v4.4.4
 - **Hexo version** : 3.1.1
 - **Hexo-cli version** : 
 - **Tranquilpeak version** : hexo-theme-tranquilpeak-built-for-production-1.7.1
 

### Actual behavior
url generated is like "2016/05/28/期待六一儿童节/2016/05/28/期待六一儿童节//1.jpg"

### Expected behavior
expected 2016/05/28/期待六一儿童节/1.jpg

### Steps to reproduce the behavior

The content in my post

```
thumbnailImage: 0.jpg
thumbnailImagePosition: right
coverImage: 
gallery:
  - 0.jpg
  - 1.jpg
  - 2.jpg
  - 3.jpg
  - 4.jpg
  - 5.jpg
  - 6.jpg
```

**Comment by LouisBarranqueiro** [comment]
hey @oliviafu , 

Did you edit the theme or it's the original version?

**Comment by LouisBarranqueiro** [comment]
Ok, I identify 2 bugs. I'm gonna fix them. If don't wanna wait, replace these lines :  

in `scripts/helpers/resolve_asset_url.js` file, replace line 16 with
```
 else if (from.slice(-1) !== '/') {
```

in `layout/_partial/post/gallery.ejs` file, replace `page` variable with `post` at line 22 and 25.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released and fix this issue :)
