### ISSUE TITLE
why my home page list all the artical content ?

### ISSUE THREAD

**Issue by fantiq** [LouisBarranqueiro/hexo-theme-tranquilpeak#266]
### Configuration

node v5.3.0

npm 3.3.12

hexo 3.2.0

hexo-cli 1.0.1

tranquilpeak 1.6.2   (built-for-production)
 

### Actual behavior

when i use `hexo g`  i get a error
```
ERROR Process failed: source/_css/layout/_about.scss
TypeError: Cannot read property 'compile' of undefined
    at View._precompile 
    ...
```

### Expected behavior

so i delete all the files source/_* , only assets leaveled
it works

but my home page list display all the artical content  ...

**Comment by twirlfog** [comment]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224#issuecomment-219365465

**Comment by LouisBarranqueiro** [comment]
hey man, you asked the same question on hexo repository, and I gave you a workaround : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/224#issuecomment-219365465
