### ISSUE TITLE
Page performance and SEO

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#268]
### Configuration

 - **Operating system with version** : Linux Ubuntu (it is not important)
 - **Node version** : 4.4.3 (also doesn´t matter for this issue)
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 
 - **Tranquilpeak version** : 1.7.1 (production version)
 

### Actual behavior
There is a `Size tap targets appropriately` warning for a mobile version of [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Flouisbarranqueiro.github.io%2Fhexo-theme-tranquilpeak%2F&tab=mobile) tool. Actually there are two of them for the demo site as shown by the link above.

### Expected behavior
At best should have no errors nor warnings but this one (`Size tap targets appropriately`) can be easily fixed by add some padding to CSS.

### Steps to reproduce the behavior
Visit [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Flouisbarranqueiro.github.io%2Fhexo-theme-tranquilpeak%2F&tab=mobile) tool and check mobile version.

**Comment by LouisBarranqueiro** [comment]
hey @jrbenito, could you PR? :)

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro , sure, I send PR.

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro ,

I was wrong, it is not just padding. The top `<header id="header">` is actually over `<div id="main">`. Since this `<div>` has property `min-height: 100%`, the element `<header>` actually is "floating" over `<div>`.

The Google tool complain is because, teoreticaly, the tap area (click in a touch screen) of `<header>...<a href...>blog name</a>...</header>` is too near the tap area of `<div id="main">` (this element is able to scroll with touch swipe on a mobile phone). At least in Chrome for Android, this is not a problem since I can click on header link or scroll the article freely. Maybe Google tool is not able to see that way.

I don't see other way to solve this besides resize `<div>` on the fly, but this would make for annoying text re-arrangements. If you also don't see another way and since there is no problem at least for Chrome, we can flat this as "won't fix" and close.

Let me know your thoughts

**Comment by LouisBarranqueiro** [comment]
Yeah, this issue pointed by Google Tool is not very relevant in this case.
