### ISSUE TITLE
Performance issue #2

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#269]
### Configuration

 - **Operating system with version** : Linux Ubuntu (it is not important)
 - **Node version** : 4.4.3 (also doesn´t matter for this issue)
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 
 - **Tranquilpeak version** : 1.7.1 (production version)
 

### Actual behavior
There are `Optimize images` errors for mobile and desktop versions of [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Flouisbarranqueiro.github.io%2Fhexo-theme-tranquilpeak%2F&tab=mobile) tool. 

### Expected behavior
At best should have no errors nor warnings but this one (`Optimize images`) can be easily fixed by replacing cover.jpg by version suggested (optimezed) by Google´s tool itself. This will improve theme performance out of the box. Users still have to care their own image.

### Steps to reproduce the behavior
Visit [Google PageSpeed Insight](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Flouisbarranqueiro.github.io%2Fhexo-theme-tranquilpeak%2F&tab=mobile) tool and check..

**Comment by LouisBarranqueiro** [comment]
Hey @jrbenito, I'm waiting your PR :)

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro , sure, I send PR soon
