### ISSUE TITLE
HTML5 Validation

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#277]
### Configuration

 - **Operating system with version** : Ubuntu
 - **Node version** :  4.4.3
 - **Hexo version** :  3.2.0
 - **Hexo-cli version** : --
 - **Tranquilpeak version** : 1.8.0 (stock not modified)
 

### Actual behavior
HTML5 validator Error complains as follow:

Element `<p>` not allowed as child of element `<h5>` in this context. 

### Expected behavior
Ideally HTML5 validation shall have no errors.

### Steps to reproduce the behavior
This error is caused by file `layout/_partial/about.ejs` at line 22:

`<h5 id="about-card-bio"><%- markdown(__('author.bio')) %></h5>`

Markdown interpreter takes the `author.bio` text and wraps it with <p> tag. Obviously code above is wrapping it with `<h5>` tag.

To verify: https://validator.w3.org/nu/ and use theme demo site.

**Comment by jrbenito** [comment]
A possible solution would be remove markdown interpreter but this would break the ability to rich format bio.

Any other idea @LouisBarranqueiro?

**Comment by LouisBarranqueiro** [comment]
Hey @jrbenito, in this case, it not relevant to do something. The markdown feature is more important.

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro 

Let´s keep as this and close the issue.
