### ISSUE TITLE
ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js

### ISSUE THREAD

**Issue by FlowerHop** [LouisBarranqueiro/hexo-theme-tranquilpeak#280]
### Configuration

 - **Operating system with version** : Mac OS 10.10.5
 - **Node version** : v0.12.7
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : latest version
 

### Actual behavior
I just clone the repo in my themes directory, and I change name of the directory called **tranquilpeak**. I also modify the **_config.yml theme: tranquilpeak**). Then, I execute `hexo server`. My page just shows text. It seems that it can't access my themes. Console shows 

> this ERROR Script load failed: themes/tranquilpeak/scripts/tags/tabbed_codeblock.js
> /Users/caizongming/Flowerhop/Flowerhop.github.io/themes/tranquilpeak/node_modules/jsdom/lib/jsdom.js:3
> () => `jsdom 7.x onward only works on Node.js 4 or newer: https://github.com/t
>  ^
> SyntaxError: Unexpected token )
>     at exports.runInThisContext (vm.js:73:16)
>     at Module._compile (module.js:443:25)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Module.require (module.js:365:17)
>     at require (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/lib/hexo/index.js:213:21)
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/themes/tranquilpeak/scripts/tags/tabbed_codeblock.js:6:13
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/lib/hexo/index.js:229:12
>     at tryCatcher (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
>     at Promise._settlePromise (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
>     at Promise._settlePromise0 (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
>     at Promise._settlePromises (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
>     at Promise._fulfill (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
>     at Promise._resolveCallback (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:423:57)
>     at Promise._settlePromiseFromHandler (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:514:17)
>     at Promise._settlePromise (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
>     at Promise._settlePromise0 (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
>     at Promise._settlePromises (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
>     at Promise._fulfill (/Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:628:18)
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
>     at fs.js:334:14
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/nunjucks/node_modules/chokidar/node_modules/readdirp/node_modules/graceful-fs/graceful-fs.js:43:10
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
>     at /Users/caizongming/Flowerhop/Flowerhop.github.io/node_modules/hexo/node_modules/warehouse/node_modules/graceful-fs/graceful-fs.js:43:10
>     at /opt/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:43:10
>     at FSReqWrap.oncomplete (fs.js:95:15)

It's probably because the module uses the es6 syntax, and hexo doesn't support. But I am not sure, I'm a beginner, and I don't know what should I do next.

### Expected behavior
I expect that it can work without bugs, and shows the right themes.

**Comment by LouisBarranqueiro** [comment]
Hey @FlowerHop . Update Node version to v4 or higher and try again. I'm gonna update requirements version in the doc

**Comment by FlowerHop** [comment]
Thank you, @LouisBarranqueiro. It works. I like it very much.

**Comment by LouisBarranqueiro** [comment]
I'm gonna update the versions required. Thanks for using this theme :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.8.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.8.0) is released and I updated the required versions :)
