### ISSUE TITLE
Setup a continuous integration system for this project

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#281]
### Configuration
- **Operating system with version** : Ubuntu
- **Node version** : 4.4.3
- **Hexo version** : 3.2.0
- **Hexo-cli version** : 0
- **Tranquilpeak version** : 1.8.0 original

### Actual behavior
- No continuous integration (ci).

### Expected behavior
- We would benefit of continuous integration in many ways

@LouisBarranqueiro , we could have a ci setup for the theme. [Travis-ci](https://travis-ci.org) do it for free to all opensource projects hosted by Github. What do you think?

**Comment by LouisBarranqueiro** [comment]
What do you have in mind? because there are no tests to run and nothing to deploy.

**Comment by jrbenito** [comment]
Sorry for delay, I was out for the weekend.

I was thinking in test compilation errors and dependencies for start. At least we can guarantee the installation is working. Since travis-ci can run the install process in a variety of node versions we can use it to detect broken compatibility.

What do you think?

**Comment by LouisBarranqueiro** [comment]
Yeah, It can be an idea, but I currently don't have time to do that. And you?
a good start will be to generate a blog on different Node and Hexo configuration.

**Comment by willwade** [comment]
This may be useful: https://github.com/sazzer/blog/blob/master/.travis.yml (from https://sazzer.github.io/blog/2015/05/04/Deploying-Hexo-to-Github-Pages-with-Travis/)

**Comment by MeteoBoy4** [comment]
I agree with @jrbenito, I hope tranquilpeak can pass test and build on Travis CI, now if I do that, travis will complain about 
```bash
Error: cannot find module 'prompt' 
Error: cannot find module 'jquery' 
```
which are dependencies of tranquilpeak alone.

**Comment by LouisBarranqueiro** [comment]
@MeteoBoy4  You downloaded the source and not the built version ready for production, so you have to install dependencies to build your blog.

**Comment by LouisBarranqueiro** [comment]
We don't really need it for now, so let's close it
