### ISSUE TITLE
Custom css and js

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-theme-tranquilpeak#284]
Hello, Louis. I don't inderstand one fundamental thing(( How to inject a custom.js and custom.css to script.ejs and head.ejs. Will you explain it step by step, please?

**Comment by aerohub** [comment]
### Configuration

 - **Operating system with version** : Windows_NT 6.1.7601 win32 x64
 - **Node version** : 4.4.5
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : developers
 

### Actual behavior

I have input lines with custom css & js into pipeline.js and put the files to `source/assets/css` and `source/assets/js`. Then run `grunt build`
Neither custom style nor custom javascript files are injected to head.ejs and script.ejs

**Comment by LouisBarranqueiro** [comment]
Hey @aerohub, 

To inject javascript code : 

1. Create a new file in `source/_js/`
2. Build the theme with `npm prod` or `npm start` if you are in dev process.

To inject css code : 

1. Create a new file in `source/_css/`. it can be a css or scss file.
2. Import it in `source/_css/tranquilpeak.css` with  `@import `../relative/path/to/your/file.scss`.
2. Build the theme with `npm prod` (`alias `grunt buildProd`) or `npm start` (alias `grunt default`)
 
Sorry to reply late

**Comment by aerohub** [comment]
Thank you very much @LouisBarranqueiro Don't excuse, it's ok)

**Comment by LouisBarranqueiro** [comment]
you're welcome :)
