### ISSUE TITLE
New sidebar for extra large screens

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/hexo-theme-tranquilpeak#285]
Hey, I implemented the new sidebar. Any other suggestions or ideas on it?

![capture d ecran 2016-07-02 a 22 26 30](https://cloud.githubusercontent.com/assets/4705626/16542320/130f921a-40a4-11e6-902e-022452163b51.png)

@kaedea

**Comment by jrbenito** [comment]
Hi @LouisBarranqueiro ,

Is this on dev or other branch? Or even better, is there a demo? I want to see it in action.

Is it a new behavior for large screens or is there something else?

**Comment by kaedea** [comment]
GJ. This looks better than I expected.

**Comment by LouisBarranqueiro** [comment]
@kaedea =) I love it too. thanks for this suggestion!
@jrbenito , I pushed it on [add-new-sidebar-behavior](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/tree/add-new-sidebar-behavior)

**Comment by jrbenito** [comment]
@LouisBarranqueiro , will try it tonight if I can leave office early.

**Comment by LouisBarranqueiro** [comment]
[v1.9.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.0) is here - Thank you @kaedea for having proposed this feature :)

**Comment by jrbenito** [comment]
Just commenting to say: I love it!
