### ISSUE TITLE
Problem with code typeface.

### ISSUE THREAD

**Issue by brenohq** [LouisBarranqueiro/hexo-theme-tranquilpeak#286]
### Configuration

 - **Operating system with version** : Windows 10
 - **Node version** : 4.4.7
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.8.0
 
Hello, i need to change this uggly typeface on code blocks, but i don't have ideia about i need to do. It's my first experience with javascript frameworks, so I do not know much about how it all works, I'm still discovering.

**My post example:** https://brenohq.github.io/2016/07/03/hello-world/

I need to change that serifed font at the codes, thanks! Your template is awesome!

**Comment by LouisBarranqueiro** [comment]
Hey man,

1. Menlo font is not ugly for code blocks :D
2. Read this section of doc [user doc - quick and easy modifications](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#quick--easy-modifications)
3. This is the file you are looking : [source/_css/utils/_variables.scss](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/source/_css/utils/_variables.scss#L16)
4. Build the theme to see changes, read [this](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#prerequisites)

Thanks for using this theme :)

**Comment by LouisBarranqueiro** [comment]
Can we close this issue?

**Comment by Garee** [comment]
I think the issue here is that Menlo is the default font for code blocks but it's not installed by default on Windows operating systems. There should be a fallback monospace font e.g. Consolas for people who don't have Menlo installed.

**Comment by LouisBarranqueiro** [comment]
hey @Garee, you sure? Could you PR? :)

**Comment by Garee** [comment]
@LouisBarranqueiro Yeah I'm currently on a Windows 7 PC and the font looks awful because Menlo isn't installed. I'll submit a PR later tonight.

**Comment by LouisBarranqueiro** [comment]
cool. thank you 👍
