### ISSUE TITLE
ERROR Script load failed: themes/tranquilpeak/scripts/migrators/1.4.0.js Error: Cannot find module 'prompt'

### ISSUE THREAD

**Issue by Hearen** [LouisBarranqueiro/hexo-theme-tranquilpeak#287]
### Configuration
- **Operating system with version** : 
  - node: 6.2.0
  - hexo: 3.2.2
  - hexo-cli: 1.0.2
  - os: Darwin 15.5.0 darwin x64 
  - hexo-theme-tranquilpeak-built-for-production-1.8-2.1
    
    ### Actual behaviour

> Just follow the user guidance and rename the folder in themes, change the theme in _config.yml then run `hexo -v`

**Comment by LouisBarranqueiro** [comment]
Hey buddy,

Don't understand the version you use : 1.8-2.1?

**Comment by Hearen** [comment]
it's the directory I unzipped, it should be the latest version 1.8.1

**Comment by LouisBarranqueiro** [comment]
it's strange. I just re-tested with built version and everything is working fine. 
Option 1: Install all the stuff (`prompt` included`) run `npm install` in `blog/themes/tranquilpeak/` folder.
read this section for more information : [dev doc - installation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation)
Option 2: (try again :D)
CReate a new folder, run  `hexo init` in it and then re-download the theme, put the theme in the folder, etc...

**Comment by Hearen** [comment]
Thank you for your prompt reply, I've already made it in some other way around.

**Comment by LouisBarranqueiro** [comment]
Is it working?

**Comment by xsank** [comment]
@Hearen Hi,how do you fix this problem?
Here it is:
`ERROR Script load failed: themes\hexo-theme-tranquilpeak\scripts\migrators\1.4.0.js
Error: Cannot find module 'prompt'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (D:\code\mine\xsank\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\code\mine\xsank\themes\hexo-theme-tranquilpeak\scripts\migrators\1.4.0.js:7:16
    at D:\code\mine\xsank\themes\hexo-theme-tranquilpeak\scripts\migrators\1.4.0.js:233:3
    at D:\code\mine\xsank\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\code\mine\xsank\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\code\mine\xsank\node_modules\bluebird\js\releas
Error: Cannot find module 'jquery'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (D:\code\mine\xsank\node_modules\hexo\lib\hexo\index.js:213:21)
    at Object.done (D:\code\mine\xsank\themes\hexo-theme-tranquilpeak\scripts\tags\tabbed_codeblock.js:18:11)
    at D:\code\mine\xsank\node_modules\jsdom\lib\jsdom.js:271:18
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
`

**Comment by LouisBarranqueiro** [comment]
Hey @xsank, read my answer. just run `npm install` in theme folder

**Comment by Hearen** [comment]
Sorry, guys. I just used another `theme` Next.

**Comment by taroYxx** [comment]
@Hearen hi, I can't load resource like css image....but Other themes are ok.
![2017-02-25 4 17 34](https://cloud.githubusercontent.com/assets/14303767/23329562/0f43ad6e-fb76-11e6-80c0-30b75fc419c5.png)

**Comment by jrbenito** [comment]
@taroYxx ,

Did you build the theme? Maybe you download the developer code and not production.
