### ISSUE TITLE
Tags and Categories page aren't working out the box (new to hexo)

### ISSUE THREAD

**Issue by willwade** [LouisBarranqueiro/hexo-theme-tranquilpeak#288]
### Configuration

 - **Operating system with version** : Mac OSX 10.11.5
 - **Node version** : v4.2.2
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : original 
 

### Actual behaviour
http://localhost:4000/all-categories/ : Cannot GET /all-categories/
http://localhost:4000/all-tags/: Cannot GET /all-tags/

### Expected behavior
http://localhost:4000/all-categories/ : Categories page!
http://localhost:4000/all-tags/ : Tags page!

### Steps to reproduce the behaviour
git clone project
add one file in source/_posts/SomeTitle.md. with something like below. run hexo server. 

Am I missing a plugin maybe?

`---
title: SomeTitle
date: 2016-06-21 17:46:46
tags: 
- Injury
- Fight
- Shocking
---

## Hello`

**Comment by LouisBarranqueiro** [comment]
Hey @willwade,

Be careful, you download the source and not the build version ready for prod, so you have to install all requirements, dependencies, and build the theme. check this section for more information : [dev doc - installation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation)

About pages : read [user doc - enable pages](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-pages)

If you got a question, there are great chance that the answer is in README, user doc or dev doc :)

Thanks for using this theme :)

**Comment by willwade** [comment]
Sorry for not properly reading the manual! RTFM in future!

**Comment by LouisBarranqueiro** [comment]
np @willwade  :)
