### ISSUE TITLE
How to change the share item or hide it?

### ISSUE THREAD

**Issue by szpssky** [LouisBarranqueiro/hexo-theme-tranquilpeak#289]
Hi,
The default is Twitter,Facebook and Google+.How to change it or hide it?
You know some County cannot visit it.
![qq20160707-0 2x](https://cloud.githubusercontent.com/assets/5045936/16652797/87834c34-447f-11e6-9507-8dece0362f34.png)
Thanks,The theme is so cool:)

**Comment by jrbenito** [comment]
Hi @szpssky 

You can edit file  [share-options.ejs](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/post/share-options.ejs)

**Comment by szpssky** [comment]
@jrbenito 
thanks

**Comment by szpssky** [comment]
Hi @jrbenito
I was tried, but even if I delete this file,the share item always exist :(

**Comment by LouisBarranqueiro** [comment]
Hey @szpssky, Are you new to Hexo? Do you know how it works?

**Comment by szpssky** [comment]
@LouisBarranqueiro Hi，
yes，but now I think I might know how to solve this problem.
About share Item,I should edit [actions.ejs](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/post/actions.ejs)
You define this feature in the actions.ejs, Maybe the  share-options.ejs is unused.

**Comment by LouisBarranqueiro** [comment]
I just wanted to know to choose the way I explain this. You have to edit [actions.ejs](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/post/actions.ejs) and [share-options.ejs](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/post/share-options.ejs)
- **actions.ejs**  is used in the bottom bar
- **share-actions** is used in an hidden div which swipe from bottom on small screen when you click on share button.
![spax4yuuwa](https://cloud.githubusercontent.com/assets/4705626/16689672/5d43ef78-4524-11e6-87fc-c02fb565e07d.gif)

**Comment by szpssky** [comment]
oh,well.I see.I will edit the action.ejs and share-options.ejs.
Okey,Thank you for your help 👍
