### ISSUE TITLE
How to keep the header from hiding when the user scrolls down?

### ISSUE THREAD

**Issue by abelsu7** [LouisBarranqueiro/hexo-theme-tranquilpeak#293]
Hi~ 

I just wonder how to ***keep the header from hiding*** when the user scrolls down. 
When I scroll down the page using a mobile phone, sometimes it's really annoying.

Awesome theme, sure it is : )
***
### Configuration

 - **Operating system with version** : OS X El Captain 10.11.5
 - **Node version** : 4.4.7
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.8.0 original

**Comment by LouisBarranqueiro** [comment]
Hey @abelsu7,

comment these 2 lines in [source/_js/header.js](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/source/_js/header.js#L68-L69) and rebuild the theme.

Thanks for using this theme :)

**Comment by abelsu7** [comment]
Thanks for your reply. I'll have a try :)
