### ISSUE TITLE
Upgrade README.md showcase to display latest version

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#299]
### Actual behavior

`README.md` showcase display 1.7.0 version

### Expected behavior

`README.md` showcase display 1.9.0 version (even more since new *sidebar behavior*)

<img width="944" alt="screen shot 2016-07-13 at 22 09 56" src="https://cloud.githubusercontent.com/assets/275609/16818213/eaa9c2e0-4946-11e6-85f7-c731cd4d95ef.png">

**Comment by LouisBarranqueiro** [comment]
YEAH! I saw that yesterday. :D I'm on it

**Comment by LouisBarranqueiro** [comment]
![v1 9](https://cloud.githubusercontent.com/assets/4705626/16965741/e1804c2e-4e01-11e6-9f61-1a762f31beec.jpg)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.9.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.1) is released :)
