### ISSUE TITLE
Horizontal scrolling on non-mobile device overlap with sidebar

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#300]
### Configuration

 - **Operating system with version** :  Mac OSX 10.11.5 with Chrome 51
 - **Node version** : 6.3.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.0 (still same issue on 1.7.1)
 

### Actual behavior

Horizontal scrolling on article

<img width="1437" alt="screen-shot-2016-07-13-at-22 22 14" src="https://cloud.githubusercontent.com/assets/275609/16882597/269e9c2e-4ac0-11e6-80f6-3b90d459e63c.png">

### Expected behavior

3 solutions (I have no personal preference):

1. Same behavior as mobile device: horizontal scrolling will close sidebar
2. Content should not overlap sidebar
3. Content should be responsive regarding sidebar so no scrollbar should exists

### Steps to reproduce the behavior

Go to http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/06/15/Welcome-to-the-new-Tranquilpeak/ and scroll horizontally

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.9.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.1) is released :)
