### ISSUE TITLE
Search post links are broken

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#301]
### Actual behavior

**Filtered** post using new search box (based on `Algolia`) link to wrong URL.

<img width="1440" alt="screen shot 2016-07-17 at 10 40 09" src="https://cloud.githubusercontent.com/assets/275609/16899624/db1f6fb6-4c0a-11e6-9241-67cfd484f99c.png">

Where http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/hexo-theme-tranquilpeak/2015/05/28/Elements-showcase/

<img width="982" alt="screen shot 2016-07-17 at 10 40 40" src="https://cloud.githubusercontent.com/assets/275609/16899627/f445d78c-4c0a-11e6-95f3-bc0fac72f599.png">

### Expected behavior

Avoid `404`

### Steps to reproduce the behavior

**ATTENTION you must filter (add keyword and apply search) to reproduce)**
**Unfiltered list has correct URL**

1. Go to http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak
2. Click on _search_ button
3. Write keyword (example `markdown`) 
4. Open post

**Comment by LouisBarranqueiro** [comment]
It's not a bug from the theme, I'm working on hexo-algoliasearch (sync feature) and I used the the same, it's a mistake, i'm gonna fix it :D
