### ISSUE TITLE
Sidebar author bio should depends on sidebar behavior

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#303]
### Configuration

 - **Operating system with version** :  Mac OSX 10.11.5 with Chrome 51
 - **Node version** : 6.3.0
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.0
 

### Actual behavior

If `author.bio` is defined inside translation files, `tranquilpeak` theme will render it on `sidebar`. However render is pretty cool on _new big sidebar_ when `sidebar_behavior: 1` but when `sidebar_behavior: 2` result is not so cool

<img width="76" alt="screen shot 2016-07-17 at 12 04 17" src="https://cloud.githubusercontent.com/assets/275609/16899999/ef102d60-4c16-11e6-80d8-3333ce0abe90.png">

### Expected behavior

Only display `author.bio` when sidebar is format: _big_

### Steps to reproduce the behavior

**ATTENTION** `author.bio` rendering is depending on screen size so you may no reproduce if screen is too small

1. Edit `_config.yml` to add `sidebar_behavior: 2`
2. Add `author.bio` inside `en.yml`
3. Open homepage on large screen

**Comment by LouisBarranqueiro** [comment]
i'm on it :)

**Comment by LouisBarranqueiro** [comment]
Same bug with `sidebar_behavior:4`.

**Comment by LouisBarranqueiro** [comment]
Now that bug is fixed, you have to prove that you are a fucking blogger rockstar :D

**Comment by kakawait** [comment]
It's not me it's Jean Bon :) thank for correction

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.9.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.1) is released :)
