### ISSUE TITLE
Change homepage?

### ISSUE THREAD

**Issue by willwade** [LouisBarranqueiro/hexo-theme-tranquilpeak#304]
### Configuration
- **Operating system with version** : Mac OSX 10.11.5
- **Node version** : v4.2.2
- **Hexo version** : 3.2.0
- **Hexo-cli version** : 1.0.2
- **Tranquilpeak version** : original 

I want a single post displayed on the home (index) page instead of the blog posts..  Is this possible??

**Comment by LouisBarranqueiro** [comment]
what do you means? only one post on index, or display the whole content of your post on index page?

**Comment by LouisBarranqueiro** [comment]
> and a link to the /all-tags/ page..). 

Do you know that you can customize link of the sidebar? 

> So / shows the standard sidebar but with one post e.g. MyHomePage.md (I intend to put some welcome text in there

About that, I would be better to create a page `home.md`. But if a sticky post feature would be good to you I can implement that :)

**Comment by LouisBarranqueiro** [comment]
yeah, like I said, you need to customize layout of theme to display `home.md` on `/` and blog posts on `posts/` for example, and it's gonna be very complicated if you did know how hexo works.

**Comment by LouisBarranqueiro** [comment]
you want an home page to say hello? to introduce yourself?

**Comment by willwade** [comment]
Well to introduce the site.. (its not really a personal blog - its an index of open source assistive technology software).. I think I can live with just making it sticky  👍  Thanks for the help :)

**Comment by LouisBarranqueiro** [comment]
ok, for the moment, you can use a future date to make it sticky like you proposed, i'm gonna take a look to add a variable in front-matter like `sticky: true` to make it sticky :)

**Comment by willwade** [comment]
nice one! Thanks..

**Comment by jrbenito** [comment]
@LouisBarranqueiro and @willwade ,

Food for thoughts:

If one put `sticky: true` on two or more posts , are you going to show all? IMHO, it does not make sense.

How about a config switch? The normal behavior is to render the root page as index of most recent posts (actual behavior). If the switch has a value (a name of page/post for instance), it swaps the behavior of root page to display the content of that page/post. 

PS: the intention here is just to feed the discussion with other arguments.

**Comment by LouisBarranqueiro** [comment]
@jrbenito  @willwade 

> If one put sticky: true on two or more posts , are you going to show all? IMHO, it does not make sense.

yeah, some user had already asked a sticky post feature. and yeah, it can have multiple sticky post. (e.g: improve visibility of famous post).

> How about a config switch? The normal behavior is to render the root page as index of most recent posts (actual behavior). If the switch has a value (a name of page/post for instance), it swaps the behavior of root page to display the content of that page/post.

We should not forget that it's a theme for blog, @willwade use this theme to do something different than blogging so it's normal to wanna customize some part and this is what I recommend. :) I want to keep this theme the most simple as possible and highly customizable too. But this homepage built-in feature, seems to me a bit to much for a blog theme. I prefer to spend time on feature related to blog activity :). But let's open a discussion on Github and prevent user on Gitter, to gather views :)

**Comment by willwade** [comment]
I kind of agree - its a blog theme and lets not complicate it... However.. One sticky post maybe useful for all sorts of purposes - for example I can see a case of having a short intro at the top of the homepage for even a blog (and it would be useful for the demo itself.. ??). To be clear this is how I'm using it: http://openassistive.github.io/oatsoft

**Comment by jrbenito** [comment]
@LouisBarranqueiro 

I agree with your points.
