### ISSUE TITLE
Not generating assets folder. 

### ISSUE THREAD

**Issue by willwade** [LouisBarranqueiro/hexo-theme-tranquilpeak#306]
### Configuration
 - **Operating system with version** : Mac OSX 10.11.5
 - **Node version** : v4.2.2
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : original 
 
 
More of a call for help this.. Any suggestions why my hexo generate or server is not creating the assets folder?? (NB: I have recently moved around my code to make my repo nicer.. I'm sure I've messed something up in the process.. gah).
Whole site is here: https://github.com/openassistive/OATSoft

**Comment by LouisBarranqueiro** [comment]
Hey @ willwade

Be careful, you got the source and not the built version ready for production, so you have to install all requirements, dependencies, and build the theme. Check this section for more information : [dev doc - installation](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation)

**Comment by willwade** [comment]
Gah.. Sorry. I've gone from using production to dev about 40 times. Apologies for not RTFM'ing again..

**Comment by LouisBarranqueiro** [comment]
np man, is it working now? :)

**Comment by willwade** [comment]
Is indeed. Having intermittent problems with algolia working but other than that! 

https://openassistive.github.io/OATSoft/

**Comment by LouisBarranqueiro** [comment]
I reported this bug : https://github.com/hexojs/hexo/issues/2048. Downgrade to 3.1.0 to solve this issue
