### ISSUE TITLE
Image is not centered

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-theme-tranquilpeak#307]
- **Tranquilpeak version** :  1.9 (not modified in given below parts)
 

### Actual behavior
Alone image is not centered with `center` class and `n<100 %` width attribute in image tag

![001](https://cloud.githubusercontent.com/assets/16353578/16999978/44a811d4-4ec9-11e6-9d63-c9cc08966b34.jpg)

### Steps to reproduce the behavior

**theme's _config.yml**
```
sidebar_behavior: 1
clear_reading: true
```
**image tag in post**
```
{% image fancybox center image.jpg 75% "Caption" %}
```
_*75% or %50 or anything else <100%_

**Comment by jrbenito** [comment]
@aerohub 

Is it centered in regard the whole screen (not text container)?

**Comment by aerohub** [comment]
@jrbenito 
No. The screenshot above is of the whole screen, and you can see it's not.

**Comment by LouisBarranqueiro** [comment]
Hey @aerohub, you are right. I'm on it :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.9.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v1.9.1) is released :)
