### ISSUE TITLE
click left top button,can't view back sidebar,  No response

### ISSUE THREAD

**Issue by LOVEChen** [LouisBarranqueiro/hexo-theme-tranquilpeak#308]
pls help

**Comment by LouisBarranqueiro** [comment]
Hey @LOVEChen, I would like to help you but please read [Guidelines to ask question/report a bug](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by LOVEChen** [comment]
### Configuration

 - **Operating system with version** : 
 - **Node version** : 6.3.1
 - **Hexo version** : 3.2.2 
 - **Hexo-cli version** : 1.02
 - **Tranquilpeak version** : 1.9.0 original git version
 

### Actual behavior
click on article top bar left corner button, it won't show sidebar to me.



### Expected behavior
click the button , show the sidebar.



### Steps to reproduce the behavior
click on article top bar left corner button, system no response.

sorry for my english :) thx alot

**Comment by LouisBarranqueiro** [comment]
ok buddy, this bug has already been reported https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/296, it will be fixed in the next release. In some hours (1 - 2hrs), I'm gonna release the new version :)

**Comment by LouisBarranqueiro** [comment]
also welcome on GitHub :)

**Comment by LOVEChen** [comment]
thx for you kind and fast reply , thx!
