### ISSUE TITLE
Loading "Gruntfile.js" tasks...ERROR

### ISSUE THREAD

**Issue by abelsu7** [LouisBarranqueiro/hexo-theme-tranquilpeak#310]
### Configuration

 - **Operating system with version** : Mac OS X El Capitan 10.11.6
 - **Node version** : 4.4.7
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.8.0, original
 

### Actual behavior

Hey bro,

I think there should be sth wrong with my Grunt installation.

I have followed your instructions in the developer documentation.However, when I run `grunt default`, it gives the following error message -

```bash
# AbelSu at suchuanyudeMacBook-Air.local in ~/abelsu7.github.io/themes/tranquilpeak on git:master ✖︎ [10:20:03]
→ grunt default
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'webpage'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

Following is My grunt installation information -

```bash
# AbelSu at suchuanyudeMacBook-Air.local in ~/abelsu7.github.io/themes/tranquilpeak on git:master ✖︎ [10:27:58]
→ grunt --version
grunt-cli v1.2.0
grunt v0.4.5
``` 

I have searched for the solution but nothing satisfies. How should I fix it?

**Comment by abelsu7** [comment]
I just run `npm install webpage` and run `grunt default`again, the error message is like this -

```bash
# AbelSu at suchuanyudeMacBook-Air.local in ~/abelsu7.github.io/themes/tranquilpeak on git:master ✖︎ [11:19:49]
→ grunt default
Loading "Gruntfile.js" tasks...ERROR
>> TypeError: require(...).create is not a function
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.
```

**Comment by LouisBarranqueiro** [comment]
Hey @abelsu7, did you run `npm install` in theme folder?

**Comment by abelsu7** [comment]
Sure, I have run `npm install` in `Tranquilpeak` theme folder.

**Comment by LouisBarranqueiro** [comment]
be sure you got the right grunt structure, maybe you edited a grunt tasks involuntarily. Re-download the source of [grunt tasks](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/tree/master/tasks) folder because I never seen this error before.

**Comment by abelsu7** [comment]
Sorry bro, it's totally my mistake...
I used the production code for developing rather than the source code without aware of it!
Hope not bothering you : )

**Comment by LouisBarranqueiro** [comment]
Is it working now?

**Comment by abelsu7** [comment]
As expected, it works successfully.

**Comment by LouisBarranqueiro** [comment]
good news :)
