### ISSUE TITLE
can't deploy success

### ISSUE THREAD

**Issue by HIKALU-Z** [LouisBarranqueiro/hexo-theme-tranquilpeak#312]
### Configuration

 - **Operating system with version** : mac ei captain 10.11 
 - **Node version** : 5.4
 - **Hexo version** : 3.2
 - **Hexo-cli version** : 
 - **Tranquilpeak version** :  original 
 

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/14190574/17278062/b1e97264-5785-11e6-9576-a68443c8a014.png)

i  can success to view my blog at localhost:4000/
but when i deploy it ,it will can't push.just like the picture 

i have tryed `hexo clean` and delete `.depoly_git/` but it still doesn't work

**Comment by LouisBarranqueiro** [comment]
Hey @HIKALU-Z, this is not related to the theme. Check your deploy config, specially your credentials. E.G : GitHub credentials if you deploy it on GitHub

**Comment by HIKALU-Z** [comment]
thank you after i change theme and depoly success 
i change back to your theme and is success.
