### ISSUE TITLE
How to defined the share link?

### ISSUE THREAD

**Issue by HIKALU-Z** [LouisBarranqueiro/hexo-theme-tranquilpeak#313]
hi. 
thank you to read my question.
i am a user in china ,if i want share my post to weixin(or some other website in china),
how can i change your theme to share my post to the website i want

**Comment by HIKALU-Z** [comment]
i mean which ejs file should i change?

**Comment by HIKALU-Z** [comment]
after i change the file at `layout/_partial/post/share-option.ejs` and use` hexo clean`
it still didn't work
did i do something wrong?

**Comment by LouisBarranqueiro** [comment]
Hey buddy, read this post :) https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/289

It will be good to add this feature. I mean : in theme configuration file, give possibility to choose which share option to add at the bottom of an article. like this :  

``` yml
share_options:
    - facebook
        - fa-facebook #font awesome icon  
    - twitter
        - fa-twitter
    - wechat
        - fa-wechat
```
 But I need your help :)

Could you give me the main list of all social networks and platforms that china users use to share content, please? I need the name of the social networks and the share link.

**Comment by antonioaguilar** [comment]
Hi Louis,
I'm wondering if the ```share_options``` feature is available? I'm having some problems trying to add the LinkedIn share url. My blog posts title and content is not picked up correctly by LinkedIn. 
Below is the HTML template I'm using in the ```actions.ejs``` file:

```html
        <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="<%= 'https://www.linkedin.com/shareArticle?mini=true&url=' + post.permalink %>">
                <i class="fa fa-linkedin-square "></i>
            </a>
        </li>
```

This is the HMTL in the ```share-options.ejs``` file:

```html
        <li class="share-option">
            <a class="share-option-btn" target="new" href="<%= 'https://www.linkedin.com/shareArticle?mini=true&url=' + post.permalink %>">
                <i class="fa fa-linkedin-square"></i><span><%= __('global.share_on_linkedin') %></span>
            </a>
        </li>
```

Any suggestions or ideas?

thanks!
