### ISSUE TITLE
need enhance the date and fig view

### ISSUE THREAD

**Issue by LOVEChen** [LouisBarranqueiro/hexo-theme-tranquilpeak#315]
### Configuration

 - **Operating system with version** : OS X EI Capitan 10.11.6 / Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
 - **Node version** : 6.3.1
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.1 original
 

### Actual behavior
this is not bug , pls enhance some more future.
and thank you enhance this large sidebar in 1.9.1

![2 pic](https://cloud.githubusercontent.com/assets/7329959/17303070/a8965ade-5851-11e6-84cd-4b72856ab378.jpg)

**Comment by LouisBarranqueiro** [comment]
Hey buddy, 
I understand about `fig` CSS classes for image tag and copyrights. But not the rest. what is ORT?  could you write all features request as text and with some explanations please :)

**Comment by LOVEChen** [comment]
define:
*G= Global setting
*S= 	Single page setting

request:
Date in the page: hide / display *G / *S
up page / down page : hide / display *G / *S
facebook / google / twiter etc...icon: hide / display all or only display selected *G / *S
Copyright Date:hide / display / set custom value ex:2002-2016 *G
fig: more fig option or user can set by self like fig-(any num) *S

:)

**Comment by LOVEChen** [comment]
Hi Louis, do you have any plan to enhance it? thank you buddy~

**Comment by LouisBarranqueiro** [comment]
Hey @LOVEChen, sure. I'm just busy at this time. :D 

Could you open an issue for : 
- fig enhancements
- page settings to disable/enable components
- about copyrihts, i'm currently not decided
- about sharing options list - i'm on it here : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/314

**Comment by LOVEChen** [comment]
ok thx~
