### ISSUE TITLE
firefox jumps to random line on page

### ISSUE THREAD

**Issue by Dapuva76** [LouisBarranqueiro/hexo-theme-tranquilpeak#316]
Just checked out your demo site, when I click a link to an article (using FF 48 on Win7), it opens the link, but not at the top. sometimes in the middle, sometimes at the bottom of the page.

This is what it looks like when I click "Welcome to Tranquilpeak"

http://imgur.com/a/dgvBz

**Comment by LouisBarranqueiro** [comment]
Hey @Dapuva76, 

yeah, I noticed this bug too. I'm on it :)
