### ISSUE TITLE
'OLDER POSTS' Button Overlaps Sidebar

### ISSUE THREAD

**Issue by abelsu7** [LouisBarranqueiro/hexo-theme-tranquilpeak#318]
### Configuration
- **Operating system with version** : Mac OS X El Capitan 10.11.6
- **Node version** : 4.4.7
- **Hexo version** : 3.2.2
- **Hexo-cli version** : 1.0.2
- **Tranquilpeak version** : 1.9.1 modified

### Actual behavior

When visiting the home page with a mobile phone, the sidebar hides and the header bar shows as expected.

However, when I click the menu button to make sidebar show, the `OLDER POST` navigation button overlaps the sidebar like this -

<div align=center>
<img src="http://o9zpdc3re.bkt.clouddn.com/2016-08-05_error.png" />
</div>

### Steps to reproduce the behavior

Using mobile phones, tablets or desktop browsers with a small/medium screen (in other words, let the sidebar hides) to view [this page](http://abelsu7.cn), then click the menu button and scrolls down to the bottom, you'll find this.

**Comment by LouisBarranqueiro** [comment]
Hey @abelsu7 , image is not correctly displayed, I can't see the bug. and I try to reproduce it but I can see the button as expected

**Comment by abelsu7** [comment]
Sorry, it seems that the picture above wasn't uploaded successfully.

When I visit my homepage using developer tools of Opera browser, it shows like this without any problem -
![screenshot 6](https://cloud.githubusercontent.com/assets/15975045/17759454/ca827346-6529-11e6-9288-909d788c1dcd.png)

However, when I clicked the menu button and scrolls down to the bottom, the `OLDER POST` button overlaps the sidebar like this -
![screenshot 7](https://cloud.githubusercontent.com/assets/15975045/17759484/fb1a858e-6529-11e6-8294-d09e5f22ca50.png)

**Comment by LouisBarranqueiro** [comment]
Did you try in other browsers? Chrome? Firefox?

**Comment by robinWongM** [comment]
Sorry for my poor English.

Everything goes well on Firefox 48.
![screenshot_firefox](https://cloud.githubusercontent.com/assets/2606137/17966716/91de1316-6af5-11e6-8537-d5b9b59ab37d.png)
But the bug can be reproduced on Chrome 52 & Opera 39(Chromium 52). (Windows of course)
![screenshot_chrome](https://cloud.githubusercontent.com/assets/2606137/17967259/abc8f752-6af8-11e6-9967-82bb82f31e5a.png)
------
At last, I found that it rendered correctly after removing "float":
![screenshot_chrome_remove_float](https://cloud.githubusercontent.com/assets/2606137/17967335/2df0098c-6af9-11e6-91d5-7867081e8609.png)
Maybe it's a chrome bug about float and transform:translate.
Hope this helpful. :)

**Comment by LouisBarranqueiro** [comment]
ok thanks man, i'm on it
