### ISSUE TITLE
hexo server is fail to start when i use hexo-theme-tranquilpeak

### ISSUE THREAD

**Issue by YeMingQiaoYu** [LouisBarranqueiro/hexo-theme-tranquilpeak#325]
### Configuration

 - **Operating system with version** : Mac OX X El Capitan 10.11.6
 - **Node version** : 4.4.7
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.1     the theme is original
 

### Actual behavior
I want to start hexo server, but fail
![qq20160811-3](https://cloud.githubusercontent.com/assets/14698591/17576685/e911f188-5fa7-11e6-9894-15ee0a57b3a3.png)

### Expected behavior
I just want the theme can apply for my blog

### Steps to reproduce the behavior
hexo server
........

**Comment by YeMingQiaoYu** [comment]
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.5.2
node: 4.4.7
v8: 4.5.103.36
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2h

**Comment by YeMingQiaoYu** [comment]
![qq20160811-1](https://cloud.githubusercontent.com/assets/14698591/17573584/f7565f0a-5f8d-11e6-94a7-3e4220596cea.png)

**Comment by YeMingQiaoYu** [comment]
hope someone help me

**Comment by gauthamzz** [comment]
is this closed?

**Comment by YeMingQiaoYu** [comment]
yes，I just download the not compiled files

**Comment by uglybachelor** [comment]
@YeMingQiaoYu Hi, I'm not sure I understand how you solve the problem. I'm using the latest production version of this theme, and it works perfectly fine on my mac. But when I uploaded the project to my server, I ran into the same problem you did. How did you solve it exactly?

**Comment by LouisBarranqueiro** [comment]
Hey @uglybachelor , create an issue to describe your problem, I'm gonna help you :)
