### ISSUE TITLE
Feature Request: 404 page

### ISSUE THREAD

**Issue by Mr0Null** [LouisBarranqueiro/hexo-theme-tranquilpeak#327]
for user experience, it's better to have a 404 page designed for blog! It is better to be compiled with hexo, but we can take advantage of .htaccess to define custom 404 page!

**Comment by LouisBarranqueiro** [comment]
Yeah buddy!

**Comment by darekkay** [comment]
While it would be a nice-to-have, it's quite simple to create a custom 404 page in Hexo, without adjusting the theme. Create `404.md` in the `source` folder, so Hexo generates a corresponding `404.html`. Now you can configure your web server to use this page for 404 by default.

[That's](https://darekkay.com/404) how it looks like on my page.

**Comment by LouisBarranqueiro** [comment]
yeah, you are right @darekkay. Could you add a section in the user documentation to describe how you did it step by step?

**Comment by darekkay** [comment]
@LouisBarranqueiro 
Sure, however I just noticed it's not as simple as I described it. By default, meta and post actions are rendered as well, which looks weird on a 404 page. So I have added two front matter options to disable those:

```
title: Whoops!
hideMeta: true
hideActions: true
comments: false     # this one already exists
```

If this is something you would like to include in your project, I can create a PR ;)

**Comment by LouisBarranqueiro** [comment]
yes, create the PR, I will review it :)

**Comment by darekkay** [comment]
Sure thing: #399
