### ISSUE TITLE
Feature Request: Related posts

### ISSUE THREAD

**Issue by Mr0Null** [LouisBarranqueiro/hexo-theme-tranquilpeak#331]
One of the best ways of keeping visitors in your blog is showing the related posts! why not having it?

**Comment by LouisBarranqueiro** [comment]
Cause it take some time to build an "intelligent" selection of related posts, not only based on tags or categories. Could you implement it?

**Comment by Mr0Null** [comment]
I'm not sure I have enough time :( even having posts selected by tag is enough I think! maybe we can add a section to front-matter called related posts

**Comment by LouisBarranqueiro** [comment]
I currently don't have time to implement this feature. But I let it open if someone want to help :)

**Comment by Mr0Null** [comment]
Is there any way so we can get latest posts in some tag??

**Comment by LouisBarranqueiro** [comment]
yeah, with 
``` js
site.tags.findOne({name: 'tagName'}).posts.sort('date', -1).limit(5)
```
it will give you the 5 latest posts of a tag

**Comment by YoshinoriN** [comment]
@Mr0Null 

You can generate related posts using by [this plugin](https://github.com/tea3/hexo-related-popular-posts), if you using google analytics.
This plugin generate related posts based on tags & page view of google analytics.

**Comment by LouisBarranqueiro** [comment]
@Mr0Null Are you still working on it?

**Comment by Mr0Null** [comment]
completely forgot about it 😁

**Comment by LouisBarranqueiro** [comment]
So let's close it for now.

**Comment by psi-4ward** [comment]
yay, wasted some time with existing solutions and came up with my own: https://gist.github.com/psi-4ward/d3a2ff3b6500129e936ce6e24d6871e5

**Comment by huiwang** [comment]
Hello everyone, I developed a new plugin which generates a list of recommended posts for each post. This list contains both internal and exchanged external links. You can live preview this feature [here](http://hui-wang.info/2017/12/02/%E5%AD%A6%E4%B9%A0%E5%A6%82%E4%BD%95%E5%AD%A6%E4%B9%A0/). 

For more details about the plugin, you can find the doc [here](https://github.com/huiwang/hexo-recommended-posts/blob/master/README-en.md)
