### ISSUE TITLE
When input `s` in duoshuo's input field, the window of algolia search pops up immediately.

### ISSUE THREAD

**Issue by showzeng** [LouisBarranqueiro/hexo-theme-tranquilpeak#334]
### Configuration
- **Operating system with version** : Ubuntu 16.04.1 LTS
- **Node version** : 6.4.0
- **Hexo version** : 3.2.2
- **Hexo-cli version** : 1.0.2
- **Tranquilpeak version** : 1.9.1 original
### Actual behavior

I'm using duoshuo to comment. When you input `s` in input field, the window of algolia search will pop up immediately.
### Expected behavior

It shouldn't act like this and this is unfriendly. And it's seems not the duoshuo's bug. 
### Steps to reproduce the behavior

Any Operating system with duoshuo plugin. when you comments show `s` in input field, the window of algolia search will pop up immediately.

**Comment by Rui-Sun** [comment]
I change the number "83" of 'tranquilpeak\source\assets\js\script-taaobz4ueybn54ikf9gtu3wlm8tpgzjkwfknygrtitquljbwokv26p56moto.min.js Line4,Column24815' in to "118", so that typing 'F7' will call out the algolia, isn instead of 's'.
