### ISSUE TITLE
can I show a specific category under 'about'

### ISSUE THREAD

**Issue by sanyucz** [LouisBarranqueiro/hexo-theme-tranquilpeak#336]
I have categorys : 'swift', 'Objective-C' .... ,now i want show 'swift' on sidebar,

e.g : 

- home
- category
- archive
- search
- about
- swift
- GitHub

Can I do this? because i hope see swift when I or other visit the website

**Comment by sanyucz** [comment]
because i hope see swift when I or other visit the website

**Comment by LouisBarranqueiro** [comment]
Hey @sanyucz,

yeah of course, go in `config.yml` file of the theme, to add a new item menu : 
eg : 
sidebar:
    menu:
        # ....
        swift:
            title: "swift"
            url: /tags/swift
            icon: code

Read [User doc - sidebar](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#sidebar) for more information

**Comment by sanyucz** [comment]
thanks~~
