### ISSUE TITLE
It`s a bug on safari for iPhone?

### ISSUE THREAD

**Issue by sanyucz** [LouisBarranqueiro/hexo-theme-tranquilpeak#337]
### Configuration
- **Operating system with version** : OS X10.10.5 / iOS 10 beta
- **Node version** : v6.3.1
- **Hexo version** : 3.2.2
- **Hexo-cli version** : 1.2.0
- **Tranquilpeak version** : original

on safari for iPhone，tap menu，show sidebar, then click home button,open safari,
drag home page cover the sidebar

**Comment by sanyucz** [comment]
here is screenshot 
![screenshot](http://od6bpfkkf.bkt.clouddn.com/screenshot.gif),
 i try it on safari for iPhone5C(iOS 9.3),but it can not reproduce. It seems there is only on safari(iOS 10 beta).

**Comment by sanyucz** [comment]
give you the img url : http://od6bpfkkf.bkt.clouddn.com/screenshot.gif ..

**Comment by LouisBarranqueiro** [comment]
Did you test it on the IOS10 GM?

**Comment by sanyucz** [comment]
it only show iOS 10 GM but iOS 9

**Comment by LouisBarranqueiro** [comment]
I don't understand. What do you mean?
> it only show iOS 10 GM but iOS 9

**Comment by sanyucz** [comment]
```
if (iOS 10 GM){
    there is a bug 
}else{
    not is a bug 
}
```

then , do you understand it ?

**Comment by LouisBarranqueiro** [comment]
:D yes, ok. I'm gonna wait the release to test it and fix it :)

**Comment by LouisBarranqueiro** [comment]
confirmed. I'm on it.

**Comment by LouisBarranqueiro** [comment]
I decided to not fix this bug for the moment because it is very specific. We will see if new IOS version have this bug
