### ISSUE TITLE
title to center

### ISSUE THREAD

**Issue by joy-chen** [LouisBarranqueiro/hexo-theme-tranquilpeak#343]
Hi,
How can i set the title align center?

**Comment by FelixINX** [comment]
Which title are you talking about? Can you send a screenshot?

**Comment by joy-chen** [comment]
Hi,
I wish the title in red circle could be set at center.

**Comment by LouisBarranqueiro** [comment]
Hi @joy-chen,

No you can't on index page. you can only change title position on post page

**Comment by joy-chen** [comment]
I see @LouisBarranqueiro 
and wish to add this feature in future version.

**Comment by LouisBarranqueiro** [comment]
All content is aligned to the left, it does not make sens to only align title to the center
