### ISSUE TITLE
Algolia Search is not working

### ISSUE THREAD

**Issue by abhi1693** [LouisBarranqueiro/hexo-theme-tranquilpeak#344]
### Configuration

 - **Operating system with version** : 
 - **Node version** : 6.6.0
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : Original Theme (1.8.0)
 
I followed your documentation, installed all the plugins for algolia search and I've also filled up the _config.yml with the configuration strings.

But whenever I click on the search button on the sidebar, nothing happens.

My blog [link](https://abhi1693.github.io/tux-tips/)

**Comment by LouisBarranqueiro** [comment]
Hey @abhi1693 , Algolia search integration is available in 1.9.x :)

**Comment by abhi1693** [comment]
Ok, I download your production ready package that you had mentioned on the Readme. Anyway, thank you!

**Comment by talipovdaniyar** [comment]
Hey @LouisBarranqueiro first of great Theme and documentation. But I still have troubles getting the search window to pop out. I followed your 4 steps to the letter...

I am getting my indices on my Algolia page so 'Hexo Algolia' does register my posts, but when I click on the search icon nothing happens.

(I am using version 1.9.1 of tranquilpeak)
