### ISSUE TITLE
Unhandled rejection TypeError: /Users/VictorZhang/Documents/HEXOBLOG/blog/themes/ppoffice/layout/index.ejs:2

### ISSUE THREAD

**Issue by VictorZhang2014** [LouisBarranqueiro/hexo-theme-tranquilpeak#346]
When I `hexo generate`,  I got this error, what should I do?

**Comment by LouisBarranqueiro** [comment]
as you can see the error come from an other theme (ppoffice) and not this one. If you really wanna use tranquilpeak, delete the old theme and try again
