### ISSUE TITLE
Title display bug when closing sidebar using gesture on mobile

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#351]
### Configuration
- **Operating system with version** : Android 6 with chrome
- **Tranquilpeak version** : http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/

### Actual behavior

Using mobile device (bug is reproducible using chrome debug on desktop) when closing sidebar using gesture, title is no more center

<img width="352" alt="screen shot 2016-10-09 at 22 09 00" src="https://cloud.githubusercontent.com/assets/275609/19223306/0f55830c-8e6d-11e6-98c7-b007fc717502.png">

if you try to open sidebar again using button that not open sidebar but fix title (center it)

### Expected behavior

gesture should have same behavior than button

<img width="319" alt="screen shot 2016-10-09 at 22 09 48" src="https://cloud.githubusercontent.com/assets/275609/19223310/233ad7e6-8e6d-11e6-9923-6c4e9e2a4748.png">

### Steps to reproduce the behavior
- Load http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/ on chrome
- Open debug tool and set device to `Nexus 5x`
- Open sidebar (by gesture or button, whatever)
- Close it using gesture

result:

<img width="352" alt="screen shot 2016-10-09 at 22 09 00" src="https://cloud.githubusercontent.com/assets/275609/19223305/0565a174-8e6d-11e6-84ba-68b617d5c64a.png">

**Comment by LouisBarranqueiro** [comment]
confirmed. I'm on it

**Comment by LouisBarranqueiro** [comment]
I decided to not fix this bug for the moment because it require many changes. I will re-open the issue if many users complaint about it.

**Comment by LouisBarranqueiro** [comment]
👋 @kakawait, I wanted to work on it but I didn't manage to reproduce this bug. What about you? Maybe the latest Chrome version "fix" this issue.
