### ISSUE TITLE
Cannot find module 'async'

### ISSUE THREAD

**Issue by clayclayclay** [LouisBarranqueiro/hexo-theme-tranquilpeak#353]
$ hexo server
ERROR Script load failed: themes\hexo-theme-tranquilpeak\scripts\migrators\1.4.0.js
Error: Cannot find module 'async'

how to fix the problem?

**Comment by LouisBarranqueiro** [comment]
Hey @clayclayclay , 

short answer : 
- cd ` themes\hexo-theme-tranquilpeak`
- `npm install`

If you want a long answer, fill all fields required to post an issue. I bet you download the source and not the built version ready for production.

**Comment by LouisBarranqueiro** [comment]
Download built version ready for production : [hexo-theme-tranquilpeak-built-for-production-1.9.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/download/v1.9.1/hexo-theme-tranquilpeak-built-for-production-1.9.1.zip)

**Comment by LouisBarranqueiro** [comment]
Is it working?

**Comment by clayclayclay** [comment]
@LouisBarranqueiro uh,I think so ,Thank you~
