### ISSUE TITLE
Support Azure Search

### ISSUE THREAD

**Issue by prajaybasu** [LouisBarranqueiro/hexo-theme-tranquilpeak#354]
[Free Azure Subscription to test out ($25/mo credit for 1 year; no CC required IIRC)](https://www.visualstudio.com/dev-essentials/)
[About Azure Search](https://azure.microsoft.com/en-in/services/search/)
[And there is already a plugin that indexes to Azure Search](https://github.com/artchen/hexo-azuresearch)
I think this is one of the only indexing services left that has a free tier. (Except about less than a dollar for overall data transfer per datacenter)

**Comment by LouisBarranqueiro** [comment]
Hey @prajaybasu, could you PR? :)
