### ISSUE TITLE
Code font Menlo in device except Mac

### ISSUE THREAD

**Issue by tcztzy** [LouisBarranqueiro/hexo-theme-tranquilpeak#355]
### Configuration
- **Operating system with version** : Windows and Linux
- **Node version** : v4.6.0
- **Hexo version** : 3.2.2
- **Hexo-cli version** : 1.0.2
- **Tranquilpeak version** : 1.9

### Actual behavior

Not mono space display.

### Expected behavior

Code should display in mono space.

### Steps to reproduce the behavior

After install the Menlo font, it display correctly.
### Solution

Change the Menlo font to another cross-platform font or add to web font.

**Comment by kakawait** [comment]
Fix seems to be already delivered https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/322 but you must need to wait new version to be released to get it

**Comment by tcztzy** [comment]
@kakawait Thanks a lot.
