### ISSUE TITLE
Does the theme have the feature of subcategory?

### ISSUE THREAD

**Issue by LEAFERx** [LouisBarranqueiro/hexo-theme-tranquilpeak#357]

**Comment by LouisBarranqueiro** [comment]
Hexo allow sub categories but what do you expect at theme level?

**Comment by LEAFERx** [comment]
I think it will be better if a specific category page still has its sub categories structure instead of all posts mixing together :).

**Comment by LouisBarranqueiro** [comment]
check [all categories page](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/all-categories/)

**Comment by LEAFERx** [comment]
I mean a page like [this](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/categories/tranquilpeak/). It doesn't have a sub categorie sstructrue.

**Comment by LouisBarranqueiro** [comment]
I understand, but it not really useful since we have the all categories pages.
