### ISSUE TITLE
A question about search engine verification...

### ISSUE THREAD

**Issue by LEAFERx** [LouisBarranqueiro/hexo-theme-tranquilpeak#358]
Most search engines require to  put a certain file into the website root to verify the owner of the website.
But when I put the file into the "source" fold, Hexo automatically added the html template of the theme, which means I need to paste the correct file into "public" fold manully every time before I run `hexo g`.

How can I solve this?

**Comment by LouisBarranqueiro** [comment]
Hey @LEAFERx, could you provide an example? or give more details about what you want to achieve, please?
