### ISSUE TITLE
`/all-archives`, `/all-categories` & `/all-tags` these pages haven't been generated

### ISSUE THREAD

**Issue by ajielee** [LouisBarranqueiro/hexo-theme-tranquilpeak#359]
### Configuration

 - **Operating system with version** : Darwin 16.1.0 darwin x64
 - **Node version** : v7.0.0
 - **Hexo version** : 
 - **Hexo-cli version** : 1.0.2
 - **Tranquilpeak version** : 1.9.1 (Modified)
 

### Actual behavior

- `/all-archives`: Cannot GET /all-archives
- `/all-categories`: Cannot GET /all-categories
- `/all-tags`: Cannot GET /all-tags

**Comment by kakawait** [comment]
Did you follow the corresponding documentation https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-pages ?

**Comment by ajielee** [comment]
@kakawait Oh, sorry! I didn't read the whole document. Thanks for your help!

**Comment by kakawait** [comment]
@ajielee please close issue if doc process solves your issue. 

Good luck with tranquilpeak
