### ISSUE TITLE
How can I create a link for jumping inside the page ?

### ISSUE THREAD

**Issue by ajielee** [LouisBarranqueiro/hexo-theme-tranquilpeak#360]
I want do something like this:

```
## Brief

1. [Part 1](#1)
2. [Part 2](#2)
3. [Part 3](#3)

<h2 id="1">Part 1</h2>
...
<h2 id="2">Part 2</h2>
...
<h2 id="3">Part 3</h2>
```

Normally, it should work, but it doesn't work with Tranquilpeak. It look like the URL change event gets caught by some js function. 
So how can I make it works properly?

**Comment by LouisBarranqueiro** [comment]
Hey @ajielee, yeah, it should work. It not related to tranquilpeak directly. This is the job of the markdown render module, so which one do you use? the default one? (`hexo-renderer-marked`)

**Comment by ajielee** [comment]
@LouisBarranqueiro Thank you for reply, in fact I've solved this problem, it's just because I did something wrong with CSS.

**Comment by LouisBarranqueiro** [comment]
👍
