### ISSUE TITLE
Google analytics ga.js is deprecated 

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#361]
### Actual behavior

https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/google-analytics.ejs

is using `ga.js` that is now deprecated by google itself

> ga.js is a legacy library. If you are starting a new implementation we recommend you use the latest version of this library, analytics.js. For exisiting implementations, learn how to migrate from ga.js to analytics.js.

https://developers.google.com/analytics/devguides/collection/gajs/

### Expected behavior

Migrate to `analytics.js`

Here two possibility

1. Common way (sync)

```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= theme.google_analytics_id %>', 'auto');
  ga('send', 'pageview');

</script>
```

or using `async` from HTML5 to do not block website (http://caniuse.com/#feat=script-async)

```html
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', '<%= theme.google_analytics_id %>', 'auto');
ga('send', 'pageview');
</script>
<script async src='//www.google-analytics.com/analytics.js'></script>
```

**Comment by jrbenito** [comment]
I would go for async way.

**Comment by kakawait** [comment]
On my fork I set `async` as default but configuration to allow switch if your user target is using old browser that do not support `async`

PS: You can check your user browser in google analytics, great news :)

**Comment by LouisBarranqueiro** [comment]
let's use the first one, PR please :)
