### ISSUE TITLE
how to configure algolia

### ISSUE THREAD

**Issue by selfmaking** [LouisBarranqueiro/hexo-theme-tranquilpeak#364]
I'am chinese ,my English is not very well.If i make some mistakes, forgive me.
I have a issues, I can't use algolia.
My steps is:
1.npm install hexo-algoliasearch --save 
2.configure 
algolia:
  appId: "****"
  apiKey: "***"
  adminApiKey: "****"
  chunkSize: 5000
  indexName: "****"
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip
in _config.yml
3.Run hexo algolia

but when I click search button, no response
only
<img width="331" alt="2016-12-19 5 22 20" src="https://cloud.githubusercontent.com/assets/21097577/21307268/b980d398-c60f-11e6-97ee-4491297b3a6e.png">

can you tell me what can I do.
thanks.

**Comment by talipovdaniyar** [comment]
@selfmaking you have to create an account on https://www.algolia.com/. There is a free hacker subscription. Once your account is created you will find the needed api keys to complete the configuration.

PS: Make sure you have the 1.9.x release of tranquilpeak.

**Comment by selfmaking** [comment]
@talipovdaniyar I already have a account on algolia., and I make sure the tranquilpeak version is 1.9.x. so I don't know what I mistake.

**Comment by talipovdaniyar** [comment]
@selfmaking could you show the configuration of your _config.yml (theme)?

**Comment by selfmaking** [comment]
@talipovdaniyar this?
algolia:
  applicationID: '0LQ6KO4WJH'
  apiKey: 'e0f2957c790694a27331476051b03412'
  adminApiKey: '4e018288a74837235ee336ba61bf929e'
  indexName: 'selfmaking'
  chunkSize: 5000
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip

**Comment by talipovdaniyar** [comment]
@selfmaking  No, the theme config file.

**Comment by selfmaking** [comment]
@talipovdaniyar 

# Tranquilpeak
# Version : 1.9.1
# Author : Louis Barranqueiro

# I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.

# If you want to store images yourself, please read this guidelines:
# For users, if you only use this theme, put your images directly in `source/assets/images` folder
# But if you want to add local images, you can put your images directly in `source/assets/images` folder
# For developpers, if you modify this theme, put your images in `source/_images` folder and
# use grunt task `build` to synchronize assets


# Image directory (default: images)
image_dir: assets/images


# Sidebar Configuration
#    You can add groups of links and links much as you want
#    You just have to respect the indentation : `groups of links` -> `link` -> `title, link, icon`
#    E.g:
#    -------------
#    sidebar:                   # DON'T modify this variable name
#         menu:                 # Name of your groups of links (changeable)
#             home:             # Name of your link (changeable)
#                title: Home    # Title of your link displayed
#                url: /         # URL of the link. If the URL is internal, domain name is not necessary
#                icon: home     # Name of the font awesome icon class without the `fa-`
#                               # Go to http://fontawesome.io/icons/ to find class name of icon
sidebar:
    menu:
        home:
            title: global.home
            url: /
            icon: home
        categories:
            title: global.categories
            url: /all-categories
            icon: bookmark
        tags:
            title: global.tags
            url: /all-tags
            icon: tags
        archives:
            title: global.archives
            url: /all-archives
            icon: archive
        search:
            title: global.search
            url: /#search
            icon: search
            # `open-algolia-search` classes are used to open algolia search modal
            class: open-algolia-search
        about:
            title: global.about
            url: /#about
            icon: question
    author_links:
         github:
             title: global.github
             url: https://github.com/selfmaking
             icon: github
        # stack_overflow:
        #     title: global.stack_overflow
        #     url: http://stackoverflow.com/users
        #     icon: stack-overflow
        # twitter:
        #     title: global.twitter
        #     url: https://twitter.com/
        #     icon: twitter
        # facebook:
        #     title: global.facebook
        #     url: https://facebook.com/
        #     icon: facebook
        # google_plus:
        #     title: global.google_plus
        #     url: https://plus.google.com/
        #     icon: google-plus
        # linked_in:
        #     title: global.linkedin
        #     url: https://www.linkedin.com/profile/
        #     icon: linkedin
        # mail:
        #     title: global.mail
        #     url: mailto:
        #     icon: envelope-o
    rss:
        rss:
            title: global.rss
            url: /atom.xml
            icon: rss


# Header configuration
# The link at the right of the header is customizable
# You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
# By default, author's gravatar or author's picture is displayed if `icon` is empty
# DON'T edit `header`, `right_link`, `url`, `icon` and `class` variable name
# E.g to display a shortcut to open algolia search window :
#     url: /#search
#     icon: search
#     class: open-algolia-search
header:
    right_link:
        url: /#about
        icon:
        class:


# Author
# Your biography and your job is editable in each languages files in `languages` folder
author:
    email:
    location: 上海
    # Your profile picture located in folder `source/_images/` (development)
    # or in `source/assets/images/` (production)
    # or you can use an external url
    # Overwritten by your gravatar image if `gravatar_email` is filled
    picture: headerpic.png
    # Your Twitter username without the @. E.g : `tranquilpeak`
    twitter:
    # Your personal google plus profile id, not your blog or business page id.
    # E.g : `+JohnDoe` or `123812884128439`
    google_plus:
    # Your businnes google plus profile id. If not provided, personal will be used instead.
    # E.g : `+Tranquilpeak` or `123812884128439`
    google_plus_business:


# Customization
# Define the behavior of the sidebar
# 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
# medium sidebar on medium screen and header bar on small screen and
# extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
# 2: Display large sidebar on large screen, medium sidebar on medium screen and
# header bar on small screen and large sidebar is swiped
# 3: Display medium sidebar on large and medium screen and header bar on small screen and
# medium sidebar is swiped
# 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
# large sidebar is swiped on all lower screens
# 5: Display header bar on all screens and large sidebar is swiped on large screen
# 6: Display header bar on all screens and medium sidebar is swiped
sidebar_behavior: 1
# Hide sidebar on all article page to let article take full width to improve reading, and
# enjoy wide images and cover images. (true: enable, false: disable)
clear_reading: true
# Display thumbnail image of each post on index pages (false: disabled, true: enabled)
thumbnail_image: true
# Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
# Set this value to `right` if you have old posts to keep the old style on them
# and define `thumbnailImagePosition` on a post to overwrite this setting
thumbnail_image_position: right
# Automatically select the cover image or the first photo from the gallery of a post if
# there is no thumbnail image as the thumbnail image
# Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
# and set `autoThumbnailImage` to `false` on a post to overwrite this setting
auto_thumbnail_image: false
# Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
# There is many free CDN like Cloudinary or you can also use indirectly
# by using services like Google Photos.
# Current image is on AWS S3 and delivered by AWS CloudFront.
# Otherwise put your image in folder `source/_images/` (development)
# or in `source/assets/images/` if you can't or don't want to build the theme,
# and use relative url : `your-image.png`
cover_image: cover.jpg
# Your favicon located in folder `source/_images/` (development) or in `source/assets/images/` (production)
favicon: favicon.jpg
# Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
image_gallery: false
# Pagination behavior of archive, category and tag pages (false: pagination disabled, true: pagination enabled)
archive_pagination: true
category_pagination: true
tag_pagination: true


# Integrated services
# You can't use Disqus and Duoshuo together
# then fill the right shortname
# Your Disqus shortname
disqus_shortname:
# Your Duoshuo shortname
duoshuo_shortname: selfmaking
# Your Google analystics web property ID : UA-XXXXX-X
google_analytics_id:
# Your Baidu analystics web property ID : 9505a5af654a2478f93fd6c0ae4f687d
baidu_analytics_id:
# Your Gravatar email. Overwrite `author.picture` everywhere in the blog
gravatar_email:
# Your Facebook user ids used to connect your blog with your facebook user accounts (Facebook Insights). Separate ids with comma. e.g : 9830047,1003342
fb_admin_ids:
# Your Facebook app id used to connect your blog with your facebook app account (Facebook Insights). E.g : 9841307
fb_app_id:
    
algolia:
  applicationID: '0LQ6KO4WJH'
  apiKey: 'e0f2957c790694a27331476051b03412'
  adminApiKey: '4e018288a74837235ee336ba61bf929e'
  indexName: 'selfmaking'
  chunkSize: 5000
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip

**Comment by selfmaking** [comment]
@talipovdaniyar 

[_config.docx](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/667798/_config.docx)

**Comment by talipovdaniyar** [comment]
@selfmaking Everything seems legit. Did you execute the 'hexo algolia' command for indexing your posts? npm -> https://www.npmjs.com/package/hexo-algolia

If yes, what is the cli output?

**Comment by selfmaking** [comment]
yes, I found a error.
<img width="644" alt="2016-12-25 12 54 11" src="https://cloud.githubusercontent.com/assets/21097577/21469776/a53afcd8-caa1-11e6-8618-2f3f491f3043.png">
<img width="643" alt="2016-12-25 12 54 25" src="https://cloud.githubusercontent.com/assets/21097577/21469777/a72226f2-caa1-11e6-9958-d63085289a9f.png">

**Comment by talipovdaniyar** [comment]
@selfmaking ok 👍 let me know if you need help!

**Comment by selfmaking** [comment]
@talipovdaniyar Ah....but I don't have solutions, how to work out. can you give me some advice.thanks

**Comment by LouisBarranqueiro** [comment]
hey @selfmaking , please give us all information asked to create an issue, it will be easier to help you

**Comment by selfmaking** [comment]
@LouisBarranqueiro hi,when I execute the 'hexo algolia' command, a error be found.

![](https://cloud.githubusercontent.com/assets/21097577/21469776/a53afcd8-caa1-11e6-8618-2f3f491f3043.png)

![](https://cloud.githubusercontent.com/assets/21097577/21469777/a72226f2-caa1-11e6-9958-d63085289a9f.png)

This is screenshot,can you give me some advice.thanks

**Comment by talipovdaniyar** [comment]
@selfmaking move the Algolia configurations from the theme _config to the main _config.

**Comment by selfmaking** [comment]
@talipovdaniyar the Algolia configurations is already in main _config, but error is also exist

**Comment by talipovdaniyar** [comment]
@selfmaking could you send your main config then.

**Comment by selfmaking** [comment]
@talipovdaniyar 
<img width="723" alt="2017-01-04 8 27 38" src="https://cloud.githubusercontent.com/assets/21097577/21642296/4165dcbe-d2bc-11e6-9ee3-1d64baedf9cf.png">
I used to send you

**Comment by LouisBarranqueiro** [comment]
@selfmaking I closed this issue because it is a bit messy, we still don't have information asked. So please create a new issue and provide all information asked to report a bug (just follow the template)

```
<!-- use this template only to report a bug or ask a question -->
<!-- fill this part for bugs reporting or questions -->
### Configuration

 - **Operating system with version** : 
 - **Node version** : 
 - **Hexo version** : 
 - **Hexo-cli version** : 
 - **Tranquilpeak version** : <!-- Does the theme is original or modified? -->
 
<!-- fill this part for bugs reporting if needed  -->
### Actual behavior

<!-- fill this part for bugs reporting if needed  -->
### Expected behavior

<!-- fill this part for bugs reporting if needed -->
### Steps to reproduce the behavior
```

Also provide your main config -  just copy it in the issue or give us a .txt or an .yml please
