### ISSUE TITLE
social link share options

### ISSUE THREAD

**Issue by antonioaguilar** [LouisBarranqueiro/hexo-theme-tranquilpeak#365]
Hi Louis,
I'm wondering if the ```share_options``` feature is available in Tranquilpeak 1.8.0? I'm having some problems trying to add the LinkedIn share url. My blog posts title and content is not picked up correctly by LinkedIn. 
Below is the HTML template I'm using in the ```actions.ejs``` file:

```html
        <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="<%= 'https://www.linkedin.com/shareArticle?mini=true&url=' + post.permalink %>">
                <i class="fa fa-linkedin-square "></i>
            </a>
        </li>
```

This is the HMTL in the ```share-options.ejs``` file:

```html
        <li class="share-option">
            <a class="share-option-btn" target="new" href="<%= 'https://www.linkedin.com/shareArticle?mini=true&url=' + post.permalink %>">
                <i class="fa fa-linkedin-square"></i><span><%= __('global.share_on_linkedin') %></span>
            </a>
        </li>
```

Any suggestions or ideas?

thanks!

**Comment by LouisBarranqueiro** [comment]
Hey @antonioaguilar , the sharing option feature will be released in some days. I was so busy during the last month so I didn't had time to finish it. Stay tuned.

About your code: If the title and content is not picked up correctly by LinkedIn, check in their doc how do they pickup them and then, update your code. I'm gonna check it out too.
