### ISSUE TITLE
The Internet Explorer can't display correctly the side bar, if _config.yml sidebar_behavior key value is 1.

### ISSUE THREAD

**Issue by YoshinoriN** [LouisBarranqueiro/hexo-theme-tranquilpeak#366]
Hello.
I found that the IE can't display correctly the side bar,  if _config.yml sidebar_behavior key value is 1.

### Configuration

 - **Tranquilpeak version** : 1.9.1 or 1.10.0 modified
 - **Browser** : IE 11
 

### Actual behavior

The side bar's scroll bar are overlapped. 

![ie](https://cloud.githubusercontent.com/assets/11273093/21586272/6754b2e8-d112-11e6-950c-2e146e5003e3.png)

I don't tried other version of IE.
The Chrome and Edge are no problem.

Thanks.

**Comment by LouisBarranqueiro** [comment]
Hey @YoshinoriN, I thing it is the same issue: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/333

**Comment by YoshinoriN** [comment]
oh...it's very sorry. 
I didn't notice it.

**Comment by LouisBarranqueiro** [comment]
it's ok man :D stay tuned, i'm gonna release the new version in some days :)
