### ISSUE TITLE
support multi-languages in Tranquilpeak theme

### ISSUE THREAD

**Issue by araczkowski** [LouisBarranqueiro/hexo-theme-tranquilpeak#367]
We can read in the docs that:
**Tranquilpeak theme is currently not ready to support multi-languages. It will be in a next release.**

I would like to ask about the plans to implement this feature? Maybe I can help somehow?

Thx
Andrzej

**Comment by LouisBarranqueiro** [comment]
Hey man,

Give me some days, I'm gonna define all the steps for. Let do this here :)

**Comment by LouisBarranqueiro** [comment]
A good start would be to update the index page template (`layout/partial/index.ejs`) and filter posts with the current language defined in the `index.md` page. 
- `en/index.md` display on english posts
- `fr/index.md` display on french posts

in front-matter of each page, there is the current language (`page.lang`):
```
---
lang: fr
---
```

See more how to structure pages here: https://hexo.io/docs/internationalization.html

**Comment by araczkowski** [comment]
Hi @LouisBarranqueiro 

I started pull request #393 

I need a hand with:
> but how to generate index for the second language?
> currently when I go to host:port/pl/index.html
> I have 404

all details in pull request

**Comment by LouisBarranqueiro** [comment]
really bad news, we can't generate pages of posts in multiple languages... i18n feature is only available for orphans pages and not for the page/post system.

Let's re-open it when Hexo supports i18n for page/posts system.

**Comment by noraj1337** [comment]
I think we may do something with those plugins:

https://github.com/Jamling/hexo-generator-i18n
https://github.com/xcatliu/hexo-generator-index-i18n
https://github.com/polo2ro/hexo-helper-page-languages
