### ISSUE TITLE
An error about algolia

### ISSUE THREAD

**Issue by selfmaking** [LouisBarranqueiro/hexo-theme-tranquilpeak#368]
### Configuration

 - **Operating system with version** : mac os 10.12
 - **Node version** : node js v6.9.1
 - **Hexo version** : 3.2.2
 - **Hexo-cli version** : 1.0.2
 - **hexo-algolia** : 0.1.1
 - **hexo-algoliasearch**: 0.2.1
 - **Tranquilpeak version** : 1.9.1 original

when I run "hexo algolia"
<img width="829" alt="2017-01-05 9 27 01" src="https://cloud.githubusercontent.com/assets/21097577/21665863/3690e212-d329-11e6-93bb-6b8ff523a00c.png">

and when I clicked search button, there is no response

**Comment by LouisBarranqueiro** [comment]
Hey  @selfmaking . thanks for re-creating the issue.

The error say that you didn't provide an application ID. The problem should come from your configuration file. Copy your main `_config.yml` please

**Comment by selfmaking** [comment]
@LouisBarranqueiro 
[_config.txt](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/686622/_config.txt)

**Comment by LouisBarranqueiro** [comment]
you did a mistake in your configuration.

replace `applicationID` by `appId`.

``` y;l
algolia:
  appId: "Z7A3XW4R2I" // here
  apiKey: "12db1ad54372045549ef465881c17e743"
  adminApiKey: "40321c7c207e7f73b63a19aa24c4761b"
  chunkSize: 5000
  indexName: "my-hexo-blog"
  fields:
    - title
    - tags
    - slug
    - excerpt
    - excerpt:strip
    - photos
    - gallery
```

**Comment by selfmaking** [comment]
@LouisBarranqueiro thank you very much ,it work.
when I run `hexo algolia` 
<img width="930" alt="2017-01-05 3 43 07" src="https://cloud.githubusercontent.com/assets/21097577/21672452/aea67db4-d35d-11e6-819d-b6c0c0658cf1.png">
but the algolia plugin can popping.
<img width="744" alt="2017-01-05 3 41 55" src="https://cloud.githubusercontent.com/assets/21097577/21672547/20a3a00e-d35e-11e6-8c56-ffc57a65b831.png">
but the layout looks weird
and when I input keyword, it doesn't work.

**Comment by LouisBarranqueiro** [comment]
1. as it said. you reach the max number of operations for this month. Check [Hacker plan](https://www.algolia.com/pricing?utm_source=google&utm_medium=cpc&utm_campaign=search-branded&creative=166549143286&network=g&device=c&gclid=CNCAu8HFqtECFUWfGwodxmsN8w) 

2. It can pop even if you exceeded max limit but search will not works.

**Comment by LouisBarranqueiro** [comment]
Go check usage on your account to see what going on

**Comment by selfmaking** [comment]
@LouisBarranqueiro my mistake, algolia need renewal every month. thanks.
now, when I run`hexo algolia`
 
<img width="415" alt="2017-01-06 9 56 52" src="https://cloud.githubusercontent.com/assets/21097577/21704784/7b900f6e-d3f6-11e6-9180-3fee40f5ce56.png">

 always 0 post indexed, I don't know why

**Comment by selfmaking** [comment]
@LouisBarranqueiro I have already solved, thanks for your help.

**Comment by LouisBarranqueiro** [comment]
your welcome :)

**Comment by PeoceWang** [comment]
@selfmaking I wonder how to solve 0 post indexed problem ???

**Comment by selfmaking** [comment]
@PeoceWang run `hexo clean` and 'hexo g',I just clean cache, you can try

**Comment by PeoceWang** [comment]
@selfmaking Tks, I found my solution. 
Just execute `hexo algolia`  && `hexo d` Instead of  `hexo g`  &&  `hexo algolia` && `hexo d `.

**Comment by selfmaking** [comment]
@LouisBarranqueiro Maybe 'hexo g' should behind 'hexo algolia'

**Comment by PeoceWang** [comment]
@selfmaking In my PC ' hexo g ' is not necessarily
(' hexo algolia') = ( 'hexo algolia' + 'hexo g')

**Comment by selfmaking** [comment]
@LouisBarranqueiro I just tried it on, when I run `hexo algolia` also can create html files. so maybe it include `hexo g`

**Comment by LouisBarranqueiro** [comment]
what's the problem?

**Comment by PeoceWang** [comment]
@LouisBarranqueiro You may should modify official documentation, cause ' hexo g ' is not necessarily after ' hexo algolia ' , And what' worse is if I run ' hexo algolia ' after ' hexo g ' , IT CAN NOT GENERATE INDEX !!!

**Comment by LouisBarranqueiro** [comment]
this is not related to the theme. open an issue on the hexo-algolia repository.

**Comment by skout90** [comment]
@PeoceWang Thanks!! you save my time!
