### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by darekkay** [LouisBarranqueiro/hexo-theme-tranquilpeak#371]
Hi Louis, thank you very much for this wonderful theme :) I've been using it for a while on my blog and I would be happy to see it in your showcase:

https://darekkay.com

Is this showcase already available somewhere?

**Comment by LouisBarranqueiro** [comment]
Hey buddy, Happy to hear that. :) Not yet, I'm gonna list them in a wiki.
