### ISSUE TITLE
How to make my blog just like your demo

### ISSUE THREAD

**Issue by AudienceX** [LouisBarranqueiro/hexo-theme-tranquilpeak#372]
Hi guy~Thanks for your theme and I like it very much . So I want to make my blog just like your demo.  And could you please tell me how ? Maybe you can show me your code and I can help myself.

**Comment by LouisBarranqueiro** [comment]
Hey @xenglog, Glad to hear that. :) what do you mean by "just like your demo"?

**Comment by xenglog** [comment]
@LouisBarranqueiro like this [demo](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/) ,I want each article shows two lines abstract with the link named "Continue reading"  and right picture . Also I like the effect of first article , "Welcome to Tranquilpeak 1.9". So can you tell me how to set it :-P  Maybe my poor English drivies you mad hahhh~~~

**Comment by LouisBarranqueiro** [comment]
You just have to install the theme 😄 
and read https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#front-matter-settings to define thumbnail position and excerpt

**Comment by xenglog** [comment]
I've just pay attention to the file "developer.md" but forgot to read the file "user.md"......Thanks for your help~~~~~ XD
