### ISSUE TITLE
Some question about Markdown Preview

### ISSUE THREAD

**Issue by AudienceX** [LouisBarranqueiro/hexo-theme-tranquilpeak#373]
I hope I'm not disturbing you because what I want to know maybe has nothing to do with your theme :P

Could you please tell me how to change the font of Markdown Preview...

I've changed `_variables.scss` file , but it can only influence the content of post. The tittle is also using default font  ...

The same problem happens when I use `Atom` and try to set my own background or font previewing Markdown file.

I try to find answer in Google but don't know how to search... OK I can't deal with it...

So do you know how to fixed it ?

**Comment by LouisBarranqueiro** [comment]
Hey @xenglog,  what is the markdown preview?

**Comment by xenglog** [comment]
I mean that we write blog using Markdown  Grammar, it looks like this
```
# **Tittle**
> Here is content.
```

And when previewing , it looks like

#  **Tittle**
> Here is content.

I want to change the font of preview results that we finally see. But I don't how where to set

**Comment by LouisBarranqueiro** [comment]
in `_variables.scss` as you said, but don't forget to re-build the theme. read developer doc to learn how to do that : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#register-tasks

**Comment by LouisBarranqueiro** [comment]
Hey @AudienceX, is it fixed?

**Comment by AudienceX** [comment]
@LouisBarranqueiro Yes, And then I found a easier way to do this. I modify `font-family` Tags in `\tranquilpeak\source\assets\css\tranquilpeak.css`  and save without compile. It works. 

＜（￣︶￣）＞

**Comment by LouisBarranqueiro** [comment]
yes because you are directly editing the compiled file but if you recompile the theme, you will loose your modifications. That's why I recommend you to modify the source.

**Comment by AudienceX** [comment]
@LouisBarranqueiro  (づ ￣ ³￣)づ   I‘m sure I won't recompile  the theme. I just want to edit some simply attribute. For me, editing the compiled file is enough. Anyway, thanks for your tips.  (^-^)
