### ISSUE TITLE
How to remove post-actions-wrap module

### ISSUE THREAD

**Issue by AudienceX** [LouisBarranqueiro/hexo-theme-tranquilpeak#376]
Hi, I want to remove a module which is maybe named post-actions-wrap... 

It contains `PREVIOUS` button, `NEXT` button,  `Return Top` , `Twitter`, `Facebook` and `Google` . Only  when Sliding up, it will show.

Setting `post-actions-wrap` Tag's `background` will influence it.

So could you please to me how to remove it ?

(God bless that you can understand what module I am talking about  :P  )

**Comment by LouisBarranqueiro** [comment]
Hey @AudienceX, remove these lines and it should be good: 
- https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/post.ejs#L43
- https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/layout.ejs#L28-L33

Thanks for using this theme! :)
