### ISSUE TITLE
Wrong open graph image url

### ISSUE THREAD

**Issue by kilik52** [LouisBarranqueiro/hexo-theme-tranquilpeak#379]
### Configuration

 - **Operating system with version** :   maxosX
 - **Node version** :  v6.9.5
 - **Hexo version** :  newest
 - **Hexo-cli version** :  1.0.2
 - **Tranquilpeak version** : original 1.9.1
 

### Actual behavior
Wrong Tag:

````
<meta property="og:image" content="https://kilik52.github.io/01.png">
````

### Expected behavior  
Expected Tag:
````
<meta property="og:image" content="https://kilik52.github.io/2017/02/14/CentralLimitTheorem/01.png">
````

### Steps to reproduce the behavior
When i add an image in the main content of my article using relative path:
````
![Image 01](01.png)
````

It will generate the wrong url in open graph tag.

**Comment by LouisBarranqueiro** [comment]
Hey @kilik52, this job handled by Hexo, report this issue on their repository. Tranquilpeak only generate path for post: photos, gallery, cover image, thumbnail image. All image urls inserted in the body of the post are handled by Hexo.
