### ISSUE TITLE
Add a Bio| Resume post 

### ISSUE THREAD

**Issue by gauthamzz** [LouisBarranqueiro/hexo-theme-tranquilpeak#381]
It would be nice to have a bio post which is visible in the sidebar. 
The about page is very simple. It would be great if we could show the resume of a person .

Can you tell me how i can start doing this ?
Thanks for developing this :+1:

**Comment by LouisBarranqueiro** [comment]
Hey @gauthamzz, this theme is focused on blogging, I don't wanna add feature like this. What you can do is to create a page for your resume and add the link in the sidebar. :)
