### ISSUE TITLE
How to display thumbnail image on the top of title in index pages?

### ISSUE THREAD

**Issue by lvyuannaonao** [LouisBarranqueiro/hexo-theme-tranquilpeak#382]
How to display the thumbnail image on the top of title in index pages?

**Comment by lvyuannaonao** [comment]
How to display the thumbnail image on the top of title in index pages?

**Comment by LouisBarranqueiro** [comment]
Hey @lvyuannaonao , you can define thumbnail position in the front matter of your post. See more here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#customization
