### ISSUE TITLE
Question: could not find a way to create the gallery in a grid view

### ISSUE THREAD

**Issue by ZhaoC** [LouisBarranqueiro/hexo-theme-tranquilpeak#383]
Unable to create a gallery as you implemented in [your demo](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2014/10/29/Tags-plugins-showcase/#Image) 
### Actual behavior

code :
```
{% image fancybox fig-33 clear group:plants flower1.jpg 200px  "flower" %}
{% image fancybox fig-33 clear group:plants flower2.jpg  200px "flower" %}
```
image layout:
![screenshot](https://cloud.githubusercontent.com/assets/8210826/23638077/6d34de5a-02ad-11e7-86aa-de94c37450e8.png)

### Expected behavior
do I need to customize the layout in css file or i can implement it by adding properties in the image tag. expected to display the images in a grid view like this:
![grid view](https://cloud.githubusercontent.com/assets/8210826/23638124/a7d9f28e-02ad-11e7-9b29-39cb7ab38606.png)

**Comment by LouisBarranqueiro** [comment]
Hey @ZhaoC, you have to activate in the in the front matter of your post. Read more here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#customization
