### ISSUE TITLE
Error on Latest ubuntu

### ISSUE THREAD

**Issue by Volem** [LouisBarranqueiro/hexo-theme-tranquilpeak#384]
Downloaded the user version and trying to rebuild with new font, but getting an error when running hexo after installing necessary npm packages. I revert the changes and the problem gone. Even with the original version - meaning w/o changing the font or anything, after installing packages hexo gets error as below.

`Mar 08 07:32:39 ip-172-31-36-176 hexo[15670]: INFO  Start processing
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]: FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]: Error: watch /home/ubuntu/blog/meblogging/themes/tranquilpeak/node_modules/es5-ext/number/#/index.js ENOSPC
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at exports._errnoException (util.js:1022:11)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at FSWatcher.start (fs.js:1429:19)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at Object.fs.watch (fs.js:1456:11)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at createFsWatchInstance (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:37:15)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at setFsWatchListener (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:80:15)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:228:14)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at FSWatcher.NodeFsHandler._handleFile (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:255:21)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at FSWatcher.<anonymous> (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:473:21)
Mar 08 07:32:50 ip-172-31-36-176 hexo[15670]:     at FSReqWrap.oncomplete (fs.js:123:15)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]: FATAL watch /home/ubuntu/blog/meblogging/themes/tranquilpeak/node_modules/es5-ext/number/#/index.js ENOSPC
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]: Error: watch /home/ubuntu/blog/meblogging/themes/tranquilpeak/node_modules/es5-ext/number/#/index.js ENOSPC
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at exports._errnoException (util.js:1022:11)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at FSWatcher.start (fs.js:1429:19)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at Object.fs.watch (fs.js:1456:11)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at createFsWatchInstance (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:37:15)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at setFsWatchListener (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:80:15)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:228:14)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at FSWatcher.NodeFsHandler._handleFile (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:255:21)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at FSWatcher.<anonymous> (/home/ubuntu/blog/meblogging/node_modules/chokidar/lib/nodefs-handler.js:473:21)
Mar 08 07:32:51 ip-172-31-36-176 hexo[15670]:     at FSReqWrap.oncomplete (fs.js:123:15)`

 - **Operating system with version** :  Ubuntu 16.04.2 LTS
 - **Node version** :  v6.10.0
 - **Hexo version** :  3.2.2
 - **Hexo-cli version** :  1.0.2
 - **Tranquilpeak version** : 1.9.1
 

Getting an error when starting hexo after installing npm packages and npm run prod.

Run as it was before installing npm packages

Download user version, install npm packages.

**Comment by YoshinoriN** [comment]
@Volem
Perhaps, I think this problem will be solved below way.

[ENOSPC Error (Linux)](//hexo.io/docs/troubleshooting.html#ENOSPC-Error-Linux)

**Comment by Volem** [comment]
Let me try that and retur back here

**Comment by Volem** [comment]
Thanks for pointing me the direction. Now it's ok
