### ISSUE TITLE
how to create the link like your article "Hexo websites"

### ISSUE THREAD

**Issue by vinurs** [LouisBarranqueiro/hexo-theme-tranquilpeak#385]
I want to create a post like the aritile " Hexo websites" in your https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/, the title link to the hexo web site, How can i do ?
thanks for your help.

**Comment by LouisBarranqueiro** [comment]
Hi @vinurs , you can check the source of all of the demo here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/tree/source-blog-posts/source/_posts

Here is the code of the link post:
```
---
title: Hexo website
date: 2012-04-12 23:33:26
link: http://www.hexo.io/
categories:
- tranquilpeak
- features
thumbnailImagePosition: left
thumbnailImage: http://d1u9biwaxjngwg.cloudfront.net/hexo-website/peak-140.jpg
---
This is a link post. Clicking on the link should open [Hexo](http://www.hexo.io/) in a new tab or window.
<!-- more -->
```

**Comment by vinurs** [comment]
@LouisBarranqueiro thanks , It works ok.
