### ISSUE TITLE
Feature Request: Interactive Charts

### ISSUE THREAD

**Issue by kilik52** [LouisBarranqueiro/hexo-theme-tranquilpeak#386]
Hi, Thank your for this great theme. Any plans to add any interactive charts support?

**Comment by LouisBarranqueiro** [comment]
Hi @kilik52, I didn't plan to a a feature about charts but what do you mean exactly?

**Comment by kilik52** [comment]
Some JS library like [chart.js](http://www.chartjs.org)

**Comment by LouisBarranqueiro** [comment]
ok, but what do you want to do with it?

**Comment by kilik52** [comment]
Write articles which have interactive charts. Like this:

http://www.tylervigen.com/spurious-correlations

**Comment by LouisBarranqueiro** [comment]
It's a really specific use cases and a big feature to implement. I recommend you to use an  external services which allow you to embed your chart in your blog post.
