### ISSUE TITLE
How to justify text on the post content?

### ISSUE THREAD

**Issue by ashatkerimov** [LouisBarranqueiro/hexo-theme-tranquilpeak#388]
I am new to hexo. I tried to edit style.css and tranquipeak.css files, but there was no success.

**Comment by LouisBarranqueiro** [comment]
Hi @ashatkerimov, if you are new to Hexo and wanna modify the theme, I recommend you to carefully read related section of user and developer documentation to understand how the theme is build and how to see changes. You can start here: [Quick & easy-modifications](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#quick--easy-modifications)

**Comment by ashatkerimov** [comment]
Thank you.
