### ISSUE TITLE
how to display biography on the index page?

### ISSUE THREAD

**Issue by SimmerChan** [LouisBarranqueiro/hexo-theme-tranquilpeak#389]
I set the variable sidebar_behavior to 1, but the sidebar seems to be still quite narrow. I want to put the menu and author_links at two columns with biography displayed below the avatar and name just like what your page shows. Otherwise, how can I use \<h\> tag on name just like yours(with \<h4\> tag)?  Thanks!
![1](https://cloud.githubusercontent.com/assets/7333516/23831195/2942ebca-0757-11e7-84d8-ef4d61b3e9e6.jpg)
![2](https://cloud.githubusercontent.com/assets/7333516/23831194/28ffc7f0-0757-11e7-8000-751dafefe761.jpg)

**Comment by LouisBarranqueiro** [comment]
Hey @SimmerChan,  make sure you have the latest version of the theme and the window is larger than 1280. :)

**Comment by SimmerChan** [comment]
It's solved after I update it to the latest version. By the way, the download link in user.md links to version 1.8.0.   THX!!
