### ISSUE TITLE
Why not use something like Transifex to manage localization?

### ISSUE THREAD

**Issue by jrbenito** [LouisBarranqueiro/hexo-theme-tranquilpeak#397]
Hi,

Every time we need to add new localized terms it is boring and time consuming  to copy and paste terms from en.yml file to all other languages available. Every time a new term is added, original translators for languages are not notified to revise translations (that are most done by Google Translator), this sometimes leads to poor quality translations. Every new language file added makes this workload grows.

How about make use of something like [Transifex](https://www.transifex.com/)? It tracks modifications and is able to propagate it among language files, translators who subscribe to the project can be notified and translate english/french terms added. New files translated can be directly brought to Github repo and sent to Transifex by hand or there is [integration alternative](https://docs.transifex.com/integrations/github/).

I think this can improve the quality and maintainability of localization files with little to no extra effort. What do you think about?

**Comment by jrbenito** [comment]
While what I wrote above is true, I didn´t realized that Transifex has no free option. This because I use it to translate an app from another guy (who might pay it). However, there are other options out there... anyway, forget about Transifex.

**Comment by LouisBarranqueiro** [comment]
Hey @jrbenito, we almost never change the language files so it would be useless to spend more time to setup transiflex for this project that it take to update the language files when we need it.
