### ISSUE TITLE
Duoshuo comment service is closing

### ISSUE THREAD

**Issue by ttimasdf** [LouisBarranqueiro/hexo-theme-tranquilpeak#401]
Said to be closed completely on 6/1/17,official announcement(Chinese) [here](http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241)

Related code can be cleansed, maybe?

**Comment by LouisBarranqueiro** [comment]
Hi @ttimasdf, yeah we can remove the code when the service will be closed.
