### ISSUE TITLE
When is the next release of tranquilpeak?

### ISSUE THREAD

**Issue by antonioaguilar** [LouisBarranqueiro/hexo-theme-tranquilpeak#402]
Congrats for this great looking hexo template! Just wondering when is the next release of tranquilpeak plan for? It will be nice to benefit from some the bug fixes ;-)

**Comment by LouisBarranqueiro** [comment]
Hey @antonioaguilar, I'll do the my best to release it today :)

**Comment by antonioaguilar** [comment]
No rush @LouisBarranqueiro - I just wanted to get a general idea how often you are releasing. Let me know if you need some help testing the release.
