### ISSUE TITLE
Hexo doesn't show the tranquilpeak good

### ISSUE THREAD

**Issue by moeinroid** [LouisBarranqueiro/hexo-theme-tranquilpeak#406]
Hi i use tranquilpeak in my hexo blog , but it seams css didn't load.
![screenshot](http://uupload.ir/files/54ej_screenshot_from_2017-04-19_16-16-24.png)

**Comment by jrbenito** [comment]
Hi @moeinroid 

You are using development code. Tranquilpeak must be built before use. You have two options:

1. Build the current source you have (see developer documentation on this repository)
1. Download latest version .zip file already built for production.

BRs,
Benito.

**Comment by moeinroid** [comment]
Hi @jrbenito 
I think i built it
With :
`cd themes/tranquilpeak`
`npm install`
`bower install`

**Comment by jrbenito** [comment]
You still need to run
`grunt buildProd` 

after bower.
