### ISSUE TITLE
Add a sticky table of content 

### ISSUE THREAD

**Issue by ghost** [LouisBarranqueiro/hexo-theme-tranquilpeak#410]
now , the toc(table of content) is in the top of the article, I want to add it in the right of the post like this, I tried several times, but failed, I have no knowledge about css.
![image](https://cloud.githubusercontent.com/assets/2130033/25573118/cd18b222-2e74-11e7-9712-3b283b7f5dd3.png)

can anyone give me some tips?

**Comment by LouisBarranqueiro** [comment]
Hi @vinurs , hard to give you some tips here because it requires some work, what I mean is it cannot be done with few css rules. I'm going to think about adding this feature if some other users need it.

**Comment by maligh** [comment]
+1
Hi LouisBarranqueiro, I like your theme very much.Thank you for sharing.
I have the same wish,I want a list of articles which can quickly location to the content in the article.
Thank you for reading my advice and  bear my poor English. :)

**Comment by damarindra** [comment]
+1.
I've tried to make this works, but my knowledge of js and css is poor.
If you want to add this feature, maybe this will be help : https://github.com/forsigner/fexo
I've tried to copy the js, css, and implements the layout, but no help, always return null variable. The structure of your code and fexo is different.

**Comment by LouisBarranqueiro** [comment]
I'm closing this one for now since only a very few people want it.
