### ISSUE TITLE
jQuery not found

### ISSUE THREAD

**Issue by Mr0Null** [LouisBarranqueiro/hexo-theme-tranquilpeak#411]
I have tested even with the latest version, but if I click on the about, the debug console says that

```
Uncaught ReferenceError: jQuery is not defined
    at somejsfile.js:1
```

**Comment by jrbenito** [comment]
Are you using production version (downloaded zip file) or you have cloned the repo? If you cloned git repository you need to build theme first. Read development documentation to find more  about.

**Comment by Mr0Null** [comment]
I have tried with both release and I built it on my own, same results!

**Comment by F1LT3R** [comment]
I can confirm that the build step worked for me. jQuery was found after that.

**Comment by Malalawi1** [comment]
I am having the same issue. Can someone kindly advise?

**Comment by LouisBarranqueiro** [comment]
@Mr0Null @Malalawi1  did you follow these [steps](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#installation) then built the theme?
