### ISSUE TITLE
how to change fade in and fade out speed in about card

### ISSUE THREAD

**Issue by csarron** [LouisBarranqueiro/hexo-theme-tranquilpeak#412]
how to change fade in and fade out speed in about card? I can find the related file is `source/_js/about.js`

**Comment by LouisBarranqueiro** [comment]
Hi @csarron, it can be done by passing the duration to `$elem.fadeIn()` and `$elem.fadeOut()` function. See more here: [.fadeIn()](http://api.jquery.com/fadein/)

Thanks for using this theme :)
