### ISSUE TITLE
Type errors in ejs?

### ISSUE THREAD

**Issue by Malalawi1** [LouisBarranqueiro/hexo-theme-tranquilpeak#414]
### Configuration

 - **Operating system with version** : mac OS Sierra
 - **Node version** : 4.2.0
 - **Hexo version** : hexo: 3.3.7
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** :  1.10.0 (trying to modify, but modification is producing error)
 

So I am trying to fill in the author, email, and location designations in the config.ymd file for the tranquilpeak theme, however, whenever I do that I get the following error message:

`Unhandled rejection TypeError: /Users/XXXX/Desktop/Test/themes/tranquilpeak/layout/layout.ejs:18
    16|     <body>
    17|         <div id="blog">
 >> 18|             <%- partial('_partial/header', {sidebarBehavior: sidebarBehavior}) %>
    19|             <%- partial('_partial/sidebar', {sidebarBehavior: sidebarBehavior}) %>
    20|             <%- partial('_partial/post/header-cover', {post: page, sidebarBehavior: sidebarBehavior}) %>
    21|             <div id="main" data-behavior="<%= sidebarBehavior %>"

/Users/XXXX/Desktop/Test/themes/tranquilpeak/layout/_partial/header.ejs:3
    1| 
    2| <% var authorPicture = null; %>
 >> 3| <% if (!theme.header.right_link.icon) { %>
    4|     <% if (theme.gravatar_email && theme.gravatar_email.length) { %>
    5|         <% authorPicture = gravatar(theme.gravatar_email, 90); %>
    6|     <% } else if (theme.author.picture && theme.author.picture.length) { %>

Cannot read property 'right_link' of undefined
   

(note that I have not played with any .ejs files and do not know why I am getting this error)

**Comment by LouisBarranqueiro** [comment]
Hi @Malalawi1 , you maybe removed this variable: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/_config.yml#L105

Do not delete any lines in this file. 

I advise you to download the theme again and carefully follow the user documentation and developer documentation to do what you need.
