### ISSUE TITLE
put the welcome-post at the top of index page,but the Pagination run incorrectly.

### ISSUE THREAD

**Issue by ihepta** [LouisBarranqueiro/hexo-theme-tranquilpeak#415]
### Configuration

 - **Operating system with version** : win7
 - **Node version** : v6.9.2
 - **Hexo version** : v3.3.7
 - **Hexo-cli version** : v1.0.2
 - **Tranquilpeak version** : v1.8.0
 
hi,Louis
I prefer putting the welcome-post(but this post was generated earliest) at the top of index page,like this
![image](https://user-images.githubusercontent.com/16395060/26865679-5ed80d24-4b90-11e7-9853-76367a51d7c5.png)

and I modified some code in the local file node_modules\hexo-generator-index\lib\generator.js 

from
`var posts = locals.posts.sort(config.index_generator.order_by);`
to
`var posts = locals.posts;
  posts.data = posts.data.sort(function(a, b) {
        if(a.top && b.top) {
            if(a.top == b.top) return b.date - a.date;
            else return b.top - a.top;
        }
        else if(a.top && !b.top) {
            return -1;
        }
        else if(!a.top && b.top) {
            return 1;
        }
        else return b.date - a.date;
    });`

then add the "top: 1" to front-matter settings in my welcome-page.md
definitely it works(the welcome-page displayed at the top),but a new problem appeared,the pagination run incorrectly.when I click the pagination button the posts still in original order(sort by date).
I wonder if your welcome-page in your demo was created at last?
btw,your tranquilpeak theme is so nice  : )

**Comment by LouisBarranqueiro** [comment]
Hey @ihepta, just set a future date for your welcome post like this:
```
date: 2020-12-12
```

Thanks for using this theme :)
