### ISSUE TITLE
page 'archives' is not work while 'all-archives' works

### ISSUE THREAD

**Issue by 839891627** [LouisBarranqueiro/hexo-theme-tranquilpeak#420]
我用 `hexo new page archives`生成并配置后，访问`localhost:4000/archives` 不行，
但是 `hexo new page all-archives`后，访问`localhost:4000/all-archives` 就可以。

不过我还是想配置成 `localhost:4000/archives` 这样的

**Comment by LouisBarranqueiro** [comment]
Hi, `archives` page is already taken by Hexo. It's like a system page. that's why you can't use it.
