### ISSUE TITLE
Error has occurred during clearing index : AlgoliaSearchRequestTimeoutError: Request timedout before getting a response

### ISSUE THREAD

**Issue by kianlai** [LouisBarranqueiro/hexo-theme-tranquilpeak#421]
### Configuration

 - **Operating system with version** :  CentOS 7
 - **Node version** :  v8.1.3
 - **Hexo version** : 3.3.7
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : original, user-version
 

### Actual behavior
[root@localhost hexo]# hexo algolia
(node:11834) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Collecting posts...
INFO  Start processing
INFO  Files loaded in 4.9 s
INFO  Generated: atom.xml
INFO  Generated: all-categories/index.html
INFO  Generated: all-tags/index.html
INFO  Generated: all-archives/index.html
INFO  Generated: 2017/07/01/Learn-Python/index.html
INFO  Generated: 2017/07/01/Install-Hexo-on-CentOS-7/index.html
INFO  Generated: 2017/07/01/Getting-Git-on-CentOS7-Server/index.html
INFO  Generated: 2017/07/01/ABAP-Performance-Analysis/index.html
INFO  Generated: 2017/07/01/Using-Jekyll/index.html
INFO  Generated: 2017/07/01/hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2017/index.html
INFO  Generated: archives/2017/07/index.html
INFO  Generated: index.html
INFO  Generated: assets/fonts/fontawesome-webfont.eot
INFO  Generated: assets/fonts/fontawesome-webfont.woff2
INFO  Generated: assets/images/blank.gif
INFO  Generated: assets/images/fancybox_loading.gif
INFO  Generated: assets/images/fancybox_loading@2x.gif
INFO  Generated: assets/images/fancybox_overlay.png
INFO  Generated: assets/images/fancybox_sprite.png
INFO  Generated: assets/images/fancybox_sprite@2x.png
INFO  Generated: assets/fonts/FontAwesome.otf
INFO  Generated: assets/fonts/fontawesome-webfont.ttf
INFO  Generated: assets/fonts/fontawesome-webfont.woff
INFO  Generated: assets/images/gravatar_email.png
INFO  Generated: assets/css/jquery.fancybox-thumbs.css
INFO  Generated: assets/css/jquery.fancybox.css
INFO  Generated: assets/js/jquery.fancybox-thumbs.js
INFO  Generated: assets/css/font-awesome.css
INFO  Generated: assets/js/jquery.fancybox.js
INFO  Generated: assets/js/tranquilpeak.js
INFO  Generated: assets/css/style-sxklfps8ywgfyyjcowvnb4gxdgt0zjts3hsguljmv9uqanxjbnitrovtbrek.min.css
INFO  Generated: assets/css/tranquilpeak.css
INFO  Generated: assets/js/script-ivwiy10zeb8fifc4swnhkwneuk64y53w2scmdmtp8thi9cqfxh31aowtroaz.min.js
INFO  Generated: assets/css/style.css
INFO  Generated: assets/js/jquery.js
INFO  Generated: assets/js/script.js
INFO  Generated: assets/images/cover.jpg
INFO  Generated: assets/fonts/fontawesome-webfont.svg
INFO  Generated: assets/images/cover-v1.2.0.jpg
INFO  41 files generated in 957 ms
INFO  6 posts collected
INFO  Clearing index on Algolia...
INFO  Error has occurred during clearing index : AlgoliaSearchRequestTimeoutError: Request timedout before getting a response

### Steps to reproduce the behavior
I follow the **User documentation** to configure the file **themes/tranquilpeak/_config.yml**
1. run ```npm install hexo-algoliasearch --save```
2. configure *hexo-algoliaseach* in **themes/tranquilpeak/_config.yml** file
3. run ```hexo algolia```
And then the tips me the above error ~~

**Comment by LouisBarranqueiro** [comment]
Algolia request to clear the index has timed out. that's all, you just need to try again
