### ISSUE TITLE
How can I change the text color inside post

### ISSUE THREAD

**Issue by sunilpatro1985** [LouisBarranqueiro/hexo-theme-tranquilpeak#424]
Hello,

Firstly thanks a lot for the theme.

I want to change the text color in my posts, is there any way I can do?

**Comment by LouisBarranqueiro** [comment]
Hi @sunilpatro1985, you just have to use some html and inline css!
``` html
<span style="color:red;">text-red</span>
```

Thanks for using this them. :)
