### ISSUE TITLE
Change the scss file but nothing changed

### ISSUE THREAD

**Issue by QZQTechMonster** [LouisBarranqueiro/hexo-theme-tranquilpeak#429]
I change something in file '/source/layouts/_about.scss'.
hexo g, hexo s. 
But nothing changed.
Does anyone know why?

**Comment by skout90** [comment]
i typed `grunt buildProd` in transquilpeak folder. then solved

**Comment by LouisBarranqueiro** [comment]
yes, when you modify the static files of the theme (js, css), you have to re-build the theme, read the developer documentation about this: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md#build
