### ISSUE TITLE
Post image URL in Open Graph meta tag

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-theme-tranquilpeak#431]
Hello! I know that the theme author recommends to use CDNs and remote hosts like Google Photos for images. But I'd like to know is there any way to use images in post asset folder with open graph meta tag being correctly generated for them. Does anybody use these folders for post images?

Configuration is:

Site `_config.yml`
```
url: https://domain.org
root: /
permalink: :year/:month/:day/:title/
...
post_asset_folder: true
relative_link: false
```

I use [image tag](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#image) in text of `some-post.md`
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.

{% image post-pic.jpg "Pic caption" %}

Lorem ipsum dolor sit amet, consectetur adipiscing elit.
```

and put image file `post-pic.jpg` into the post asset folder `_posts/some-post`.

It's expected that the open graph meta tag for this image would be
```
<meta property="og:image" content="https://domain.org/year/month/day/some-post/post-pic.jpg">
```

but actually I get this
```
<meta property="og:image" content="https://domain.org/post-pic.jpg">
```

Any thoughts on the problem?

**Comment by LouisBarranqueiro** [comment]
HI, there is no problem, you just need to specify the absolute path of your image.

**Comment by aerohub** [comment]
I do, but thought there is more convenient way. For what I need post asset folder then? May be it's easier then to place all images of all posts in some domain.org/postpics/ folder to have more usable url pattern.

**Comment by aerohub** [comment]
And what I really mean. In [Tranquilpeak docs](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-post-assets-folder) we read:
```
If you want to take advantage of cover image,
thumbnail image, and image gallery features,
you have to enable post assets folder
by setting post_asset_folder to true in _config.yml.
```
and in [Hexo docs](https://hexo.io/docs/asset-folders.html#Post-Asset-Folder) we read:
```
Place all assets related to your post
into the associated folder,
and you will be able to reference them
using a relative path, making for an easier
and more convenient workflow.
```
But in fact we have to specify the absolute path of image. It disorients.

**Comment by LouisBarranqueiro** [comment]
in fact, you have to specify the relative path from the root of your site... It's not really convenient but  `image` is a built in tag of Hexo...

**Comment by aerohub** [comment]
May be some note then&

**Comment by LouisBarranqueiro** [comment]
Not really, because you only have to specify the relative path from the root of your site only when you use the built-in `image` tag and not the other features related to the theme like cover image, thumbnail image, etc...

**Comment by aerohub** [comment]
OK, this may be closed.
