### ISSUE TITLE
After grunt prodBuild ,''<%-'' in script.ejs before  js('asset/js/....') disappears

### ISSUE THREAD

**Issue by ByronHsu** [LouisBarranqueiro/hexo-theme-tranquilpeak#434]
### Configuration

 - **Operating system with version** : macPro ver 10.12.3
 - **Node version** : v8.1.2
 - **Hexo version** : 5.3.0
 - **Hexo-cli version** : 5.3.0
 - **Tranquilpeak version** : 1.10.0 
 

I follow the Installation Instruction  step by step in Developer documentation. After that, however, when I type in ''grunt prodBuild", somethings strange occurs 
[](url)

- script.ejs
```ejs=
<!--SCRIPTS-->
 js('assets/js/script-9xbq8i1975y8wa6wkmgeet6iffucwpkak6vypocvmtkzpg5eczszlhuev9lt.min.js') %>
<!--SCRIPTS END-->
```
- head.ejs
```ejs=
    <!--STYLES-->
     css('assets/css/style-ccfkfxr7kxscht0fmbaolpazdwknkjxef1ukkscbn88hsclg0ox3lu8gt3pf.min.css') %>
    <!--STYLES END-->
```

"<%-" disappears!? I spend several hours but still cannot find the problem. I am a beginner in web-developing , so this question may seem stupid lol. Hope that someone can help me. Thx a lot!!

**Comment by LouisBarranqueiro** [comment]
👋 @ByronHsu, could you please add the output of the console when you run `grunt buildProd` task?
