### ISSUE TITLE
Font Awesome version.

### ISSUE THREAD

**Issue by prajaybasu** [LouisBarranqueiro/hexo-theme-tranquilpeak#437]
### Configuration
 - **Tranquilpeak version** : 1.10.0

I need the Quora icon (it is a popular website). It would be awesome if FA 4.7 is availaibe out of the box for the sidebar icons.

**Comment by wendingp** [comment]
Yeah, same problem with you

**Comment by wendingp** [comment]
And I followed the steps in the developer doc, it updated to 4.6.3 in default building mode, still no quora icon...

**Comment by LouisBarranqueiro** [comment]
👋 . Good idea guys. I'm gonna check this out!

**Comment by LouisBarranqueiro** [comment]
Available in v1.11.0
