### ISSUE TITLE
Math formula rendering problems

### ISSUE THREAD

**Issue by wendingp** [LouisBarranqueiro/hexo-theme-tranquilpeak#441]
I've installed [hexo-math](https://github.com/hexojs/hexo-math). It works in [hexo theme next](https://github.com/iissnan/hexo-theme-next) but when I switch to tranquilpeak, `$...$`, `$$...$$`and math block don't work:
1. It shows $ sign and normal texts when using single $ (`$...$`).
2. No formula showing when using double $ (`$$...$$`).
3. When in server mode, using `{% math %} ... {% endmath %}` gives:
`...Unhandled rejection Template render error: (unknown path) [Line 15, Column 101]
  unknown block tag: math...`

**Comment by LouisBarranqueiro** [comment]
:wave: @wendingp,  please follow the template to post an issue otherwise it's hard for me to help you.
