### ISSUE TITLE
Thumbnail won't show with my assets

### ISSUE THREAD

**Issue by talentprince** [LouisBarranqueiro/hexo-theme-tranquilpeak#444]
### Configuration

 - **Operating system with version** : Darwin 16.7.0 darwin x64
 - **Node version** :  8.5.0
 - **Hexo version** :  3.3.9
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : latest
 

### Actual behavior
I use thumbnailImage: /images/xxx.png, doesn't work, the generate url is http://host/blog-name/source/images/xxx.png
It should be the same like the image inside my log, /source/images/xxx.png

### Expected behavior
Show the correct thumbnail from the directory of source->images

**Comment by LouisBarranqueiro** [comment]
👋 @talentprince, you have to put these images in the folder related to your post. otherwise use an absolute link. 

Read: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#enable-post-assets-folder
