### ISSUE TITLE
share supports wechat

### ISSUE THREAD

**Issue by youngmeng** [LouisBarranqueiro/hexo-theme-tranquilpeak#446]
when can this theme's share support WeChat and Moments？

**Comment by YoshinoriN** [comment]
@youngmeng 

Do you mean that share button ?
You can add share buttons for any services using by _config.yml if you want.This feature implemented in v 1.10.0.
 
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#sharing-options

**Comment by youngmeng** [comment]
@YoshinoriN 

I mean the share button after article. I know the sharing-options, but I still can't add Wechat and Moments button. May somebody has added it?

**Comment by LouisBarranqueiro** [comment]
Hi @youngmeng , why you can't? You just have to add these new sharing options to the list.
