### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by RadianceL** [LouisBarranqueiro/hexo-theme-tranquilpeak#448]
Hey, add my blog into the showcase:https://radiancel.github.io/

and i have a question：
my blog each of document is too big（long） at home page；
how config like your blog？

**Comment by LouisBarranqueiro** [comment]
Hey @RadianceL , thanks for using this theme. 

> my blog each of document is too big（long） at home page；
how config like your blog？ 

You are searching this post excerpt feature: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#define-post-excerpt
