### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by mikecann** [LouisBarranqueiro/hexo-theme-tranquilpeak#454]
Hey, add my blog into the showcase: https://mikecann.co.uk/

**Comment by mikecann** [comment]
Thanks for the awesome work on the theme, really makes my blog shine.

BTW Im thinking of making the background a video, I have a ton of drone videos that might look good if I clip, loop then blur them: https://www.youtube.com/channel/UCrgLfQ1_Z5QQx4JKmtxkxIg/videos

**Comment by LouisBarranqueiro** [comment]
👋 @mikecann, you have some amazing videos man 👍 ! you can modify the theme to insert a HTML5 video yeah! :D

**Comment by mikecann** [comment]
Awesome thanks mate.
