### ISSUE TITLE
Question about TOC and $1 in headings

### ISSUE THREAD

**Issue by aerohub** [LouisBarranqueiro/hexo-theme-tranquilpeak#455]
The problem is: if I have $1 in headings it is trimmed in generated TOC. 

**Example:**
Heading in source post text `### If I Had $1000000`
becomes `<h3>If I Had $1000000</h3>`
but TOC item looks like this `If I Had 000000`

If I use double $ in heading then the TOC item looks good but generated `<h3>` does not:
Source: `### If I Had $$1000000`
HTML: `<h3>If I Had $$1000000</h3>`
TOC item: `If I Had $1000000`

It's just a question. I am not sure it's a theme bug. May be it conflicts with some script, I cannot realize myself.

**Comment by LouisBarranqueiro** [comment]
👋 @aerohub , it's a bug from the [Hexo toc](https://hexo.io/docs/helpers.html#toc) helper. Create an issue on their repository to report this bug.
