### ISSUE TITLE
Add my blog into the showcase, and more. (multi-language site inplemented)

### ISSUE THREAD

**Issue by zyzyz** [LouisBarranqueiro/hexo-theme-tranquilpeak#458]
Hey, add my blog into the showcase: http://zyzyz.github.io/en/

My blog supports 3 languages and I add a language switch button at footer.
It should be able to switch language for any page.

Sorry for my few posts as my foreign language is not so good. There are still few bugs but it should be okay for showcase.

I have modified some part of the theme and use my own plugins to implement this feature. further discussion is welcome if anyone interests. (or should I open another issue?)

**Comment by LouisBarranqueiro** [comment]
👋 @zyzyz , good job  for having internationalize your entire blog (posts included). 

Could you try to PR the repository to create a new section in the documentation to explain how to do that using your plugin? (if it's not tricky of course) :)

**Comment by zyzyz** [comment]
@LouisBarranqueiro 
Sorry for my late reply, I have created a PR to give a multi-language site building solution. 

It may be complicate(or tricky?) to achieve that, as the original Hexo has not good supports for multi-language switch. I provide a diff file to make the solution "portable". My aim is mainly provide ideas about implementation of whole-site i18n with a switch, so it's okay to reject the PR if you think it's not good.:stuck_out_tongue_closed_eyes:

And because the template `layout/_partial/post/tag.ejs` uses `list_tags`, it still leads to wrong navigation of tag buttons below every post(lack "language" part in links). I haven't come up with a good way to solve this without touching hexo core stuffs.
