### ISSUE TITLE
"algoliasearch is not defined" on Posts but is on Index?

### ISSUE THREAD

**Issue by mikecann** [LouisBarranqueiro/hexo-theme-tranquilpeak#459]
### Configuration

 - **Operating system with version** : Windows 10
 - **Node version** : 6.11.3
 - **Hexo version** : 3.2.0
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : 1.10.0 - modified
 

### Actual behavior
Search popup doesn't open on pages or blog posts and get error "algoliasearch is not defined" in console.

### Expected behavior
Should be able to open search popup from anywhere and shouldnt get errors

### Steps to reproduce the behavior

If you go to any post on my blog (for example https://mikecann.co.uk/blog/the-static-blog/) then open up the console you get the following error:

```
(index):931 Uncaught ReferenceError: algoliasearch is not defined
    at (index):931
```

Which I suspect is the reason why you cant open the search popup when in a post. 

If you go to the index page (https://mikecann.co.uk/) then you don't get the error and the search popup works just fine.

I looked at the source and they look identical so I have no idea what could be causing it. Have you got any idea?

The Source for my site is here: https://github.com/mikecann/mikecann.co.uk

**Comment by LouisBarranqueiro** [comment]
👋 @mikecann, indeed that is weird. Could you please fill out the template to report a bug. It would help me to understand and solve our problem

**Comment by mikecann** [comment]
@LouisBarranqueiro sorry about that, I have now updated the issue above using the template. Thankyou very much for your time and any assistance you may be able to offer 😄

**Comment by mikecann** [comment]
Its odd because the code for loading algoliasearch is exactly the same at the bottom of the homepage and the about page:

```

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.14.1/moment-with-locales.min.js"></script>
--
  | <script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
  | <script>
  | var algoliaClient = algoliasearch('JYZJ63OX7U', '01ddc3505766aa8d46cbbd65006671ec');
  | var algoliaIndex = algoliaClient.initIndex('mikecann');
  | </script>

```

BTW I am using https://github.com/oncletom/hexo-algolia to update the index instead of your algolia plugin, perhaps thats the issue?

**Comment by mikecann** [comment]
I located the problem.

I had a MailChimp signup form popup that was conflicting for some reason:

```script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">require(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us3.list-manage.com","uuid":"aaed03be8d4e6cc7ca902a572","lid":"3c8f7e6e85"}) })</script>```

My solution was just to make sure that the above is the very last thing that loads.

**Comment by LouisBarranqueiro** [comment]
Ok great @mikecann! When I inspected your site, the strange thing happened on your post pages. Algolia script was loaded but instead of expose `window.algoliasearch`, it exposed `window.AlgoliaSearch`. I don't really know why.

**Comment by mikecann** [comment]
hmmm.. it perhaps has something to do with me using https://github.com/oncletom/hexo-algolia in my project? Either way it works now, thanks for your help!
