### ISSUE TITLE
how to set the name 

### ISSUE THREAD

**Issue by promontory7** [LouisBarranqueiro/hexo-theme-tranquilpeak#460]
`<h4 id="about-card-name">[object Object]</h4>`

why the name is "[object Object]"?

//---------------this is my config

author: 
    email: 
    location: 广州
    picture: avatar.jpg
    twitter: 
    google_plus: 
    google_plus_business:

**Comment by LouisBarranqueiro** [comment]
👋 @promontory7, because the indentation is not correct. If you want a more detailed answer please fill out the template to report a bug.
