### ISSUE TITLE
Unhandled rejection ReferenceError when generating posts with non-empty values of categories

### ISSUE THREAD

**Issue by minchaowu** [LouisBarranqueiro/hexo-theme-tranquilpeak#463]
### Configuration

 - **Operating system with version** : Linux 4.10.0-40-generic linux x64 | ubuntu 16.04 LTS
 - **Node version** : 4.2.6
 - **Hexo version** : 3.4.2
 - **Hexo-cli version** : 1.0.4
 - **Tranquilpeak version** : 1.11.0 original 
 

### Actual behavior
Whenever the value of `categories:` in a front-matter is not empty, the following is reported during `hexo generate` :

> 
> Unhandled rejection ReferenceError: /home/minchao/hexo/themes/tranquilpeak/layout/all-categories.ejs:109
>     107|         <% site.categories.sort('name').each(function(category) { %>
>     108|             <% if (!category.parent) { %>
>  >> 109|                 <%- displayCategories(category) %>
>     110|             <% } %>
>     111|         <% }); %>
>     112|     </section>
> 
> site is not defined
>     at displayCategories (eval at <anonymous> (/home/minchao/hexo/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:71:27)
>     at eval (eval at <anonymous> (/home/minchao/hexo/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:125:17)
>     at Query.forEach (/home/minchao/hexo/node_modules/warehouse/lib/query.js:42:5)
>     at eval (eval at <anonymous> (/home/minchao/hexo/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:119:37)
>     at returnedFn (/home/minchao/hexo/node_modules/ejs/lib/ejs.js:580:17)
>     at _compiled (/home/minchao/hexo/node_modules/hexo/lib/theme/view.js:127:30)
>     at View.render (/home/minchao/hexo/node_modules/hexo/lib/theme/view.js:29:15)
>     at /home/minchao/hexo/node_modules/hexo/lib/hexo/index.js:390:25
>     at tryCatcher (/home/minchao/hexo/node_modules/bluebird/js/release/util.js:16:23)
>     at /home/minchao/hexo/node_modules/bluebird/js/release/method.js:15:34
>     at RouteStream._read (/home/minchao/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
>     at RouteStream.Readable.read (_stream_readable.js:328:10)
>     at resume_ (_stream_readable.js:718:12)
>     at nextTickCallbackWith2Args (node.js:441:9)
>     at process._tickCallback (node.js:355:17)

### Expected behavior
No error.

### Steps to reproduce the behavior
Write a new post with a non-empty value of `categories:` and `hexo generate`.

**Comment by LouisBarranqueiro** [comment]
👋 @minchaowu, I cannot reproduce this bug. Could you please add the front-matter of your post?
Did you try to uninstall then re-install dependencies? 
Did you try to clean cached file with `hexo clean` then `hexo g`?

**Comment by minchaowu** [comment]
@LouisBarranqueiro I should have come back to this early -- it has been fixed by upgrading node version from 4.2.6 to 9.8.0. I was pretty sure it has nothing to do with the cached files as I've tried `hexo clean` several times. Thanks for the help, and sorry about the delay.

**Comment by LouisBarranqueiro** [comment]
Happy to hear that. I'm going to update required node version to the latest node LTS version.
