### ISSUE TITLE
"npm run start" fail, TypeError [ERR_INVALID_CALLBACK]: Callback must be a function

### ISSUE THREAD

**Issue by wangyeming** [LouisBarranqueiro/hexo-theme-tranquilpeak#468]
### Configuration

 - **Operating system with version** : 
mac os High Sierra
 - **Node version** : 
v9.3.0
 - **Hexo version** : 
3.4.4
 - **Hexo-cli version** : 
1.0.4
 - **Tranquilpeak version** : 
1.11.0

 original

### Actual behavior
npm install   result: success
bower install  result: success
npm run start  result : fail

    > hexo-theme-tranquilpeak@1.11.0 start /Users/wangyeming/workshop/my/wangyeming-blog-source/themes/tranquilpeak
    > grunt default

    Loading "Gruntfile.js" tasks...ERROR
    >> TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    Warning: Task "default" not found. Use --force to continue.
    Aborted due to warnings.
    npm ERR! code ELIFECYCLE
    npm ERR! errno 3
    npm ERR! hexo-theme-tranquilpeak@1.11.0 start: `grunt default`
    npm ERR! Exit status 3
    npm ERR!
    npm ERR! Failed at the hexo-theme-tranquilpeak@1.11.0 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm ERR! A complete log of this run can be found in:
    npm ERR!     /Users/wangyeming/.npm/_logs/2018-01-03T06_32_37_919Z-debug.log

### Expected behavior

build success

**Comment by sskim91** [comment]
I have same error.. :(

**Comment by berniechiu** [comment]
@wangyeming 
I use node stable version and reinstall grunt works fine afterwards, hope if this helps

**Comment by sskim91** [comment]
@berniechiu 
Thank you!
I reinstall node stable version it works fine!

**Comment by LouisBarranqueiro** [comment]
👋 guys, I'm going to update dependencies, so users will use local grunt instead of global grunt.
