### ISSUE TITLE
scrset in gallery

### ISSUE THREAD

**Issue by snoopy21** [LouisBarranqueiro/hexo-theme-tranquilpeak#472]
**Configuration**
    Operating system with version :
    Windows 10
    Node version :
    v9.3.0
    Hexo version :
    3.4.4
    Hexo-cli version :
    1.0.4
    Tranquilpeak version :
    1.11.0

I'm trying out to integrate responsive images into the gallery - fancybox seems to support this. I edited layout\_partial\post\gallery.ejs with something like `data-srcset="<%= photo.original2x %> 2048w, <%= photo.original %> 1024w"` in the <a>-tag, but this string never appeared in the source-code of the html-page with an image-gallery. Is there another place where the code of the image-gallery is generated?

**Comment by LouisBarranqueiro** [comment]
👋 @snoopy21, it should do the job. Did you regenerate the site?

**Comment by snoopy21** [comment]
@LouisBarranqueiro hmm, no it did not work. I'm also missing all the div's with `class="photo-box"`. My gallery begins with `{% image fancybox fig-50 group`

**Comment by LouisBarranqueiro** [comment]
you are mistaking gallery images and basic images. 

Images gallery is defined in the front-matter:
``` yml
title: Image gallery showcase
photos:
  - >-
    http://example.com/image
    http://example.com/image-thumbnail
    "Mercedes"

```

Basic images are defined in the body:
``` html
{% image fancybox fig-25 clear  http://example.com/image http://example.com/image-thumbnail %}
```

Here you changed the code of the images gallery. So it does not affect basic images. You have to change the code of the **image** tag in `./scripts/tags/image.js`.

What are you trying to do exactly? It could be interesting to update the theme :)

**Comment by LouisBarranqueiro** [comment]
> it would be nice to give an absolute url without the domain name in it like "/gallery/aaa/1.jpg"

I don't think so we can do that. Hexo API is so poorly documented 😢
