### ISSUE TITLE
<p> nested in <li> has an unexpected margin

### ISSUE THREAD

**Issue by zyzyz** [LouisBarranqueiro/hexo-theme-tranquilpeak#474]
### Configuration

 - **Operating system with version** :  Windows 7 64bit
 - **Node version** : v6.11.4
 - **Hexo version** : 3.3.9
 - **Hexo-cli version** : 1.0.3
 - **Tranquilpeak version** : 1.11.0 Modified
 

### Actual behavior
The default behaviour of Markdown is to wrap the list items in \<p\> tags if list items are separated by blank lines, this leads to an annoying margin in this theme.
![snipaste_20180129_144524](https://user-images.githubusercontent.com/7401846/35509806-9c0f5300-0530-11e8-9ae2-6572952758e4.jpg)

### Expected behavior
Tried to modify the `source/_css/components/_post.scss` in this way:
![image](https://user-images.githubusercontent.com/7401846/35510005-41a46724-0531-11e8-92a0-4977c0e0a865.png)
and it gives an expected result:
![image](https://user-images.githubusercontent.com/7401846/35510038-6b27c474-0531-11e8-9975-8ee389a6ead5.png)

**Comment by LouisBarranqueiro** [comment]
👋 @zyzyz, sounds good to me. Do you want to create a pull request?

**Comment by zyzyz** [comment]
@LouisBarranqueiro 
with pleasure. #482
