### ISSUE TITLE
Netlify Not Generating Assets Folder

### ISSUE THREAD

**Issue by markgenest** [LouisBarranqueiro/hexo-theme-tranquilpeak#475]
### Configuration

 - **Operating system with version** : WIndows 10 Pro 1709 16299.214
 - **Node version** : 6.9.5
 - **Hexo version** : 3.5.0
 - **Hexo-cli version** : 1.0.4
 - **Tranquilpeak version** :  [hexo-theme-tranquilpeak-built-for-production-1.11.0](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak#quick-start)
 

### Actual behavior
On both production and development versions, [Netlify ](https://app.netlify.com/) builds public folder using `hexo generate` but will not generate assets folder or combine css/js causing page render problems. However in page source, the combined css/js links are there, they just don't link to any asset folder as it doesn't exist. As you can see in the below local/live build outputs, the assets folder is clearly not generated on live build.

[Live Demo Here](https://mgportfolio2.netlify.com/)

[Local Hexo Generate Output.txt](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/1713876/Local.Hexo.Generate.Output.txt)

[Netlify Hexo Generate Output.txt](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/1713877/Netlify.Hexo.Generate.Output.txt)

### Expected behavior
Netlify deploy should build the `hexo generate` public with assets folder the same as it does on local `hexo generate` command. Builds on local as expected in both production and development versions .

### Steps to reproduce the behavior
- Hosting repo on [Bitbucket ](https://bitbucket.org/)which deploys the static build to [Netlify](https://app.netlify.com/).
- Download tranquilpeak theme and add to fresh hexo install (no additional plugins added to cause conflict)
- Install dependencies using `npm install` & `bower install` in theme folder
- Run initial build with `npm run start` in theme folder
- Run production build with `npm run prod` in theme folder
- Add `jquery `& `prompt ` module dependencies in hexo root `package.json` so they will be installed when Netlify builds (otherwise causes the build to fail due to uninstalled modules)

Beautiful theme. Would really like to use it. Any help would be GREATLY appreciated. 
Thanks so much!

**Comment by markgenest** [comment]
Finally fixed the issue!

### Steps to fix the issue
- Delete `assets `folder in theme `.gitignore`
- Smack self upside the head

**Comment by LouisBarranqueiro** [comment]
👋 @markgenest, Good news! 👍

**Comment by anbuchelva** [comment]
I had build my site using netlify without any issues.  I did not add the theme as sub module, instead i download the [production release](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v2.0.0) on [the fly](https://github.com/anbuchelva/blog/blob/036fe88c039bdaeec7f227429dbbe06a246ae87a/build_theme.sh#L3) and copy the [theme customization](https://github.com/anbuchelva/blog/tree/source/themes/blog_tranquilpeak) related files during the build.

The following commands are used to build the sites:
[.build_theme.sh](https://github.com/anbuchelva/blog/blob/source/build_theme.sh) && [.build_site.sh](https://github.com/anbuchelva/blog/blob/source/build_site.sh)

I have used 3 environment variables such as 
[GH_TOKEN](https://github.com/anbuchelva/blog/blob/036fe88c039bdaeec7f227429dbbe06a246ae87a/build_site.sh#L3) - to push the deployed site contents back to the [git repo](https://github.com/anbuchelva/blog/tree/master), 
[ALGOLIA_ADMIN_API_KEY](https://github.com/anbuchelva/blog/blob/036fe88c039bdaeec7f227429dbbe06a246ae87a/_config.yml#L98) and 
[ci](https://github.com/anbuchelva/blog/blob/036fe88c039bdaeec7f227429dbbe06a246ae87a/build_site.sh#L10) to identify whether the site was built by Netlify or Travis-CI.

it build the site [less than 1 min](https://app.netlify.com/sites/anbu-blog/deploys) which is faster than [Travis-CI](https://travis-ci.org/anbuchelva/blog/builds)
