### ISSUE TITLE
Structured data - missing required fields

### ISSUE THREAD

**Issue by SergeyPodgornyy** [LouisBarranqueiro/hexo-theme-tranquilpeak#479]
### Configuration

 - **Operating system with version** : all
 - **Node version** : all
 - **Hexo version** : latest
 - **Hexo-cli version** : latest
 - **Tranquilpeak version** : original
 

### Actual behavior

Missing required fields in schema.org markdown. Google related manual could be found [here](https://developers.google.com/search/docs/data-types/article#article_types).

![structured_data](https://user-images.githubusercontent.com/13667212/36631874-58457fe2-197f-11e8-94a8-61ed76b2c691.png)

### Expected behavior

**Errors:**
* A value for the *author* field is required.
* A value for the *datePublished* field is required.
* A value for the *publisher* field is required.
* A value for the *headline* field is required.
* A value for the *image* field is required.

**Warnings**:
* The *dateModified* field is recommended. Please provide a value if available.
* The *mainEntityOfPage* field is recommended. Please provide a value if available.

### Steps to reproduce the behavior

Using [Google test tool](https://search.google.com/structured-data/testing-tool#url=http%3A%2F%2Flouisbarranqueiro.github.io%2Fhexo-theme-tranquilpeak%2F) you can found, which errors and warnings are on the page.

**Comment by LouisBarranqueiro** [comment]
👋 @SergeyPodgornyy, these metadata are present in post pages but it seems that Google does not find them. I'll take a look at it.

**Comment by SergeyPodgornyy** [comment]
:wave:  @LouisBarranqueiro 
It's possible to fix with adding `JSON-LD code` to rendered page. As an example, which will be valid for Google:

```html
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "BlogPosting",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://google.com/article"
  },
  "headline": "Article headline",
  "image": [
    "https://example.com/photos/1x1/photo.jpg",
    "https://example.com/photos/4x3/photo.jpg",
    "https://example.com/photos/16x9/photo.jpg"
   ],
  "datePublished": "2015-02-05T08:00:00+08:00",
  "dateModified": "2015-02-05T09:20:00+08:00",
  "author": {
    "@type": "Person",
    "name": "John Doe"
  },
   "publisher": {
    "@type": "Organization",
    "name": "Google",
    "logo": {
      "@type": "ImageObject",
      "url": "https://google.com/logo.jpg"
    }
  },
  "description": "A most wonderful article"
}
</script>
```

**Comment by LouisBarranqueiro** [comment]
@SergeyPodgornyy Thanks for your suggestions

**Comment by IMMUKESHPATEL** [comment]
Where do I paste this code

**Comment by LouisBarranqueiro** [comment]
👋 @IMMUKESHPATEL , you can paste that in this file https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/head.ejs

Don't forget to rebuild the theme after that:  https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#modifying-the-theme
