### ISSUE TITLE
Title Size

### ISSUE THREAD

**Issue by youngmeng** [LouisBarranqueiro/hexo-theme-tranquilpeak#480]
Hi, I just want to know how to change the font size of title text?

**Comment by LouisBarranqueiro** [comment]
👋 @youngmeng , you have to edit the theme. Check [developer doc](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/developer.md) to know how to install the necessary, edit and rebuild the theme.

**Comment by youngmeng** [comment]
@LouisBarranqueiro Thank you very much.
