### ISSUE TITLE
Where can I see the demo configuration information

### ISSUE THREAD

**Issue by PLDaily** [LouisBarranqueiro/hexo-theme-tranquilpeak#481]
Where can I see the [demo](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/) configuration information ?

**Comment by LouisBarranqueiro** [comment]
👋 @PLDaily, only blog posts are available here: [source-blog-posts](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/tree/source-blog-posts)

What do you want to know? I will tell you :)

**Comment by PLDaily** [comment]
I saw the showcase and build my blog. very nick theme. thanks
