### ISSUE TITLE
sometimes link in alert doesn't shift to next line properly

### ISSUE THREAD

**Issue by zyzyz** [LouisBarranqueiro/hexo-theme-tranquilpeak#487]
### Configuration

 - **Operating system with version** : Windows 7 64bit
 - **Node version**: v6.11.4
 - **Hexo version**: 3.3.9
 - **Hexo-cli version**: 1.0.3
 - **Tranquilpeak version**: 1.11.0 Modified
 
### Actual behavior
For some links it's wrong:
![image](https://user-images.githubusercontent.com/7401846/38465480-be28870a-3b4e-11e8-8b5f-a2792c73a19e.png)
![image](https://user-images.githubusercontent.com/7401846/38465498-0937f3de-3b4f-11e8-825b-1527f05ba2db.png)

but if there's a dash:
![image](https://user-images.githubusercontent.com/7401846/38465551-bc33e6dc-3b4f-11e8-9c85-5060c2b79024.png)

or this link:
![image](https://user-images.githubusercontent.com/7401846/38465584-469fa914-3b50-11e8-8cf0-d0a6e4d53149.png)

Markdown:
```
{% alert info %}
References：  
https://XXXXXX.....
{% endalert %}
```

**Comment by LouisBarranqueiro** [comment]
👋 @zyzyz , I'm on it
