### ISSUE TITLE
Netlify deployment

### ISSUE THREAD

**Issue by verlanmar** [LouisBarranqueiro/hexo-theme-tranquilpeak#488]
Hi Louis!

### Configuration

 - **Operating system with version** : Netlify (linux-x64)
 - **Node version**: 8.11.1
 - **Hexo version**: 3.7.1
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: 2.0.0 original, built for production
 - **Hexo plugin**: hexo@3.7.1, hexo-generator-archive@0.1.5, hexo-generator-category@0.1.3, hexo-generator-index@0.2.1, hexo-generator-tag@0.2.0, hexo-renderer-ejs@0.3.1, hexo-renderer-markdown-it@3.4.1, hexo-renderer-stylus@0.3.3, hexo-server@0.2.2, jquery@3.3.1, jsdom@11.7.0
 
I have red all closed issues on the error 404, I have red documentation, I experimented with settings, but still assets are not loading and I have no ideas left what else to do :(

The screenshot shows that I'm using production version:

![screenshot](https://user-images.githubusercontent.com/38294552/38633170-8694c058-3dc7-11e8-97b1-ea91182306f2.png)

This is my Netlify log:
[Netlify-log.txt](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/files/1899857/Netlify-log.txt)

Any ideas how to fix this?
The default "landscape" theme works without the issue.

Thanks!

**Comment by anbuchelva** [comment]
@verlanmar can you share your repo? i would like to understand what command you are using to build the site using netlify.

I was able to build it successfully, but tried integrating netlify-cms, but the page's style is overlapping netlify cms's

![screenshot 13](https://user-images.githubusercontent.com/5076760/40559439-663f63e2-6074-11e8-9059-9b61442216bf.png)

**Comment by LouisBarranqueiro** [comment]
Hey @verlanmar, Sorry for the late response. It's because Netlify is reading `.gitignore` file and ignoring `source/assets` folder where all files are uploaded. Remove `.gitignore` file before deploying your site and it should be good. See more here : https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/475
