### ISSUE TITLE
clojure syntax highlight support

### ISSUE THREAD

**Issue by jiacai2050** [LouisBarranqueiro/hexo-theme-tranquilpeak#489]
### Configuration

 - **Operating system with version** : 
 - **Node version**: 
 - **Hexo version**: 
 - **Hexo-cli version**: 
 - **Tranquilpeak version**: 
 - **Site configuration file** (Optional):
 - **Theme configuration file** (Optional):
 - **Hexo plugin** (Optional): 
 
### Actual behavior

https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/source/_css/themes/_hljs-tranquilpeak.scss#L20

In this file, there is no rules for clojure.

**Comment by LouisBarranqueiro** [comment]
👋 @jiacai2050, I'm on it.

**Comment by jiacai2050** [comment]
👍Thanks
