### ISSUE TITLE
Gitalk support?

### ISSUE THREAD

**Issue by hilen** [LouisBarranqueiro/hexo-theme-tranquilpeak#490]

**Comment by LouisBarranqueiro** [comment]
👋 @hilen,  we already support Gitment. What are the pros compared to Gitment.

**Comment by hilen** [comment]
Gitment is no longer update. I like Gitalk's UI.

**Comment by fletchto99** [comment]
I don't really have the time to help implement this but I'd like to +1 it.

**Comment by fletchto99** [comment]
Took a first pass at implementing this today: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/533
