### ISSUE TITLE
code blocks inside alert tag cannot be rendered normally

### ISSUE THREAD

**Issue by zyzyz** [LouisBarranqueiro/hexo-theme-tranquilpeak#491]
### Configuration

 - **Operating system with version** : Windows 7 64bit
 - **Node version**: v6.11.4
 - **Hexo version**: 3.3.9
 - **Hexo-cli version**: 1.0.3
 - **Tranquilpeak version**: 1.11.0 Modified
 
### Actual behavior
If I add a code block in a alert tag block the code block will be rendered incorrectly (an "undefined" is shown).
Inline code Markdown syntax seems to be working as normal.
![image](https://user-images.githubusercontent.com/7401846/41189405-51f69b4a-6c08-11e8-8e18-ff9eef73fc9d.png)

### Expected behavior
The code blocks wrapped by alert tag block are rendered normally.

**Comment by LouisBarranqueiro** [comment]
👋 @zyzyz ,

It's an issue from `hexo.render.renderSync` function.

I suggest you to report this issue on their repository and use this syntax until it gets fixed.
``` md
{% alert info %}
    Haaay! What's poppin?!
    {% codeblock %}
	array.map(callback[, thisArg])
    {% endcodeblock %}
{% endalert %}
```
