### ISSUE TITLE
How to change the font and max width of post content

### ISSUE THREAD

**Issue by miranoisora** [LouisBarranqueiro/hexo-theme-tranquilpeak#495]
### Configuration

 - **Operating system with version** : Windows10 
 - **Node version**: 8.11.2
 - **Hexo version**: 3.7.1
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: 2.0.0
 
Hi, @LouisBarranqueiro 
I want to change the font and max-width of post content. I read  `DOCUMENTATION.md` and it said this can be done in `source/_css/utils/_variables.scss` file.

I modified `source/_css/utils/_variables.scss` line 7 from
``` scss
$merriweather-serif:   'Merriweather', serif;
```
to
``` scss
$merriweather-serif:   'Merriweather', 'PingFang SC', 'Microsoft YaHei', sans-serif;
```
in order to make chinese characters look more comfortable with sans-serif fonts.

And changed line 219 from
``` scss
    'max-width':          750px,
```
to
``` scss
    'max-width':         1000px,
```

But run `hexo g` still give a page in 750px width and render with Windows default chinese serif font (SimSun). I checked the font-family in the generated html&css files and it still `font-family: Merriweather,serif;`.
I'm wondering how to solve this problem.

Besides, I think sticky table of content (issue#410) is a good idea. Hope this beautiful theme can have this feature in the future.

Thank you!

**Comment by marikid** [comment]
Seems like you haven't rebuild the theme.
Head to `themes/tranquilpeak` and run `npm install` then `grunt buildProd`, and you should expect the changes.
Feel free to ask more.

BTW, sticky table of contents, IMHO, destory the page's conciseness. You won't read the table of contents over and over again while you're reading a book, right?

**Comment by miranoisora** [comment]
@marikid Thank you, it works!
Maybe you are right, it will destroy the conciseness indeed.

**Comment by miranoisora** [comment]
BTW, the top/bottom bar is too easy to show up now. Especially when using cellphone, any tiny scroll up will let the top/bottom bar appear. Sometimes we just touch the screen by casual and the bar will be annoying. In this point, I think Safari App is a good example. I don't know whether web page can perform like that...

**Comment by marikid** [comment]
These lines determine the sensitivity, you can manually change them:
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/source/_js/header.js#L15
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/source/_js/post-bottom-bar.js#L15
However the page didn't work as I expected: scroll up certain pixels should show the bars, and scroll down will immediately hide the bars (most sites take this method). I'll submit an issue.

**Comment by LouisBarranqueiro** [comment]
Thanks @marikid for your help! :)
