### ISSUE TITLE
Missing remove icon in about card

### ISSUE THREAD

**Issue by eppfel** [LouisBarranqueiro/hexo-theme-tranquilpeak#496]
### Configuration

 - **Operating system with version** : macOS 10.12.6
 - **Node version**: v8.11.1
 - **Hexo version**: 3.2.2
 - **Hexo-cli version**: 1.0.4
 - **Tranquilpeak version**: 3.0.0 (checked unmodified and modified version)
 
<img width="817" alt="screen shot 2018-07-19 at 10 29 51" src="https://user-images.githubusercontent.com/1899308/42928471-05a06fb2-8b40-11e8-86fc-9a76873e1e28.png">

### Actual behavior
Opening the about card does not show the close icon and you can't return without using the browser back button.

### Expected behavior
visible icon

Might be a feature request, but clicking anything but the card could also remove it.

### Steps to reproduce the behavior
Open about card.

the `remove` ison seems to be removed 🎉  in font awesome 5, now it is called `times`

Line to change is: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/layout/_partial/about.ejs#L15

**Comment by marikid** [comment]
Same problem for the close button in share options.
![](https://i.loli.net/2018/07/19/5b5090bc823b2.png)
Line to change:
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/layout/_partial/post/share-options.ejs#L2
