### ISSUE TITLE
Scroll delta doesn't work as expected

### ISSUE THREAD

**Issue by marikid** [LouisBarranqueiro/hexo-theme-tranquilpeak#498]
### Configuration

 - **Operating system with version** : Windows 10
 - **Node version**: 8.11.3
 - **Hexo version**: 3.7.1
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: 3.0.0
 
### Actual behavior/Steps to reproduce the behavior

Change the values below to something else, like 50:

https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/source/_js/header.js#L15
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/f6432960e50ac5b303a484de395478e35bd5bfdb/source/_js/post-bottom-bar.js#L15

Rebuild the theme and scroll the page, the bottom bar shows/hides as before, and the header bar shows/hides after having totally scrolled 50px (`delta`) in the same direction.

### Expected behavior

The values are obviously customizable. According to the code comments, the show/hide behavior of the bars **should** be controlled by `delta`, however, for the bottom bar the value **doesn't** work, and the behavior of the header bar is **uncommon**.

AFAIK, most sites take this method: the bars will show after having totally scrolled up a certain distance, and scroll down will immediately hide the bars.

(Pardon me for not being able to express myself clearly.)

**Comment by LouisBarranqueiro** [comment]
👋 @marikid, could you give a try with this new version (`dev` branch) and let me know if it looks good to you? :)

**Comment by marikid** [comment]
Yeah, almost perfect! Maybe I thought too much, it doesn't have to be this complex.

**Comment by LouisBarranqueiro** [comment]
How would you do it simpler? :)
