### ISSUE TITLE
YAML syntax highlighting?

### ISSUE THREAD

**Issue by justincalleja** [LouisBarranqueiro/hexo-theme-tranquilpeak#50]
Using either `yaml` or `yml` in the following:

\```yml
root:             public
dest:             <%= site.root %>
assets:           <%= site.dest %>/assets

data:             data/*.{json,yml}

templates:        templates
includes:         <%= site.templates %>/includes/*.hbs
layouts:          <%= site.templates %>/layouts
layout:           default.hbs

helpers:          
  \- <%= site.templates %>/helpers/*.js

description:      <%= pkg.description %>
\```

Gives this result:

![yaml-snippet](https://cloud.githubusercontent.com/assets/9398504/8635255/f189ca4e-281b-11e5-8c99-1644b9ae0364.png)

There is only one line number and there is no syntax highlighting. I also tried with Hexo codeblock tag. Same result.

If am using "json" instead for now (which gives me line numbers, but still no highlighting).

Is this something specific to Hexo? I read somewhere that Hexo uses highlight.js for syntax highlighting. But highlight.js supports yaml highlighting (as I've used it in the past).

Any idea how I can fix this?

Cheers,
J

**Comment by LouisBarranqueiro** [comment]
The plugin behind highlighted code feature of Hexo is [highlight.js](https://github.com/isagalaev/highlight.js) and currently it doesn't support yml.

**Comment by justincalleja** [comment]
I am using highlight.js in another blog and getting this:

![yaml-snippet-with-hightlightjs](https://cloud.githubusercontent.com/assets/9398504/8635449/9c118a54-2823-11e5-9f1d-77294c96d2d5.png)

Granted, it's not highlighting everything but it's better than nothing.

I am using `//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.3/highlight.min.js`

**Comment by LouisBarranqueiro** [comment]
Is it the same library? because i'm sure that highlight does not support yaml [highlight.js#119](https://github.com/isagalaev/highlight.js/issues/119)

**Comment by justincalleja** [comment]
lol ok no idea. It looks like the same library. But the generated HTML differs. Also, cannot see the library being pulled in. In general, not enough info to meaningfully discuss this so am closing.

Might look into it later, but it's not a priority. Also, it most likely needs to be addressed at either Hexo or Highlight.js level.

Cheers,
J

**Comment by LouisBarranqueiro** [comment]
Highlight.js yeah! It will be good to have YAML support! :)

**Comment by justincalleja** [comment]
lol no I meant figure out why there's highlighting in the old blog but not in this one. I am not planning on implementing YAML support in highlight.js ^^;

**Comment by tufu9441** [comment]
Is YAML syntax highlighting supported in this theme now? I tried to set the language to "yml" or "yaml" but neither worked.

**Comment by LouisBarranqueiro** [comment]
It didn't depends to the theme but Hexo. Recently YAML is now supported by Highlight.js, then wait that Hexo use the last version of Highlight.js

**Comment by tufu9441** [comment]
@LouisBarranqueiro OK I see, thanks a lot.

**Comment by LouisBarranqueiro** [comment]
I checked [hexo-util](https://github.com/hexojs/hexo-util) and 5 days ago, a new version was released ([3.0.0](https://github.com/hexojs/hexo-util/releases/tag/0.3.0). It use Highlight.js 9.0.0 that add support for YAML. Now, we have to wait that Hexo use the last version of hexo-util

**Comment by tufu9441** [comment]
I see, but I found there is no related style of YAML in highlight.scss.

**Comment by LouisBarranqueiro** [comment]
Yeah, beause it not supported by Hexo yet. I will implement it when I will be able to test it with the Hexo

**Comment by tufu9441** [comment]
OK, the author of Hexo told me just now Hexo has supported YAML syntax highlighting, due to https://github.com/hexojs/hexo-util/blob/master/package.json#L36

**Comment by LouisBarranqueiro** [comment]
Yeah, but as I said, Hexo doesn't use the last version of hexo-util (0.3.0). https://github.com/hexojs/hexo/blob/3.1.1/package.json#L41

**Comment by tufu9441** [comment]
Sure, so just wait for next update of Hexo.

**Comment by LouisBarranqueiro** [comment]
I gonna take some tme to implement css, release a version. And if you really want YAML supports, get lastest Hexo beta version  :)

**Comment by tufu9441** [comment]
OK, thanks a lot for your work. I have just updated the hexo-util module to 0.4.1 individually.

**Comment by tufu9441** [comment]
I saw you released a new version, had YAML syntax highlighting style been supported?

**Comment by LouisBarranqueiro** [comment]
I'm gonna release an update for codeblocks (new style, new feature, improvement, support for highlight 9.0.0, update with the new github style). But when I tried to use yaml with (yml or yaml) highlight set plain text instead of yaml (`hexo-util`: 0.5.1). Did you manage to have yaml highlighted code?

**Comment by tufu9441** [comment]
I had no YAML highlighted code because I didn't add any YAML css to the
highlight.scss, so I can't see the effects.

On 周日, 12月 20, 2015 at 05:05, LouisBarranqueiro/hexo-theme-tranquilpeak
<reply@reply.github.com>
wrote:
I'm gonna release an update for codeblocks (new style, new feature, improvement,
support for highlight 9.0.0, update with the new github style). But when I tried
to use yaml with (yml or yaml) highlight set plain text instead of yaml ( hexo-util : 0.5.1). Did you manage to have yaml highlighted code?

—
Reply to this email directly or view it on GitHub
[https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/50#issuecomment-166023804] .[https://github.com/notifications/beacon/AGec2eWwPAFQsBHbSFYTFyG43MPW12Mxks5pRb43gaJpZM4FWwNU.gif]

**Comment by tufu9441** [comment]
So it seems YAML highlighting feature is still not completed in your latest release of 1.6.0? Or I can use plain text instead of YAML?

**Comment by LouisBarranqueiro** [comment]
I can't implement YAML css since hexo-util doesn't works properly, when I declare a codeblocks with yaml, it ouput as plain text... But I think the bug come from Highlight.js, i'm waiting a new version.

**Comment by tufu9441** [comment]
OK I see, then let's just wait for the update of highlight.js.

**Comment by tufu9441** [comment]
Can you give the YAML css you tried to implement? I want to have a try and test it.

**Comment by LouisBarranqueiro** [comment]
I got nothing because highlight doesn't recognize the yaml. Did you manage to have a codeblock with highlighted yaml? (I mean that variables, attributes, strings are wrapped in a span with the a css class)

**Comment by tufu9441** [comment]
I tried to declare a code block with YAML and it output as plain text too, just as following:

![Imgur](http://i.imgur.com/JoHqsTb.png)

So it seems a bug indeed.

**Comment by LouisBarranqueiro** [comment]
yeah, I got the same bug.

**Comment by tufu9441** [comment]
So is it a bug of [highlight.js](https://github.com/isagalaev/highlight.js)? Should we open an issue to the developer?

**Comment by LouisBarranqueiro** [comment]
It works well on their demo website so I think the problem come from hexo-util. I opened an issue : https://github.com/hexojs/hexo-util/issues/8

**Comment by tufu9441** [comment]
Hexo has updated to 3.2.0 and it can recognize YAMLnormally currently:
![qq 20160302101205](https://cloud.githubusercontent.com/assets/6790361/13448608/854bfa9e-e05f-11e5-8f2c-017096128870.png)

So maybe we can complete the YAML syntax highlighting now.

**Comment by LouisBarranqueiro** [comment]
yeah, i'm on it :)

**Comment by LouisBarranqueiro** [comment]
done :)

**Comment by tufu9441** [comment]
Then when will the next version be released? I am looking forward to it so much. :smiley:

**Comment by LouisBarranqueiro** [comment]
today, if everything is fine :) otherwise tomorrow
