### ISSUE TITLE
 I found an issue with this line.

### ISSUE THREAD

**Issue by jungjoongi** [LouisBarranqueiro/hexo-theme-tranquilpeak#507]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/0ac4c104d2fe8ac60852a9d27600649bd4f199a0/package.json#L10

"grunt": " ./node_modules/grunt-cli/bin/grunt",
---->
"grunt": "node ./node_modules/grunt-cli/bin/grunt",

This requires the node command.
If there is no node command, I got a build error.
ex) npm run prod --> error

I am sorry to speak in my poor English

(I work in the Windows 10 environment
-nodejs 10.12.0
-npm 6.4.1)

**Comment by LouisBarranqueiro** [comment]
👋 @jungjoongi , it's going to be fixed and released soon. https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/506

**Comment by bmitchinson** [comment]
@jungjoongi if you checkout the dev branch, or copy my small changes in, this has been fixed in #506 

Waiting for it to be merged into master

**Comment by LouisBarranqueiro** [comment]
👋 guys, this is now fixed with https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v3.0.2
