### ISSUE TITLE
style dosnt load

### ISSUE THREAD

**Issue by Sosha1996** [LouisBarranqueiro/hexo-theme-tranquilpeak#508]
i use gitlab and forked hexo from https://gitlab.com/pages/hexo. remove relationship and change name project and path to sosha.gitlab.io.

i changed `root: "/hexo/"` to `root: "/"` in **`_config.yml`**

paste **tranquilpeak** to theme:
![image](https://user-images.githubusercontent.com/16008585/47267301-a5c33800-d54e-11e8-9298-b7e51df50b97.png)
and change `theme: landscape` to `theme: tranquilpeak`.

commit changes. this link https://gitlab.com/Sosha/sosha.gitlab.io/-/jobs/110730533 i see many errors: **Error: Cannot find module 'jsdom'**.
ok i writing `npm install jsdom` and `npm install  jquery` to .gitlab-ci.yml
![image](https://user-images.githubusercontent.com/16008585/47267362-b9bb6980-d54f-11e8-8ad4-42cb2e3ce6b7.png)

commit again...

this time, i cant see errors but style dosent load again...

how fix it? https://sosha.gitlab.io/

**Comment by LouisBarranqueiro** [comment]
👋 @Sosha1996, make sure you run `npm install` in the theme folder and not in the blog folder, also make sure you delete the `.gitignore` of the theme file before uploading your site.

**Comment by Inokinoki** [comment]
I used the released version and met the same error.
The assets folder is not generated in Travis building.

**Comment by LouisBarranqueiro** [comment]
Did you build the theme with: `npm run prod` ? Make sure you read the documentation: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#modifying-the-theme

**Comment by Inokinoki** [comment]
Emmm... In fact, I used this tarball [3.0.1](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/download/v3.0.1/hexo-theme-tranquilpeak-built-for-production-3.0.1.zip).
The node_modules are included.
When I run ``hexo generate``, there is no ``assets`` folder generated.
If I change to other themes, the style resources are loaded and generated.
My hexo and nodejs version:
```
hexo: 3.8.0
hexo-cli: 1.1.0
os: Linux 4.15.0-36-generic linux x64
http_parser: 2.8.0
node: 8.12.0
v8: 6.2.414.66
uv: 1.19.2
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.32.0
napi: 3
openssl: 1.0.2p
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```
Thank you very much for your focus !

**Comment by LouisBarranqueiro** [comment]
That's weird. Download the latest version ready for production: [hexo-theme-tranquilpeak-built-for-production-3.0.1.zip](
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/download/v3.0.1/hexo-theme-tranquilpeak-built-for-production-3.0.1.zip). Don't modify anything and run `hexo g` to check if the assets folder is generated

**Comment by bmitchinson** [comment]
@Inokinoki @Sosha1996 did you ever find a resolution to this? I'd like help if needed, otherwise, we could close the issue.

**Comment by LouisBarranqueiro** [comment]
@Sosha1996  Feel free to re-open this issue
