### ISSUE TITLE
valine support?

### ISSUE THREAD

**Issue by lenmio** [LouisBarranqueiro/hexo-theme-tranquilpeak#511]
https://valine.js.org/quickstart.html
disqus is banned in China

**Comment by LouisBarranqueiro** [comment]
👋 @lenmio what's the most famous comment system in China. I would like to add the one that would be used the most and not all of them.

**Comment by lenmio** [comment]
China's audits have made all this unusable 
valine may be shut down at any time☹️

**Comment by LouisBarranqueiro** [comment]
👋 @lenmio , Things have changed? Is there any comment system allowed for now?

**Comment by fletchto99** [comment]
Is GitHub supported in china? I just opened a PR which implements Gitalk. Perhaps that will solve your issue? Can you load/see the comments on my blog at: https://blog.fletchto99.com?

**Comment by LouisBarranqueiro** [comment]
👋 guys, let's focus on Gitalk which seems to be more popular. Thanks a lot for the PR @fletchto99 I will review that real soon.
