### ISSUE TITLE
Changing font-size-base doesn't effect on Post

### ISSUE THREAD

**Issue by damarindra** [LouisBarranqueiro/hexo-theme-tranquilpeak#519]
### Configuration

 - **Operating system with version** :  Windows 10
 - **Node version**: 6.4.1
 - **Hexo version**: 3.3.8
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: 3.0.2
 
### Actual behavior
Changing font-size-base only change the index font size. On post page, the font size will stay the same, but the vertical spacing changing.

### Expected behavior
On post page, the font size must be change.

### Steps to reproduce the behavior
```
npm install
hexo s
npm run start
```
Then, change the font-size-base on the _variables.scss

**Comment by LouisBarranqueiro** [comment]
👋 @damarindra, the content of a post has its own rules, update rules in `_post.scss`, if you want to change the font-size

**Comment by damarindra** [comment]
Ouh, many thanks!
