### ISSUE TITLE
Images don't get rendered at index pages

### ISSUE THREAD

**Issue by itpropro** [LouisBarranqueiro/hexo-theme-tranquilpeak#520]
First, thank you very much for the hard work, I am really enjoying your theme as it provides really good extensibility.

### Configuration

 - **Operating system with version** : Windows 10 1809
 - **Node version**: 8.4.0
 - **Hexo version**: 3.8.0
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: Original
 - **Site configuration file** (Optional):
- post_asset_folder: true
- relative_link: false
 - **Theme configuration file** (Optional):
 - **Hexo plugin** (Optional): 
+-- hexo@3.8.0
+-- hexo-algoliasearch@0.3.0
+-- hexo-browsersync@0.3.0
+-- hexo-deployer-azure-blob-storage@1.0.5 (github:thdotnet/hexo-deployer-azure-blob-storage#2bb67914e775e4ee2a69a0c3c7d7638c64856c9f)
+-- hexo-fontawesome@1.1.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-author2@0.0.11
+-- hexo-generator-category-enhance@0.1.6
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-robotstxt@0.2.0
+-- hexo-generator-seo-friendly-sitemap@0.0.22
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.3.3
 
### Actual behavior
I use the provided image plugin to integrate images with fancybox. If there are images in posts before more or excerpt, they don't get rendered at the index site.
They get rendered in the post itself.
With asset_img the links work fine.
The link src fields only refer to the image-name.jpg in the same folder that one is browsing.

### Expected behavior
Images should also be rendered on index sites.

### Steps to reproduce the behavior
1. Activate asset management
2. Create a post with images only referenced by name an no more or excerpt tag before the images
3. Watch the images get rendered on the post site but not on the index site

### Suggested fix
Implement the same url resolve logic that asset_img uses in the image tag plugin

**Comment by LouisBarranqueiro** [comment]
👋 @itpropro I'm not sure what you meant with

>I use the provided image plugin to integrate images with fancybox. If there are images in posts before more or excerpt, they don't get rendered at the index site.
They get rendered in the post itself.
With asset_img the links work fine.

but all HTML tags are stripped from the excerpt to be displayed on the index page. It's a desired behavior.

**Comment by itpropro** [comment]
Hello,
this is a bug from my perspective, as this also applies to pictures mentioned before the more tag or in articles that don't have excerpt or more tag at all. The desired hexo behavior is the one you get when you use the asset_img tag. The problem is that if you use the image tag, the generator doesn't get the right asset path. The url resolve logic of the image tag doesn't work the same as the asset_img tag. If asset folder is activated, the image tag only works correct on the article page itself, not on index pages.
Thanks for looking into this :)

**Comment by LouisBarranqueiro** [comment]
👋 @itpropro, sorry for the late response. Could you please post here:
- the code of your article (formatted)
- the rendered HTML code (formatted)

so I can debug this.

**Comment by LouisBarranqueiro** [comment]
@itpropro Feel free to re-open this issue with this information I need if you still have this problem. :)
