### ISSUE TITLE
Change "Scroll to top" icon

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#521]
How do I change this icon:
![image](https://user-images.githubusercontent.com/33632286/50877631-51369880-1398-11e9-8df3-5522ec152b59.png)

To a different font awesome icon, [like this one](https://fontawesome.com/icons/chevron-circle-up?style=solid).

I'd like a symbol that represents more clearly that a click will take you to the top of the page.

Looks like the theme is currently using [this one](https://fontawesome.com/icons/list-ul?style=solid), but I couldn't find much mention of "list-ui" anywhere in the theme code to replace, aside from these locations:
![image](https://user-images.githubusercontent.com/33632286/50877715-c2764b80-1398-11e9-89e5-6580783c83fc.png)

**Comment by itpropro** [comment]
You would just have to edit line 64 in the `action.ejs` file located in `tranquilpeak\layout\_partial\post`.
I changed the following lines to reproduce your problem and it worked without any problem:
```
63            <% } %>
64                <i class="fa fa-list" aria-hidden="true"></i>
65            </a>
```
changed to
```
63            <% } %>
64                <i class="fas fa-chevron-circle-up" aria-hidden="true"></i>
65            </a>
```

**Comment by bmitchinson** [comment]
@itpropro Thanks so much! Don't know why my search didn't turn up the action.ejs file in the first place 🤔
