### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by sj602** [LouisBarranqueiro/hexo-theme-tranquilpeak#524]
### Configuration

 - **Operating system with version** : MacOS Mojave 10.14.2
 - **Node version**: Node 10.15.1
 - **Hexo version**: Hexo 3.7.1
 - **Hexo-cli version**: 
 - **Tranquilpeak version**:  2.0.0(modified)
 - **Site configuration file** (Optional):
 - **Theme configuration file** (Optional):
 - **Hexo plugin** (Optional): 
 themes/tranquilpeak
├── @fancyapps/fancybox@3.2.5
├── eslint@4.18.2
├── eslint-config-google@0.9.1
├── font-awesome@4.7.0
├── grunt@1.0.3
├── grunt-cli@1.2.0
├── grunt-contrib-clean@1.1.0
├── grunt-contrib-concat@1.0.1
├── grunt-contrib-copy@1.0.0
├── grunt-contrib-cssmin@2.2.1
├── grunt-contrib-uglify@3.3.0
├── grunt-contrib-watch@1.1.0
├── grunt-sails-linker@1.0.4
├── grunt-sass@2.1.0
├── grunt-sync@0.8.0
├── grunt-text-replace@0.4.0
├── hexo-renderer-marked@0.3.2
├── hexo-util@0.6.3
├── include-all@4.0.3
├── jquery@3.3.1
├── jsdom@11.6.2
├── load-grunt-tasks@3.5.2
├── rand-token@0.4.0
└── strip-indent@2.0.0
### Actual behavior
After `npm run start` in tranquilpeak folder,
I got this and it is waiting forerver.

```
> hexo-theme-tranquilpeak@2.0.0 start /Users/seonjin/Documents/projects/sj602.github.io/themes/tranquilpeak
> npm run grunt -- default


> hexo-theme-tranquilpeak@2.0.0 grunt /Users/seonjin/Documents/projects/sj602.github.io/themes/tranquilpeak
> node ./node_modules/grunt-cli/bin/grunt "default"

Running "clean:build" (clean) task
>> 1 path cleaned.

Running "copy:dev" (copy) task
Copied 12 files

Running "sass:dev" (sass) task

Running "concat:devJs" (concat) task

Running "sync:dev" (sync) task

Running "sails-linker:devJs" (sails-linker) task
File "layout/_partial/script.ejs" updated.

Running "sails-linker:devCss" (sails-linker) task
File "layout/_partial/head.ejs" updated.

Running "replace:linker" (replace) task

Running "replace:cssFancybox" (replace) task

Running "replace:cssTranquilpeak" (replace) task

Running "watch" task
Waiting...


```

### Expected behavior

Build successfully.

### Steps to reproduce the behavior
npm run build

**Comment by LouisBarranqueiro** [comment]
👋 @sj602, sorry for the late response. 

`npm run start`: it builds the theme and watches for changes to build it.
`npm run build`: it builds the theme and exit
