### ISSUE TITLE
Search displays results as "undefined"

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#528]
### Configuration

 - **Operating system with version** : Windows_NT 10.0.17134 win32 x64
 - **Node version**:  10.14.2
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: Original
 
### Actual behavior
Search returns no results, even though Algolia seems to be working fine.

### Expected behavior
Search should display the returned results on screen

### Details
All info is essentially [in this thread](https://github.com/LouisBarranqueiro/hexo-algoliasearch/issues/21#issuecomment-472200857), because it was originally believed to be an issue with Alogia search.

### HTML
@LouisBarranqueiro had asked for the html of the panel in order to debug the issue, so that is mentioned below. Not really sure what else to provide to make the issue easier to debug. Let me know and I'll provide. Algolia theme configuration is included in the prior mentioned thread.

`

        <div class="modal-header">
            <span class="close-button"><i class="fa fa-times"></i></span>
            <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
                <span class="searchby-algolia-text text-color-light text-small">by</span>
                <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
            </a>
            <i class="search-icon fa fa-search"></i>
            <form id="algolia-search-form" _lpchecked="1">
                <input type="text" id="algolia-search-input" name="search" class="form-control input--large search-input" placeholder="Search ">
            </form>
        </div>
        <div class="modal-body">
            <div class="no-result text-color-light text-center" style="display: none;">no post found</div>
            <div class="results"><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Software-Design/"><h3 class="media-heading">Completing Software Design</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Video-Tag-Demo/"><h3 class="media-heading">Video Tag Demo</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Playground-News/"><h3 class="media-heading">TigerHacks 2018: Playground News</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Photo-Frame/"><h3 class="media-heading">Mother's Day Photo Frame</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Laserphonic/"><h3 class="media-heading">⚡ Laserphonic</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Computer-Comfort-Year-3/"><h3 class="media-heading">Entering Year 3 of Computer Comfort 👵💻</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div><div class="media"><div class="media-body"><a class="link-unstyled" href="https://benmitchinson.com/Alexa-Bus-Tracker/"><h3 class="media-heading">Bus Predictions with Alexa</h3></a><span class="media-meta"><span class="media-date text-small">Mar 16, 2019</span></span><div class="media-content hide-xs font-merryweather">undefined</div></div><div style="clear:both;"></div><hr></div></div>
        </div>
        <div class="modal-footer">
            <p class="results-count text-medium" data-message-zero="no post found" data-message-one="1 post found" data-message-other="{n} posts found">7 posts found</p>
        </div>

`

**Comment by bmitchinson** [comment]
![image](https://user-images.githubusercontent.com/33632286/54496766-12a1ea80-48c1-11e9-8ce9-0d5ac3fa0918.png)

New github feature that lets you transfer issues? Maybe check that out if you have the option to @LouisBarranqueiro

**Comment by LouisBarranqueiro** [comment]
👋 @bmitchinson,

I checked your blog, tested the search and here is the response of the search returned by Algolia.

``` json
{
    "hits": [
        {
            "gallery": null,
            "permalink": "https://benmitchinson.com/Alexa-Bus-Tracker/",
            "photos": [],
            "slug": "Alexa-Bus-Tracker",
            "tags": [
                "Alexa",
                "Python",
                "AWS",
                "API"
            ],
            "title": "Bus Predictions with Alexa",
            "contentStripTruncate": "During local hack day this December, I developed an Alexa skill for students to check bus times through campus transportation. It was a solo project I set out to complete in 10 hours, and as of January of 2019, over 30 students are still actively invoking the skill every week. \n\n \nDevelopmentThe process of building Alexa skills has changed a lot over time, but when this skill was created, the “Skill Builder” was still in beta. So instead, I just used an AWS Lambda function to control requests to",
            "excerptStrip": "During local hack day this December, I developed an Alexa skill for students to check bus times through campus transportation. It was a solo project I set out to complete in 10 hours, and as of January of 2019, over 30 students are still actively invoking the skill every week. \n",
            "objectID": "cjqpuixeq0003oooo8m1o1nlg",
            "_highlightResult": {
                "permalink": {
                    "value": "https://benmitchinson.com/Alexa-<em>Bus</em>-Tracker/",
                    "matchLevel": "full",
                    "fullyHighlighted": false,
                    "matchedWords": [
                        "buss"
                    ]
                },
                "tags": [
                    {
                        "value": "Alexa",
                        "matchLevel": "none",
                        "matchedWords": []
                    },
                    {
                        "value": "Python",
                        "matchLevel": "none",
                        "matchedWords": []
                    },
                    {
                        "value": "AWS",
                        "matchLevel": "none",
                        "matchedWords": []
                    },
                    {
                        "value": "API",
                        "matchLevel": "none",
                        "matchedWords": []
                    }
                ],
                "title": {
                    "value": "<em>Bus</em> Predictions with Alexa",
                    "matchLevel": "full",
                    "fullyHighlighted": false,
                    "matchedWords": [
                        "buss"
                    ]
                },
                "contentStripTruncate": {
                    "value": "During local hack day this December, I developed an Alexa skill for students to check <em>bus</em> times through campus transportation. It was a solo project I set out to complete in 10 hours, and as of January of 2019, over 30 students are still actively invoking the skill every week. \n\n \nDevelopmentThe process of building Alexa skills has changed a lot over time, but when this skill was created, the “Skill Builder” was still in beta. So instead, I just used an AWS Lambda function to control requests to",
                    "matchLevel": "full",
                    "fullyHighlighted": false,
                    "matchedWords": [
                        "buss"
                    ]
                }
            }
        }
    ],
    "nbHits": 1,
    "page": 0,
    "nbPages": 1,
    "hitsPerPage": 20,
    "processingTimeMS": 1,
    "exhaustiveNbHits": true,
    "query": "buss",
    "params": "query=buss"
}
```
As you can see, the `thumbnailImageUrl` and the `excerpt` values are not there. You might want to check what you indexed. As a reminder, here are the fields you want to index:
``` yaml
  fields:
    - title
    - tags
    - date
    - categories
    - excerpt
    - excerpt:strip
    - content:strip:truncate,0,50
    - permalink
    - thumbnailImageUrl
```

Once these fields will be indexed and returned by Algolia, the search will work correctly.

**Comment by bmitchinson** [comment]
@LouisBarranqueiro I really appreciate your help with this, thank you! Fixed.
(I needed to re-run the alogia index... really sorry to have wasted your time.)

If anyone else comes across this issue, just make sure your main hexo config fields for algolia match what he described above, then re run `hexo algolia` after a `hexo clean`.

**Comment by LouisBarranqueiro** [comment]
good news 🎉. No worries, it was not specified in the documentation. I will update it :)
