### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by ChadDongDongChen** [LouisBarranqueiro/hexo-theme-tranquilpeak#529]
![image](https://user-images.githubusercontent.com/20555258/55709099-23ee9a80-5a1a-11e9-88f3-e27607adfa58.png)

**Comment by bmitchinson** [comment]
In the future, please fill out the template that you instead deleted, and avoid sending large screenshots. Would be easier to help if you fill out the requested information, and paste the error as text. I'll do my best to help out though 👍 

Searching for jsdom issues in the context of tranquilpeak gave this result #244 , i'd look there, the bottom post helps.

**Comment by LouisBarranqueiro** [comment]
👋 @ChadDongDongChen,

Please read this section https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/DOCUMENTATION.md#modifying-the-theme to install dependencies of the theme to fix this problem.
