### ISSUE TITLE
Grunt High Vulnerability Issue

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#530]
### Configuration

 - **Operating system with version** : Windows_NT 10.0.17134 win32 x64
 - **Node version**:  10.14.2
 - **Hexo-cli version**: 1.1.0
 - **Tranquilpeak version**: Original

NPM Audit reports this high vulnerability within grunt

![image](https://user-images.githubusercontent.com/33632286/56088578-8b0cb480-5e49-11e9-9151-3d9aadba9551.png)

**Comment by LouisBarranqueiro** [comment]
👋 @bmitchinson , I took care of that in https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/be31455f77164041cb624690ed1f66412ae8d74e
