### ISSUE TITLE
Duplicate package.json scripts

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#531]
Why are npm build and npm prod and npm grunt all a thing?

Isn't build a duplicate? Is that there for convenience ?

![image](https://user-images.githubusercontent.com/33632286/56088638-91e7f700-5e4a-11e9-993e-3c09d1548e50.png)

**Comment by LouisBarranqueiro** [comment]
👋@bmitchinson, this is just for convenience so I can do everything with NPM scripts :)
