### ISSUE TITLE
Add SRI to CDN delivered scripts

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#544]
Since this theme pulls in multiple 3rd party scripts (disquis, gitment, gitalk, algolia, etc...) which are often delivered via CDN I think we should consider adding [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). Especially for things like gitment which isn't delivered via a versioned CDN and could easily be changed by the author at any point.

Happy to add this at some point this week. Thankfully most of the CDNs used in the theme offer a simple "copy SRI" option which should make the deployment easier:

![Screen Shot 2019-05-27 at 2 52 45 AM](https://user-images.githubusercontent.com/718681/58408183-86cbdd80-802a-11e9-9b26-9827eb045a3b.png)

**Comment by LouisBarranqueiro** [comment]
👋 @fletchto99 , that's a great idea!

**Comment by fletchto99** [comment]
I've begun this work in https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/545

**Comment by LouisBarranqueiro** [comment]
> Perhaps if we're moving more of these libraries into the build pipeline then we can use something like https://www.npmjs.com/package/grunt-sri to compute the SRI during the build process.

This is another thing to do and NPM already guarantees that once a package is published under a specific version, it cannot be changed so we should be good. 

I'm closing this for now since we should not fetch any scripts from external resources anymore so we don't need to implement that.
