### ISSUE TITLE
Vulnerabiliy in using MomentJS 2.14.1

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#549]
### Actual behavior
Tranquilpeak is reliant on MomentJS 2.14.1, which introduced a Reg Ex DoS attack vulnerability. [Details here](https://snyk.io/test/npm/moment/2.14.1), a version bump is needed.

### Expected behavior
No vulnerabilities when using a tranquilpeak theme to build your website.

### Steps to reproduce the behavior
Start up tranquilpeak website and run a [lighthouse audit report](https://web.dev/measure) on the site. The above-mentioned vulnerability will be confirmed in use for Moment.js

**Comment by fletchto99** [comment]
I think because moment isn't part of the `package.json` the renovate bot won't pick it up. I'll open up a PR to fix this issue. This is also semi-related to the SRI work I've been doing.

**Comment by fletchto99** [comment]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/540 fixes this :)

**Comment by LouisBarranqueiro** [comment]
I'm on it :)

**Comment by LouisBarranqueiro** [comment]
done with b92e32d
