### ISSUE TITLE
Avoid Google Fonts due to GDPR

### ISSUE THREAD

**Issue by rschaeuble** [LouisBarranqueiro/hexo-theme-tranquilpeak#553]
Because of the [General Data Protection Regulation (GDPR)](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), using Google Fonts is a legal gray area. When the browser fetches a font, the user's IP is sent to Google. As the IP is considered personal information, this is a problem.

Some say it's OK as long as the site's privacy statement explains that Google Fonts is used. Others disagree, and a few legal warnings have already been issued because of this. But so far there have been no court decisions on this that I'm aware of, so there is no certainty.

To avoid this issue completely, Tranquilpeak could provide the font files as static resources.

Would this be a welcome PR?

**Comment by LouisBarranqueiro** [comment]
👋 @rschaeuble , I took the time to read https://github.com/google/fonts/issues/1495 and in fact, this might be a problem. Thanks for pointing out this issue. I'm already on it.
