### ISSUE TITLE
Reading time

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/hexo-theme-tranquilpeak#554]
### Description
- **Option 1 (best):** Automatically calculate the reading time. The implementation will need to support all currently supported languages.
- **Option 2:** Add a `reading_time` variable in the front-matter of posts so users can manually enter the reading time of their posts.

Then the reading time will be displayed along with the other metadata:
<img width="783" alt="Screen Shot 2019-06-09 at 12 21 21 PM" src="https://user-images.githubusercontent.com/4705626/59163191-6849f580-8ab2-11e9-9448-cb4a2f09022c.png">

### Explanation / motivation
Motivate users to read posts because they know how long it will take.

### Additional information
- [x] I can implement this feature / improvement

**Comment by fletchto99** [comment]
I believe there is interest in a feature like this. It looks like this feature was attempted to be implemented before in #457. Furthermore, @bmitchinson also seemed quite interested in a feature such as this.

Aside from the motivations you posted, my original motivation behind this feature change was the fact that [medium](https://medium.com), a common blogging platform, displays a reading time at the top. Medium supports reading times across multiple languages, and as it turn out they actually detail their [rather simple algorithm](https://help.medium.com/hc/en-us/articles/214991667-Read-time). Something like that could be quite easy to implement and easily build upon https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/541.

**Comment by itpropro** [comment]
I already use that with tranquilpeak. We just added `hexo-wordcount` as package and added this to post/meta.ejs:
```ejs
<div><span class="post-count"><%= wordcount(post.content) %> words · <%= min2read(post.content) %> min to read</span></div>
```

**Comment by chrisjwelly** [comment]
Hi @itpropro , I'm trying to add `hexo-wordcount` to my blog as well. Facing difficulties in setting it up. In which directory is `post/meta.ejs` located? I'm currently interpreting it as `<postname>/meta.ejs` and it is giving me a reference error

**Comment by bmitchinson** [comment]
Mine has it enabled if you'd like it for reference. Would dig in more to help but have finals to study for https://github.com/bmitchinson/mitchinson.dev

**Comment by chrisjwelly** [comment]
> Mine has it enabled if you'd like it for reference. Would dig in more to help but have finals to study for https://github.com/bmitchinson/mitchinson.dev

Thanks @bmitchinson ! I had a quick look and did a global search on some keywords like "count", "wordcount", "readingtime". However, I couldn't really find anything as to how the reading time is enabled. 

Any help would be greatly appreciated. No urgency, though. Please study for your finals first!

**Comment by bmitchinson** [comment]
@chrisjwelly 

Should have linked to [my fork of the theme](https://github.com/bmitchinson/hexo-theme-tranquilpeak) and not the site itself, apologies.

See these:
- [config.yml](https://github.com/bmitchinson/hexo-theme-tranquilpeak/blob/master/_config.yml)
- [en.yml](https://github.com/bmitchinson/hexo-theme-tranquilpeak/blob/master/languages/en.yml)
- [meta.ejs](https://github.com/bmitchinson/hexo-theme-tranquilpeak/blob/master/layout/_partial/post/meta.ejs)

I just copied in this original PR, because while I agree with louis that it shouldn't be merged in until it fits all languages, I don't mind this implementation from fletchto99: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/541

**Comment by chrisjwelly** [comment]
Thanks @bmitchinson . I managed to get it working. I appreciate your help!

**Comment by LouisBarranqueiro** [comment]
Closing this issue as I will not add new feature to the theme. It is on maintenance mode.
