### ISSUE TITLE
Increase accessibility compliance (WCAG 2.1)

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#555]
### Description

I think a welcomed change by this theme's users would be increasing the [web accisiblity compliance level](https://www.w3.org/TR/WCAG21/). I believe a WCAG 2.1 level of AA would be within reason. There would be a few benefits to this change:

1. Better accessibility for readers using utilities such as screen readers.
2. A higher accessibility score leads to a [higher page rank](https://moz.com/blog/accessibility-seo-1) with many search engines.

### Explanation / motivation

The motivation behind this change was making my blog more optimized via the results of many page metrics tools (https://web.dev / https://gtmetrix.com/ / etc...). While improving accessibility would increase these scores it also offers a win in terms of compliance for accessibility tools.

There are plenty of [scanners/tools](https://www.w3.org/WAI/ER/tools/) out there that offer suggestions to ensure your page meets the WCAG score you wish to achieve. I believe we could use these tools to help us achieve an AA level of WCAG2.1.

### Additional information
- [x] I can implement this feature / improvement (if you like the idea 👍)

**Comment by LouisBarranqueiro** [comment]
Yes, it's a good idea. We need to work on the demo so we can measure the changes done (before/after). Could you please post reports here of the [demo website](https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/) done by these tools? IMO, we need to have a report for the index page and a post page. 

Once we have these reports, let's discuss what we implement to improve accessibility and ranking :)

**Comment by fletchto99** [comment]
Certainly! I'll generate reports for some of the more common tools which are recommended by browser creators. I'll generate the reports shortly and edit this comment accordingly.

**Comment by LouisBarranqueiro** [comment]
### Before on the homepage
### After on the homepage
### Before on a post

**Comment by LouisBarranqueiro** [comment]
Improvements done with https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/63ac905fea10037a619a5edaaf7a3b3fb2dae4e8
### Before on the homepage
<img width="912" alt="before homepage" src="https://user-images.githubusercontent.com/4705626/60071325-8dec1700-96ce-11e9-907a-d97e8a805251.png">

### After on the homepage
<img width="912" alt="after homepage" src="https://user-images.githubusercontent.com/4705626/60071329-90e70780-96ce-11e9-8c11-d7fac28b823b.png">

### Before on a post
<img width="914" alt="before post" src="https://user-images.githubusercontent.com/4705626/60071335-92b0cb00-96ce-11e9-9ad9-f9540bd8ee4b.png">

### After on a post
<img width="916" alt="after post" src="https://user-images.githubusercontent.com/4705626/60071337-95132500-96ce-11e9-8384-67f5284ca648.png">

**Comment by fletchto99** [comment]
I think we can still get a minor improvement for fixing the colors. [Report](https://lighthouse-dot-webdotdevsite.appspot.com/lh/html?url=https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/#accessibility)

> Background and foreground colors do not have a sufficient contrast ratio.

This should probably be an easy change but I don't have the best eye for design. Do you think this is something you might be able to do as well?

**Comment by LouisBarranqueiro** [comment]
@fletchto99 I like how the theme looks, I don't want to change that to get a better score.
