### ISSUE TITLE
Question about the the toc.

### ISSUE THREAD

**Issue by hilen** [LouisBarranqueiro/hexo-theme-tranquilpeak#560]
Hi，is there a plan to update the toc menu to the right area of the page. Just like the image below?
![image](https://user-images.githubusercontent.com/2245840/60565993-2d2ca080-9d98-11e9-89a7-d943050b7c6f.png)

**Comment by LouisBarranqueiro** [comment]
Hi @hilen,

no, I do not plan to add this feature for now because this is IMO a nice to have since there is already a TOC at the top of each post.
