### ISSUE TITLE
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Aeroever** [LouisBarranqueiro/hexo-theme-tranquilpeak#561]
### Description

I like this topic very much, but when I deploy it, getting image resources will prompt cross-domain requests. All the icons disappeared.How should I address cross-domain requests for resource access？

![image](https://user-images.githubusercontent.com/20549394/60769500-289f1980-a103-11e9-9c56-4161478fdc19.png)

### Environment
 - **Operating system with version** : 
 - **Node version**: 
 - **Hexo version**: 
 - **Hexo-cli version**: 
 - **Tranquilpeak version**: 
 - **Site configuration file**: 
 - **Theme configuration file**: 
 - **Hexo plugin**: 

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @Aeroever,

you have this error because you were on `https://yuhangyes.gitee.io`  (HTTP) and the URL of this resource is under HTTPS. Basically, you want to make sure you reach out your website using HTTPS and not HTTP. Go to `https://yuhangyes.gitee.io` you should not see this error.

**Comment by Aeroever** [comment]
The problem is solved, thank you very much.





在 2019-07-08 02:05:01，"Louis Barranqueiro" <notifications@github.com> 写道：


@Aeroever,

you have this error because you were on https://yuhangyes.gitee.io (HTTP) and the URL of this resource is under HTTPS. Basically, you want to make sure you reach out your website using HTTPS and not HTTP. Go to https://yuhangyes.gitee.io you should not see this error.
