### ISSUE TITLE
Prev/Next button truncated on small screen (firefox)

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#562]
### Description
When using firefox (68 on MacOs in my side) **(not reproducible on Chrome)** when reducing screen (or widow) size _next_/_prev_ button has visual bug effect. 

Screenshot taken from sample demo site directly https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/05/28/Elements-showcase/

<img width="722" alt="Screen Shot 2019-07-14 at 14 36 36" src="https://user-images.githubusercontent.com/275609/61183727-0b0f0a00-a645-11e9-89d8-6055d6e7e642.png">

or even on smaller

<img width="373" alt="Screen Shot 2019-07-14 at 14 39 28" src="https://user-images.githubusercontent.com/275609/61183746-398ce500-a645-11e9-9c80-2fe8a3eae3fd.png">

### Expected behavior

Same result as Chrome

<img width="663" alt="Screen Shot 2019-07-14 at 14 40 24" src="https://user-images.githubusercontent.com/275609/61183760-6a6d1a00-a645-11e9-8360-a080d51a1640.png">

<img width="402" alt="Screen Shot 2019-07-14 at 14 40 39" src="https://user-images.githubusercontent.com/275609/61183767-73f68200-a645-11e9-9b24-19ed9ced757e.png">

### Steps to reproduce the bug

1. Open firefox desktop on https://louisbarranqueiro.github.io/hexo-theme-tranquilpeak/2015/05/28/Elements-showcase/
2. Reduce widow size to trigger media query

### Environment
 - **Operating system with version** : MacOs 10.12.6
 - **Tranquilpeak version**: One deploy on https://louisbarranqueiro.github.io
 - **Site configuration file**: One deplpy on https://louisbarranqueiro.github.io
 - **Theme configuration file**: One deploy on https://louisbarranqueiro.github.io

### Additional information

- [ ] Opened on Hugo version too https://github.com/kakawait/hugo-tranquilpeak-theme/issues/322

**Comment by LouisBarranqueiro** [comment]
👋 @kakawait, this is a bug from Gecko I guess. In fact, I already did something for this issue:https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/209398b9522fb05ee5928c946ba69d45a989a3ea. 

Increasing the value to `45px` seems to "fix" the bug.
