### ISSUE TITLE
Hide scrollbar when closing sidebar

### ISSUE THREAD

**Issue by kakawait** [LouisBarranqueiro/hexo-theme-tranquilpeak#563]
### Description
When closing sidebar we can see during short interval browser scrollbar, that create a weird visual effect.

I think there is two ways to fix it:

1. Simplest using `setTimeout`

```js
swipeSidebarToLeft: function () {
    var self = this;
    // Check if the sidebar is swiped
    // and prevent multiple click on the close button with `.processing` class
    if (this.$sidebar.hasClass('pushed') && !this.$sidebar.hasClass('processing')) {
        // Swipe the sidebar to the left
        this.$sidebar.addClass('processing').removeClass('pushed processing');
        // go back to the default overflow
        setTimeout(function () {
            self.$body.css('overflow-x', 'auto');
        }, 255);
    }
},
```

2. Using `transitionated` even like https://jonsuh.com/blog/detect-the-end-of-css-animations-and-transitions-with-javascript/

I'm not Frontend dev so I don't really know which is more efficient between both

**Comment by LouisBarranqueiro** [comment]
👋 @kakawait, please follow the template to report bugs otherwise it's hard for me to reproduce them. Please also include a GIF or a video so I can the the problem.
