### ISSUE TITLE
No more hexo-theme-tranquilpeak-built-for-production-XXX.zip?

### ISSUE THREAD

**Issue by laurentkempe** [LouisBarranqueiro/hexo-theme-tranquilpeak#584]
Why in the release we are not seeing anymore a zip like hexo-theme-tranquilpeak-built-for-production-3.0.2.zip ?

**Comment by LouisBarranqueiro** [comment]
Hi @laurentkempe, sorry for the late reply. I don't add it anymore because users can build it by themselves and it created support because users didn't understand what to do once they want to change the theme.
