### ISSUE TITLE
Theme doesn't work with hexo-generator-feed anymore

### ISSUE THREAD

**Issue by itpropro** [LouisBarranqueiro/hexo-theme-tranquilpeak#588]
### Description
The hexo plugin hexo-generator-feed was updated and changed the return type of the path object.
The following lines are the cause for the problem:
```
<% if ((config.feed) && (config.feed.path.length)) { %>
        <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
    <% } %>
```
config.feed.path returns an array and the url_for helper executes the `startsWith` function on it, leading to the error.

### Expected behavior
When using hexo generate or hexo server, an error (path.startsWith is not a function) is thrown when the hexo-generator-feed plugin is installed and enabled.

### Steps to reproduce the bug
* Just initialize a clean hexo blog with `hexo init`
* install tranquilpeak as documented (npm i && npm run prod) 
* Install hexo-generator-feed with npm i --save hexo-generator-feed
* Execute hexo generate

### Environment
 - **Operating system with version** : Windows 10 1903 x64
 - **Node version**: 12.13.1
 - **Hexo version**: 4.0.0
 - **Hexo-cli version**: 3.1.0
 - **Tranquilpeak version**: 3.1.1 unmodified
 - **Site configuration file**: original
 - **Theme configuration file**: original
 - **Hexo plugin**: hexo-generator-blog

### Additional information
- [X] I can fix this bug

**Comment by itpropro** [comment]
I suggest something like the following to still be compatible with older versions of the plugin.
```
    <% if ((config.feed) && (config.feed.path.length)) { %>
        <% if (typeof config.feed.path === 'string' )) { %>
            <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path) %>">
        <% } else { %>
            <link rel="alternate" type="application/atom+xml" title="RSS" href="<%- url_for(config.feed.path[0]) %>">
        <% } %>
    <% } %>
```

**Comment by LouisBarranqueiro** [comment]
👋 @itpropro thanks for the bug report and the suggestion. I will take care of that ASAP :)
