### ISSUE TITLE
?: How can we support your development?

### ISSUE THREAD

**Issue by bmitchinson** [LouisBarranqueiro/hexo-theme-tranquilpeak#594]
Really appreciate your work Louis, having a site based on your theme really helped me feel confident applying for a job now that i'm leaving school in the Spring.

Is there anyway I could send some "coffee money" your way? 

Like Ko-Fi or something? https://ko-fi.com/

Maybe sponsors would work best? https://github.com/sponsors

![image](https://user-images.githubusercontent.com/33632286/71201815-6c747e00-2260-11ea-9267-88b634ed134d.png)

**Comment by fletchto99** [comment]
If you're interested in joining the sponsors program let me know. I'll see if there's anything I can do internally to state this would be an awesome project that should be onboarded into our sponsors program (no promises I can do anything though).

**Comment by LouisBarranqueiro** [comment]
👋 @bmitchinson  @fletchto99  buddies, I really appreciate that you thought about this but I don't need money to motivate me, or have a reason to continue to work on this project. I just do it because I want it, I wanna help the community and I don't expect anything in return.
