### ISSUE TITLE
[Pending] Update to latest gitalk once a release is cut

### ISSUE THREAD

**Issue by fletchto99** [LouisBarranqueiro/hexo-theme-tranquilpeak#596]
Hey @LouisBarranqueiro,

I know you're getting close to cutting a new release of the theme for Hexo v4. Would it be possible to hold off on cutting a new release until gitalk pushes a new release to NPM? I've opened an issue on their repo https://github.com/gitalk/gitalk/issues/336 to track this. It contains a few important fixes I'd like to see in the new version of the theme.

Thanks!

**Comment by LouisBarranqueiro** [comment]
👋 Renovate will update `gitalk` dep as soon as a new version is released. I will make a release after that.
