### ISSUE TITLE
Can't see tags in all-tag page

### ISSUE THREAD

**Issue by tooOpen** [LouisBarranqueiro/hexo-theme-tranquilpeak#598]
Hi my blog not applied tags

when I click tag in blog

there is only all-tag text.

my post has 2 tags workout, emotion but 

tag post empty even no tag button

can you help me?

https://github.com/tooOpen/tooOpen.github.io

here is my blog 

Thank you

**Comment by LouisBarranqueiro** [comment]
👋 Could you please open a new issue and respect the bug to report a template? this will help me to understand your problem. The template is here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md&title=
