### ISSUE TITLE
It's useless set lauguage to "zh_CN" 

### ISSUE THREAD

**Issue by wgspring** [LouisBarranqueiro/hexo-theme-tranquilpeak#600]
### Description
When I following the `DOCUMENTATION.md` to set `_config.yml`  language as `zh_CN`, I found is doesn't work.  But I set language as `zh_cn`, it is usefull.

There is the following paragraph in the `DOCUMENTATION.md`:

``` markdown
Currently, the theme is delivered with:

Chinese (zh-CN)
Chinese Traditional (zh-TW)
English (en)
French (fr-FR)
Japanese (ja)
Portuguese (pt-BR)
Russian (ru)
Spanish (es)
```

I think this description is misleading. It might be better to change it to the following.

``` markdown
Currently, the theme is delivered with:

Chinese (zh-cn)
Chinese Traditional (zh-tw)
English (en)
French (fr-fr)
Japanese (ja)
Portuguese (pt-br)
Russian (ru)
Spanish (es)
```

### Expected behavior
 
The page lauguage should be Chinese.

### Steps to reproduce the bug
set `language` in  `_config.yml`  as `zh_CN`, and then run server.

### Environment
 - **Operating system with version** : deepin 15.11
 - **Node version**: v12.14.0
 - **Hexo version**: 4.2.0
 - **Hexo-cli version**: 3.1.0
 - **Tranquilpeak version**: original

### Additional information
- [x] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @wgspring, I updated the documentation. Thanks for reporting this problem.
