### ISSUE TITLE
The browser can't parse if {% hl_text%} next line is headline

### ISSUE THREAD

**Issue by chilo-hzl** [LouisBarranqueiro/hexo-theme-tranquilpeak#611]
The broswer can correctly parse headline if don't have {% hl_text %}{% endhl_text %},
if have this tag the next line is ### xxx

**Comment by LouisBarranqueiro** [comment]
👋 @chilo-hzl, I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
