### ISSUE TITLE
The browser can't correctly parse headline

### ISSUE THREAD

**Issue by chilo-hzl** [LouisBarranqueiro/hexo-theme-tranquilpeak#612]
### Description

The browser can't correctly parse headline When i used {% hl_text %}{% endhl_text %} tag in the previous row(headline on next line of tags),

### Expected behavior

I hope the browser can correctly parse headline when it was located next line of tag

### Steps to reproduce the bug
 
```
# headline
<p>Here are some{% hl_text green %}texts{% endhl_text %}</p>
## headline
```
### Environment
 - **Operating system with version** : win10
 - **Node version**: 12.14.0
 - **Hexo version**: 4.2.0 - **Hexo-cli version**: 3.1.0
 - **Tranquilpeak version**: original
 - **Site configuration file**: 
 - **Theme configuration file**: 
 - **Hexo plugin**: 

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @chilo-hzl, this is not a bug. The markdown-renderer library used in Hexo requires a new line before headlines. Try that, it should work:
``` text
# headline
<p>Here are some{% hl_text green %}texts{% endhl_text %}</p>

## headline
```

**Comment by chilo-hzl** [comment]
No, this way i had tried, but it doesn't work, such as 
```
# one
<p>ddb fidvf vkdfvfdk dsvdbcs {% hl_text green%}这是一段文字{% endhl_text %} 123</p>

## two
<p>ddb fidvf vkdfvfdk dsvdbcs {% hl_text green%}这是一段文字{% endhl_text %} 123</p>

### three
<p>ddb fidvf vkdfvfdk dsvdbcs {% hl_text green%}这是一段文字{% endhl_text %} 123</p>

#### four
<p>ddb fidvf vkdfvfdk dsvdbcs {% hl_text green%}这是一段文字{% endhl_text %} </p>
```
youcan see test that will be like this [my Blog](https://chilo-hzl.github.io/)
even i use diffenent editor, it like same

**Comment by LouisBarranqueiro** [comment]
👋 I've managed to reproduce the issue. This is either related to [hexo](https://github.com/hexojs/hexo) or the hexo render library used.

I suggest you open an issue on the repository of Hexo. Here is a quick example to reproduce this problem with the builtin Hexo tag:
```
# one
{% blockquote david %}block1{% endblockquote %}

## two
{% blockquote frank %}block2{% endblockquote %} 
```

Hexo tags with ending tags corrupt the rest of the text if the ending block is not on a new line.

this example will work:
```
# one
{% blockquote david %}block1
{% endblockquote %}

## two
{% blockquote frank %}block2{% endblockquote %}
```

To sum up and solve this problem for you now, you need to do:
```
# one
<p>ddb fidvf vkdfvfdk dsvdbcs 
{% hl_text green%}
这是一段文字
{% endhl_text %} 
123</p>

## two
<p>ddb fidvf vkdfvfdk dsvdbcs 
{% hl_text green%}
这是一段文字
{% endhl_text %} 
123</p>

### three
<p>ddb fidvf vkdfvfdk dsvdbcs 
{% hl_text green%}
这是一段文字
{% endhl_text %}
 123</p>

#### four
<p>ddb fidvf vkdfvfdk dsvdbcs 
{% hl_text green%}
这是一段文字
{% endhl_text %}
</p>
```

**Comment by chilo-hzl** [comment]
Thank you so much for helping me, i will open an issue on Github of Hexo
