### ISSUE TITLE
i encountered a new promble.

### ISSUE THREAD

**Issue by l8higher** [LouisBarranqueiro/hexo-theme-tranquilpeak#618]
when i print'hexo s‘ and turn on localhost
![截屏2020-03-10 下午3 04 23](https://user-images.githubusercontent.com/57839836/76287869-70082600-62e0-11ea-8b5d-5ec0fcb18270.png)
I have no idea,i hope you can help me !!

**Comment by LouisBarranqueiro** [comment]
👋 @l8higher , I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
