### ISSUE TITLE
How to update theme without losing all configs?

### ISSUE THREAD

**Issue by tienhm0202** [LouisBarranqueiro/hexo-theme-tranquilpeak#622]
How can I silent update tranquilpeak theme (from 3.0.1 to latest) without losing all my current config?

Or can you provide some tips to do it easiest, please?

**Comment by LouisBarranqueiro** [comment]
@tienhm0202, not really, simply replace all files expect the config. If you modified the theme, only you, know what needs to be replaced. Unfortunately, there is no command to perform an update.

Also, this theme is quite old and the config for the theme is inside the theme which is not ideal. New Hexo versions enable theme configs to be outside so maybe I will invest some time a day to make this change to enable users to easily update the theme.

**Comment by tienhm0202** [comment]
That's awesome, @LouisBarranqueiro. I think I should close this issue as my question is done.

I hope your new release with outside configs will be launched soon.
