### ISSUE TITLE
where to set value of   header-title-link

### ISSUE THREAD

**Issue by iushas** [LouisBarranqueiro/hexo-theme-tranquilpeak#625]
![image](https://user-images.githubusercontent.com/7236171/79183007-dd105d80-7e42-11ea-9b31-a03cd296221a.png)

I have the error :  Cannot GET /%20/   
![image](https://user-images.githubusercontent.com/7236171/79183104-18129100-7e43-11ea-8dfa-a9b154221814.png)

**Comment by iushas** [comment]
I can't find  the place to set the conifg value of   header-title-link

**Comment by iushas** [comment]
oh , i find it !!  sidebar_behavior ..

**Comment by LouisBarranqueiro** [comment]
👋 @iushas , I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
