### ISSUE TITLE
header title link error

### ISSUE THREAD

**Issue by oe** [LouisBarranqueiro/hexo-theme-tranquilpeak#634]
### Description
When clicking header title in a post, it will redirect to `/%20/`, which will cause a 404 error.   The redirect is incorrect.

This error is caused by the following code(L19)

https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/b6090f86d598fba44ab475df4cf14a264ce22093/layout/_partial/header.ejs#L16-L22

Replacing `url_for (' ')` to `url_for ('')` or `url_for ('/')` can fix this issue.

**Comment by LouisBarranqueiro** [comment]
👋 @oe, I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
