### ISSUE TITLE
The search page never opens

### ISSUE THREAD

**Issue by TomatoesMan** [LouisBarranqueiro/hexo-theme-tranquilpeak#638]
When you click the search button, the URL changes, but no search box pops up

**Comment by LouisBarranqueiro** [comment]
👋 @TomatoesMan , I would be happy to help you but I need you to fill the template to open a bug. This will enable me to understand your issue and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
