### ISSUE TITLE
A eroor with alogin

### ISSUE THREAD

**Issue by pi-dal** [LouisBarranqueiro/hexo-theme-tranquilpeak#641]
# I use the a login to search. But it doesn’t work 
[![9-CA393-CA-3713-4916-94-D6-4-D9-C2-F450068.png](https://i.postimg.cc/DZ41RBcM/9-CA393-CA-3713-4916-94-D6-4-D9-C2-F450068.png)](https://postimg.cc/347yvjVX)
## What can I do

**Comment by LouisBarranqueiro** [comment]
👋 @pi-dal , I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
