### ISSUE TITLE
A question of the latex

### ISSUE THREAD

**Issue by pi-dal** [LouisBarranqueiro/hexo-theme-tranquilpeak#647]
**I can't use the latex on your theme.How can I do?**

**Comment by LouisBarranqueiro** [comment]
👋 @pi-dal , I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
