### ISSUE TITLE
Can I update package with security problem ?

### ISSUE THREAD

**Issue by tienhm0202** [LouisBarranqueiro/hexo-theme-tranquilpeak#649]
![](https://i.imgur.com/MJ5378z.png)

I found these errors in security report. How can I update these issues without making theme broken? (I'm not so familiar with JS)

**Comment by LouisBarranqueiro** [comment]
👋 @tienhm0202, I would be happy to help you but I need you to respect the template to open an issue. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
