### ISSUE TITLE
JS Library need update - security issue

### ISSUE THREAD

**Issue by tienhm0202** [LouisBarranqueiro/hexo-theme-tranquilpeak#651]
### Description

I run Lighthouse in Chrome Dev Tool and its report like this. I think some JS library need updated
![Imgur](https://i.imgur.com/yq614d9.png)

### Expected behavior

It make Google score my site lower. I want to know how to update these library without break theme. 

### Steps to reproduce the bug
 
Run Lighthouse Audit in Chrome

### Environment
 - **Operating system with version** : Darwin 19.6.0 darwin x64
 - **Node version**: v14.2.0
 - **Hexo version**: 3.9.0
 - **Hexo-cli version**: 2.0.0
 - **Tranquilpeak version**: Original 3.0.1
 - **Site configuration file**: 
 - **Theme configuration file**: 
 - **Hexo plugin**: 

```
├── hexo@3.9.0
├── hexo-algoliasearch@0.4.2
├── hexo-cli@2.0.0
├── hexo-deployer-git@2.1.0
├── hexo-fs@2.0.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-seo-friendly-sitemap@0.0.25
├── hexo-generator-tag@0.2.0
├── hexo-lazyload-image@1.0.7
├── hexo-migrator-wordpress@0.1.2
├── hexo-oembed@0.1.6
├── hexo-pwa@0.1.3
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
└─┬ UNMET DEPENDENCY hexo-web-push-notification@0.2.2
  ├── hexo-fs@2.0.0
  ├── hexo-util@1.9.0
  └── node-fetch@2.6.0
```

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋 @tienhm0202 , I will release a new version soon with the latest jQuery version: v3.5.1

**Comment by LouisBarranqueiro** [comment]
the fix is included in this commit
