### ISSUE TITLE
Algoliasearch repeated installation

### ISSUE THREAD

**Issue by pi-dal** [LouisBarranqueiro/hexo-theme-tranquilpeak#656]
Hey, hello. I found that when I use ```npm install && npm run prod```, algoliasearch@3.35.1 is already installed by default. Then why do I need to install it in my blog directory?

**Comment by LouisBarranqueiro** [comment]
👋 @pi-dal, I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Also, what do you mean with "algoliasearch@3.35.1 is already installed by default"? Node modules are not included in the source of the theme (`there is no `node_modules` folder), so you have to install it with `npm install`.

Please re-open this issue as soon as you updated it.
