### ISSUE TITLE
Link to title

### ISSUE THREAD

**Issue by pi-dal** [LouisBarranqueiro/hexo-theme-tranquilpeak#659]
When I used your theme, I found that the link to the website title at the top of the article was /%20.
like this:
![title](https://user-images.githubusercontent.com/53357798/91176504-f2609700-e714-11ea-8d8d-44f63ad9485b.png)
![link](https://user-images.githubusercontent.com/53357798/91176534-fc829580-e714-11ea-854d-5a1c9fd7c4b7.png)

**Comment by pi-dal** [comment]
Now I solve the problem of title link.See [#660](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/pull/660)

**Comment by LouisBarranqueiro** [comment]
👋 @pi-dal , this problem has been already fixed with this commit: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/commit/ace4a951a53a77be945c92d9b62d6c8d6cb02c4d

I will release a new version of the theme this WE.

**Comment by pi-dal** [comment]
@LouisBarranqueiro Wow, that's really good news. I will look forward to it coming.😁
