### ISSUE TITLE
How can I set Utterence in tranquilpeak?

### ISSUE THREAD

**Issue by hanseul-lee** [LouisBarranqueiro/hexo-theme-tranquilpeak#668]
I want to set utterence on my blog

I did three things like below

1. _config.yml
```utterances:
  enable: true
  repo: hanseul-lee/blog-comments
  issue_term: title
  theme: github-light
```

2. /themes/tranquilpeak/layout/post.ejs
```
<%- partial('_partial/post', {post: page}) %>
<%- partial('comment') %>
```

3. /themes/tranquilpeak/layout/comment.ejs
```
<!--  utteranc comment -->
<% if (config.utterances.enable == true) { %>
  <script src="https://utteranc.es/client.js"
  repo="hanseul-lee/blog-comments"
  issue-term="title"
  theme="github-light"
  crossorigin="anonymous"
  async>
</script>
  <% } %>
```

Aftert that, I can see the the utterence comment layout,
but when I clicked the comment button, 404 error occurred
https://hanseul-lee.github.io/  here is my blog link

I don't know how to solve this
so could you please help me?

**Comment by LouisBarranqueiro** [comment]
👋 @hanseul-lee this theme does not integrate with utterence so I won't be able to guide you to integrate it. Does utterence have a guide to integrate their comment system with any theme? Does utterence can be added to any theme?

**Comment by hanseul-lee** [comment]
@LouisBarranqueiro Yes, I saw lots of blog postings integrated with utterence. In [utternce.es](https://utteranc.es/) also say that "Add the following script tag to your blog's template.". But I don't know where to put it.

**Comment by LouisBarranqueiro** [comment]
the fact that the layout is displayed means that you correctly integrated it into the theme. Now, if you encounter an error when you comment, it probably has nothing to do with the theme. You can try utterence with another theme to confirm. I suggest posting the 404 error you have as well with the logs of the error on utterence repository/support channel. From what I have seen with comment systems like this one is misconfiguration so you want to double-check that.

**Comment by hanseul-lee** [comment]
ok. thank you:)
