### ISSUE TITLE
Showing post folder instead of posts

### ISSUE THREAD

**Issue by flor14** [LouisBarranqueiro/hexo-theme-tranquilpeak#669]
Hello!

Do you have any clue how I can fix this? 

Where the posts were shown before, now I can read "Posts". If I click there I can have access to the posts but I would like to see them again on the main page.

If you can help me I would really appreciate it.

Now:
![image](https://user-images.githubusercontent.com/29610858/105266941-1adba880-5b70-11eb-875e-2eb3e11dadb2.png)

**Comment by LouisBarranqueiro** [comment]
👋 @flor14 , I would be happy to help you but I need you to respect the template to open a bug. This will enable me to understand the problem and help you. You can find the template here: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/new?assignees=LouisBarranqueiro&labels=&template=bug-report.md

Please re-open this issue as soon as you updated it.
