### ISSUE TITLE
posts folder appear instead of the posts

### ISSUE THREAD

**Issue by flor14** [LouisBarranqueiro/hexo-theme-tranquilpeak#670]
### Description
This is the blog working properly https://florencia.netlify.app/

But since the last time when I opened it locally, it appears the post folder on the screen instead of the posts 
![image](https://user-images.githubusercontent.com/29610858/105588755-5e046a00-5d70-11eb-918a-479e80e5b821.png)

The blog has a link I included in the past to switch between the Spanish and English versions.  When I press "continue reading" and finally I can see the posts on-screen, seems that the language switcher link name changes to "posts" (if you have another idea on how to include a link or button like that, I accept ideas about this too). This makes me think that maybe it is something in the theme that changed its behavior.

![image](https://user-images.githubusercontent.com/29610858/105580935-2dbbcc00-5d6e-11eb-8226-01669ab88480.png)

This blog was created a while ago and it needs an update soon (I did not find the time yet). I understand that could be something not working locally, but if you have any clue it would be helpful. If not, thank you anyway. :)

### Expected behavior

I expect to see the blog as the last version running https://florencia.netlify.app/

### Steps to reproduce the bug
 
Something changed in the behavior of the blog locally. Probably is my environment, but not a clue what can produce this change.

### Environment
 - **Operating system with version** : 
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

 - **Node version**: 
 - **Hexo version**: 
 - **Hexo-cli version**: 
  I am running it locally from R with blogdown v0.21 package and using HUGO v0.54.0
 - **Tranquilpeak version**: "0.4.4-BETA"
 - **Site configuration file**: 
 -https://github.com/flor14/florblog/blob/master/config.toml
 - **Theme configuration file**: 
 https://github.com/flor14/florblog/tree/master/themes/hugo-tranquilpeak-theme
 - **Hexo plugin**: 

### Additional information
- [ ] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
Hi Flor, I see that you are using Hugo and not Hexo. This repository is for the theme available on Hexo. You want to create an issue on https://github.com/kakawait/hugo-tranquilpeak-theme
