### ISSUE TITLE
algoliasearch.js not exists

### ISSUE THREAD

**Issue by ficapy** [LouisBarranqueiro/hexo-theme-tranquilpeak#672]
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/ed3841ccb74391f16f26c4628e08a1625f3b7a92/tasks/config/copy.js#L82-L83

The algoliasearch.js file does not exist in the new version and will make algoliasearch not work.

**Comment by ficapy** [comment]
I put the algoliasearch.js file from version 3.35.1 into the `node_modules/algoliasearch/dist/`, and it works fine now. Hope you can fix this compatibility issue @LouisBarranqueiro

**Comment by LouisBarranqueiro** [comment]
👋 @ficapy , thanks for reporting this problem. Just fixed it and released a new version: https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/releases/tag/v4.1.2
