### ISSUE TITLE
Npm install Error - install issue

### ISSUE THREAD

**Issue by KirisameMarisas** [LouisBarranqueiro/hexo-theme-tranquilpeak#686]
### Description
Npm reports Error after I running the command "npm install" .Is the version compatibility issue?
![5 @0XN SQ GYEH8X %RJCB](https://user-images.githubusercontent.com/49802446/128834020-d6803423-8afb-4365-966c-491b802163c1.png)  
![@9Q812(WS9P_7NW}`9~~6MG](https://user-images.githubusercontent.com/49802446/128837786-73fdc944-1e1d-4d0d-8df7-01f5a8c80eba.png)
![OKII7V{K 8~4E 7 TZJ Z$V](https://user-images.githubusercontent.com/49802446/128837913-e49b875b-48ff-440d-9071-d8e8b837f491.png)

### Expected behavior
Install the theme correctly.

### Steps to reproduce the bug
Run "npm install" in theme folder 

### Environment
 - **Operating system with version** : Ubuntu20.04.2 (WSL2 in Windows10 2004)
 - **Node version**:  v16.6.1
 - **Hexo version**:  5.4.0
 - **Hexo-cli version**:  4.3.0
 - **Tranquilpeak version**: original 4.1.2
 - **Site configuration file**: 
 - **Theme configuration file**: 
 - **Hexo plugin**:   
``` txt  
├── hexo-generator-archive@1.0.0 
├── hexo-generator-category@1.0.0  
├── hexo-generator-index@2.0.0  
├── hexo-generator-tag@1.0.0  
├── hexo-renderer-ejs@1.0.0  
├── hexo-renderer-marked@4.0.0  
├── hexo-renderer-stylus@2.0.1  
├── hexo-server@2.0.0  
├── hexo-theme-landscape@0.0.3  
└── hexo@5.4.0   
```
### Additional information
It seems the error that causes on hexo-renderer-sass doesn't change dependencies version. I reported this bug on the project issue.
Also a lot of security vulnerabilities in old version dependencies.
- [x] I can fix this bug

**Comment by LouisBarranqueiro** [comment]
👋  @KirisameMarisas,  It might be related to node v16. Could you please try with the active LTS version -> node v14? https://nodejs.org/en/about/releases/

**Comment by KirisameMarisas** [comment]
I have tried with node v14, but it still have this problem.  And I fix it with modifying the package.json file , change "node-sass" from 5.0.0 to 6.0.0 and the problem is solved.
By the way , some dependencies have high-risk vulnerabilities  because of old version , using safer dependencies or trying to implement it as safe as possible.

**Comment by LouisBarranqueiro** [comment]
I see. thanks for the tip. I'm gonna release a new version of the theme with updated dependencies.

**Comment by LouisBarranqueiro** [comment]
done 🙂
