### ISSUE TITLE
Use relative path for thumbnail image url

### ISSUE THREAD

**Issue by bfcs** [LouisBarranqueiro/hexo-theme-tranquilpeak#695]
### Description

scripts/filters/thumbnail_image_url.js

```javascript
return urlFor(post.permalink + post.thumbnailImage);
```
Currently the thumbnail image url is `post.permalink + post.thumbnailImage`,  
e.g. `https://username.github.io/2021/12/09/postname/imagename.jpg`

When use `hexo server` to preview  locally, there is a 404 error to get the thumbnail image. The image won't show.

![image](https://user-images.githubusercontent.com/52602045/145536406-c4601fc5-fdb3-4827-a560-f57014883801.png)
![image](https://user-images.githubusercontent.com/52602045/145535889-343bb467-f2b9-4560-982d-0656fc17ac44.png)

I recommend using relative path for  thumbnail image url.
e.g. `/2021/12/09/postname/imagename.jpg`

### Explanation / motivation

To preview locally, solve the 404 error.

### Additional information
- [x] I can implement this feature / improvement 

I suggest replace above js code to 
```javascript
return urlFor( new URL(post.permalink).pathname + post.thumbnailImage);
```
I have tested it and it works ok both locally and Github Page, if you agree, I can make a pull request

**Comment by bfcs** [comment]
the same issue found in generated search result page
source/_js/search-modal.js 
```javascript
 html += '<a class="link-unstyled" href="' + (post.link || post.permalink) + '">';
```

**Comment by LouisBarranqueiro** [comment]
👋 @bfcs, I would like to help you but I need more information. Could you please fill out the template to report a bug (including versions of your module, hexo, system, etc...)?

**Comment by bfcs** [comment]
Hi, @LouisBarranqueiro ,
The issue is environment independent. When you config the url in `_config.yml`, the result of `post.permalink` is `https://bfcs.github.io/yyyy/mm/dd/title` 
![image](https://user-images.githubusercontent.com/52602045/145918398-849559fc-d93d-4f94-ba89-4045be0db510.png)

so 
scripts/filters/thumbnail_image_url.js
```javascript
return urlFor(post.permalink + post.thumbnailImage);
```
result is `https://bfcs.github.io/yyyy/mm/dd/title/thumbnailImage.png`

but currently the site haven't deployed, so get the url will return a 404 error.

I suggest use relative path, `/yyyy/mm/dd/title/thumbnailImage.png`

**Comment by LouisBarranqueiro** [comment]
👋 @bfcs, could you please fill out the template to report a bug (including versions of your module, hexo, system, etc...)? I believe this problem is related to the version of Hexo because it works well on my side. Please re-open this issue when you updated the issue with the information needed.
