### ISSUE TITLE
How would I go on about implementing a dark mode

### ISSUE THREAD

**Issue by wasi-master** [LouisBarranqueiro/hexo-theme-tranquilpeak#697]
The theme is great but the only issue I have is that it doesn't have a dark theme by default like [NexT](https://theme-next.js.org/). How could I achieve a dark mode like that?

**Comment by LouisBarranqueiro** [comment]
👋 @wasi-master, it would require a lot of CSS changes. That's quite some work.

**Comment by wasi-master** [comment]
Well okay then.
