### ISSUE TITLE
Disqus not work

### ISSUE THREAD

**Issue by CHYGO1985** [LouisBarranqueiro/hexo-theme-tranquilpeak#704]
I have already set the shortname in __config.yml, and the page showes  "We were unable to load Disqus." , the disques comment section works fine before, is there a bug here?

**Comment by LouisBarranqueiro** [comment]
👋 @CHYGO1985 Could you please use the template to report a bug? It will help me understand what the problem could be. 

> he disques comment section works fine before

Before what?

**Comment by CHYGO1985** [comment]
> 

Hi @LouisBarranqueiro  Thank you so much for your reply. I forgot I have left a message here, the issue has been resolved via following the recent instructions published from Disqus side :) Again thank you again for getting back to me
