### ISSUE TITLE
Add horizontal scroll bar for overflow table

### ISSUE THREAD

**Issue by panxiuwen** [LouisBarranqueiro/hexo-theme-tranquilpeak#705]
### Description
The wide table will overflow in the narrow screen.
![QQ截图20220629151039](https://user-images.githubusercontent.com/35104739/176374836-6a20a017-79d4-415d-827c-c98e26dd98e8.jpg)

I hope add the slide bar in the table, just like Typora.
![image](https://user-images.githubusercontent.com/35104739/176375257-2f5da770-f142-47fe-805f-353907c7f316.png)

**Comment by LouisBarranqueiro** [comment]
👋 @panxiuwen,  Could you please share the websites to test that?

> I hope add the slide bar in the table, just like Typora

what is typora?

**Comment by panxiuwen** [comment]
Hi @LouisBarranqueiro Thank you so much for your reply.

[My websit](https://panxiuwen.pages.dev/posts/2004/)  use tranquilpeak theme with multi-column tables. The table work well in widescreen devices like PC, but you can see the overflow table in mobile devices.

Typora is a markdown editor, and I hope those two gif [Typora](https://raw.githubusercontent.com/panxiuwen/UnixBench-Score/master/Typora.gif),[hexo](https://raw.githubusercontent.com/panxiuwen/UnixBench-Score/master/hexo.gif) can help you understand what trouble have happened

I appreciate you taking the time to check my issue and getting back to me. I hope my broken English make you understand what I need.

**Comment by panxiuwen** [comment]
Dear @LouisBarranqueiro  Thank you so much for your reply.
I use the Html syntax to solve this problem, just like this
```
<div style="overflow-x:auto;white-space:nowrap;">
<table>
···
</table>
</div>
```
I hope this give a reference for the green hand just like me.
