### ISSUE TITLE
how keep one of  page at top of index page 

### ISSUE THREAD

**Issue by kirk-zhang58** [LouisBarranqueiro/hexo-theme-tranquilpeak#707]
![image](https://user-images.githubusercontent.com/46363359/198825370-d24d398b-fd32-41dc-82ad-955d2169b4d2.png)

more like above capture,  i wanna keep page which of i drawed at top of index page . how do it

**Comment by LouisBarranqueiro** [comment]
👋 @SimonTeo58 , you want to pin this post on the first page, right? The only way is to use a date in the future.
