### ISSUE TITLE
Floating Table of Contents (side)

### ISSUE THREAD

**Issue by Y7-Lee** [LouisBarranqueiro/hexo-theme-tranquilpeak#716]
Hi, will tranquilpeak support Floating Table of Contents ? It is functional.

**Comment by panxiuwen** [comment]
@Y7-Lee Is this for you? https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/issues/705

**Comment by LouisBarranqueiro** [comment]
👋  @Y7-Lee, unfortunately, I don't add new or improve existing features. The theme is in maintenance mode.
